<style>
/* Compatibility layer for legacy ny-* admin screens. Kept here so every admin route receives the same visual system. */
.ny-main .ny-route-wrap,.ny-main .ny-vessel-wrap,.ny-main .ny-form-wrap,.ny-main .ny-departure-form,.ny-main .ny-seat-wrap,.ny-main .ny-aircraft-wrap,.ny-main .ny-air-route-wrap,.ny-main .ny-cargo-wrap{max-width:1120px!important;margin-inline:auto!important}
.ny-main .ny-route-hero,.ny-main .ny-vessel-hero,.ny-main .ny-seat-heading,.ny-main .ny-air-hero,.ny-main .ny-cargo-hero{border-radius:var(--ny-radius-lg)!important;background:linear-gradient(120deg,var(--ny-primary),var(--ny-primary-hover))!important;box-shadow:var(--ny-shadow-sm)!important}
.ny-main .ny-card,.ny-main .ny-form-card,.ny-main .ny-seat-panel,.ny-main .ny-seat-map,.ny-main .ny-table,.ny-main .ny-vessel-table,.ny-main .ny-route-table,.ny-main .ny-air-table{border-color:var(--ny-border)!important;border-radius:var(--ny-radius-lg)!important;box-shadow:var(--ny-shadow-sm)!important}
.ny-main .ny-card input,.ny-main .ny-card select,.ny-main .ny-card textarea,.ny-main .ny-form-card input,.ny-main .ny-form-card select,.ny-main .ny-form-card textarea,.ny-main .ny-grid input,.ny-main .ny-grid select,.ny-main .ny-grid textarea,.ny-main .ny-fields input,.ny-main .ny-fields select,.ny-main .ny-fields textarea{border-color:var(--ny-border)!important;border-radius:var(--ny-radius-sm)!important;min-height:44px!important}
.ny-main .ny-save,.ny-main .ny-button,.ny-main .ny-vessel-button,.ny-main .ny-air-button,.ny-main .ny-route-actions .ny-btn{border-radius:var(--ny-radius-sm)!important}
.ny-main .ny-table table,.ny-main .ny-vessel-table table,.ny-main .ny-route-table table,.ny-main .ny-air-table table{width:100%!important;border-collapse:collapse!important}.ny-main .ny-table th,.ny-main .ny-vessel-table th,.ny-main .ny-route-table th,.ny-main .ny-air-table th{background:#f4f8f6!important;color:var(--ny-text-muted)!important}.ny-main .ny-table td,.ny-main .ny-vessel-table td,.ny-main .ny-route-table td,.ny-main .ny-air-table td{border-top:1px solid #eaf0ed!important}
.ny-main .ny-alert,.ny-main .ny-note,.ny-main .ny-warning{border-radius:var(--ny-radius)!important}.ny-main [style*="background:#e8fbf2"]{border-radius:var(--ny-radius)!important}.ny-main [style*="background:#fff4d5"],.ny-main [style*="background:#fff8df"]{border-radius:var(--ny-radius)!important}
@media(max-width:700px){.ny-main>header{padding:14px 18px!important}.ny-main>header .ny-account{font-size:0}.ny-main>header .ny-account span{font-size:12px}.ny-main>main{padding:18px!important}.ny-main .ny-table,.ny-main .ny-vessel-table,.ny-main .ny-route-table,.ny-main .ny-air-table{overflow-x:auto!important}.ny-main .ny-route-hero,.ny-main .ny-vessel-hero,.ny-main .ny-seat-heading,.ny-main .ny-air-hero,.ny-main .ny-cargo-hero{padding:22px!important}}
</style>
