@if(app()->getLocale() === 'en')
<script>
if (!window.__navegayaI18nLoaded) { window.__navegayaI18nLoaded = true; document.addEventListener('DOMContentLoaded', () => {
  const dictionary = {
    'Tu viaje empieza en el río.':'Your journey starts on the river.',
    'La Amazonía se navega mejor.':'The Amazon is best explored by river.',
    'Destinos que nacen junto al agua.':'Destinations born beside the water.',
    'Busca rutas, compara empresas verificadas y reserva tu asiento para conocer la Amazonía a tu ritmo.':'Find routes, compare verified operators and reserve your seat to explore the Amazon at your own pace.',
    'Encuentra salidas verificadas y organiza tu viaje con información clara.':'Find verified departures and plan your trip with clear information.',
    'Viaja por rutas fluviales y descubre la riqueza de nuestra Amazonía.':'Travel by river and discover the richness of our Amazon.',
    'Buscar salida':'Find departure','Explorar rutas':'Explore routes','Explorar destinos':'Explore destinations',
    '¿A dónde quieres navegar?':'Where would you like to travel?', 'ORIGEN':'ORIGIN','DESTINO':'DESTINATION','FECHA DE SALIDA':'DEPARTURE DATE','PASAJEROS':'PASSENGERS','Selecciona ciudad':'Select city','1 pasajero':'1 passenger','2 pasajeros':'2 passengers','3 pasajeros':'3 passengers','4+ pasajeros':'4+ passengers','Rutas populares':'Popular routes',
    'ESPACIO PUBLICITARIO DISPONIBLE':'ADVERTISING SPACE AVAILABLE','¿Tu negocio atiende a viajeros de la Amazonía?':'Does your business serve Amazon travelers?','Anúnciate →':'Advertise →','OPERACIÓN EN VIVO':'LIVE OPERATIONS','Próximas salidas':'Upcoming departures','Horarios y tarifas publicados por empresas habilitadas en NavegaYA.':'Schedules and fares published by approved NavegaYA operators.','Carga disponible':'Cargo available','Pasajeros':'Passengers','Salida':'Departure','Reservar →':'Book →','Aún no hay salidas programadas.':'There are no scheduled departures yet.',
    'Lleva tu hamaca':'Bring your hammock','Consulta con la empresa si está incluida según tu categoría de viaje.':'Check with the operator whether it is included in your travel category.','Confirma antes':'Confirm beforehand','Llega con anticipación al puerto y confirma tu embarque.':'Arrive early at the port and confirm your boarding.','Agua y snacks':'Water and snacks','Para trayectos largos recomendamos llevar lo necesario.':'For long trips we recommend bringing what you need.','Equipaje seguro':'Secure luggage','El pasaje incluye 25 kg; la carga adicional se gestiona en terminal.':'Your fare includes 25 kg; extra cargo is handled at the terminal.','¿Buscas una ruta específica?':'Looking for a specific route?','Filtra por ciudad, fecha y duración del viaje.':'Filter by city, date and trip duration.','Buscar rutas':'Search routes','CONEXIONES REALES':'REAL CONNECTIONS','Corredores activos':'Active corridors','Estas conexiones proceden de las rutas y salidas registradas por las empresas, sin mapas ficticios.':'These connections come from routes and departures registered by operators, without fictional maps.','RUTA FLUVIAL':'RIVER ROUTE','salida(s) próxima(s) publicada(s). Consulta la embarcación, horario y disponibilidad.':'upcoming published departure(s). Check the vessel, schedule and availability.','Ver salidas →':'View departures →','DESCUBRE':'DISCOVER','Destinos que viven junto al río':'Destinations that live beside the river','Ver todos':'View all','Conocer destino →':'Explore destination →','¿Tienes un hotel, tour, restaurante o agencia?':'Do you run a hotel, tour, restaurant or agency?','Conecta tu negocio con viajeros que ya están planeando su viaje.':'Connect your business with travelers who are already planning their trip.','Promocionar negocio':'Promote business','La plataforma para viajes fluviales, empresas verificadas y destinos amazónicos.':'The platform for river travel, verified operators and Amazon destinations.','Ayuda':'Help','Planifica tu viaje':'Plan your trip','Iniciar sesión':'Sign in',
    'PASAJES FLUVIALES · AMAZONÍA PERUANA':'RIVER TICKETS · PERUVIAN AMAZON','Compara rutas, horarios y precios. Compra tu pasaje fluvial de manera rápida y segura.':'Compare routes, schedules and prices. Buy your river ticket quickly and securely.','Buscar pasajes →':'Find tickets →','Buscar pasajes':'Find tickets','Ver rutas':'View routes','Encuentra tu pasaje':'Find your ticket','Intercambiar origen y destino':'Swap origin and destination','SALIDAS DISPONIBLES':'AVAILABLE DEPARTURES','Elige tu ruta, compara información y compra tu pasaje con empresas verificadas.':'Choose your route, compare details and buy from verified operators.','Precio por pasajero':'Price per passenger','asiento(s) disponible(s)':'seat(s) available','Comprar pasaje':'Buy ticket','RUTAS POPULARES':'POPULAR ROUTES','Ver todas las rutas':'View all routes','próxima(s) salida(s)':'upcoming departure(s)','Desde':'From','Duración aproximada:':'Estimated duration:','VIAJA CON CONFIANZA':'TRAVEL WITH CONFIDENCE','Todo claro antes de embarcar':'Everything clear before boarding','Empresas verificadas':'Verified operators','Pago seguro':'Secure payment','Boleto con QR':'QR ticket','Atención por WhatsApp':'WhatsApp support','DESCUBRE LA AMAZONÍA':'DISCOVER THE AMAZON','Destinos amazónicos':'Amazon destinations','Ver todos los destinos':'View all destinations','NEGOCIOS PARA VIAJEROS':'TRAVELER BUSINESSES','Promociona tu negocio en NavegaYA.':'Promote your business on NavegaYA.','MIS BOLETOS':'MY TICKETS','Busca tu pasaje':'Find your ticket','Por tu seguridad, ingresa el DNI del viajero y el código de reserva o boleto. El embarque se confirma únicamente en el puerto.':'For your security, enter the traveler ID and the reservation or ticket code. Boarding is confirmed only at the port.','DNI o documento':'ID or document','Reserva RES-... o boleto BOL-...':'Reservation RES-... or ticket BOL-...','No se encontró un boleto con esa combinación de datos.':'No ticket was found with that combination of details.','Descargar PDF':'Download PDF','RESULTADOS DE TU BÚSQUEDA':'YOUR SEARCH RESULTS','Pasajes disponibles':'Available tickets','Compara horarios y selecciona la salida que más te convenga.':'Compare schedules and choose the departure that suits you best.','Horarios y salidas':'Schedules and departures','Salidas actualizadas directamente por las empresas de transporte.':'Departures updated directly by transport operators.','Encuentra tu salida':'Find your departure','Buscar horarios →':'Find schedules →','Todas las salidas':'All departures','Rutas fluviales':'River routes','Términos':'Terms','Privacidad':'Privacy','Contacto':'Contact',
    'Rutas fluviales para tu próximo viaje':'River routes for your next trip','VIAJA POR LA AMAZONÍA':'TRAVEL THE AMAZON','Compara horarios, embarcaciones y tarifas de operadores registrados.':'Compare schedules, vessels and fares from registered operators.','Rutas populares:':'Popular routes:','⚙ Filtros':'⚙ Filters','Todos los orígenes':'All origins','Todos los destinos':'All destinations','DURACIÓN DEL VIAJE':'TRIP DURATION','Todas las duraciones':'All durations','Menos de 12 horas':'Under 12 hours','1 a 2 días':'1 to 2 days','3 días o más':'3 days or more','Aplicar filtros':'Apply filters','salidas disponibles':'available departures','No hay salidas programadas con esos filtros.':'No departures match these filters.','Duración por confirmar':'Duration to be confirmed','horas aprox.':'hours approx.','Ver más →':'View more →',
    'Descubre la Amazonía':'Discover the Amazon','GUÍA DE DESTINOS · AMAZONÍA PERUANA':'DESTINATION GUIDE · PERUVIAN AMAZON','Ciudades conectadas por río, gastronomía viva y experiencias que comienzan al abordar.':'Cities connected by river, vibrant cuisine and experiences that start on board.','Explorar destinos →':'Explore destinations →','Ciudades que se alcanzan por río':'Cities reached by river','Planifica tu viaje':'Plan your trip','Consulta información de cada ciudad, sus atractivos, hospedajes y rutas disponibles para organizar tu próxima travesía.':'Find information about every city, its attractions, lodging and available routes for your next journey.','DESTINOS PRINCIPALES':'MAIN DESTINATIONS','rutas registradas':'registered routes','Recomendados para tu viaje':'Recommended for your trip','ESPACIO PUBLICITARIO DISPONIBLE':'ADVERTISING SPACE AVAILABLE','¿Tu negocio atiende a viajeros?':'Does your business serve travelers?','Hoteles, restaurantes, agencias y operadores pueden aparecer aquí.':'Hotels, restaurants, agencies and operators can appear here.',
    'Administración':'Administration','Principal':'Main','Operación':'Operations','Fluvial':'River','Aéreo':'Air','Ventas':'Sales','Contenido':'Content','Sistema':'System','Mi empresa':'My company','Solicitudes de empresas':'Company requests','Empresas y agencias':'Companies and agencies','Embarcaciones fluviales':'River vessels','Puertos de embarque':'Boarding ports','Rutas y salidas aéreas':'Air routes and departures','Aeronaves':'Aircraft','Carga':'Cargo','Control de embarque':'Boarding control','Reportes':'Reports','Publicidad y campañas':'Advertising and campaigns','Ciudades y destinos':'Cities and destinations','Lugares turísticos':'Tourist attractions','Hoteles y hospedajes':'Hotels and lodging','Gastronomía':'Food and dining','Usuarios y permisos':'Users and permissions','Auditoría y seguridad':'Audit and security','Configuración':'Settings','Bienvenido,':'Welcome,','Mi perfil':'My profile','Cerrar sesión':'Sign out','Nueva ruta fluvial':'New river route','Editar ruta fluvial':'Edit river route','Programar salida':'Schedule departure','Registrar embarcación':'Register vessel','Editar embarcación':'Edit vessel','Plano de asientos':'Seat map','Nueva ruta aérea':'New air route','Programar salida aérea':'Schedule air departure','Registrar carga':'Register cargo','Recepción de carga':'Cargo intake','Resultados de la operación':'Operation results','Ver reporte':'View report','Descargar CSV':'Download CSV','Guardar':'Save','Cancelar':'Cancel','Editar':'Edit','Eliminar':'Delete','Volver':'Back','Limpiar':'Clear','Nombre':'Name','Correo':'Email','Contraseña':'Password','Empresa':'Company','Estado':'Status','Acciones':'Actions','Fecha':'Date','Hora':'Time','Origen':'Origin','Destino':'Destination','Descripción':'Description','Asientos':'Seats','Capacidad':'Capacity','No hay registros todavía.':'There are no records yet.','No hay resultados para los filtros elegidos.':'There are no results for the selected filters.','Cargando…':'Loading…'
  };
  const walker = document.createTreeWalker(document.body, NodeFilter.SHOW_TEXT);
  const nodes = []; while (walker.nextNode()) nodes.push(walker.currentNode);
  nodes.forEach(node => { let text = node.nodeValue; Object.entries(dictionary).forEach(([source, target]) => { text = text.replaceAll(source, target); }); node.nodeValue = text; });
  document.querySelectorAll('[placeholder],[title],[aria-label]').forEach(element=>{['placeholder','title','aria-label'].forEach(attribute=>{const value=element.getAttribute(attribute);if(value&&dictionary[value])element.setAttribute(attribute,dictionary[value]);});});
  document.documentElement.lang = 'en';
}); }
</script>
@endif
<script>
document.addEventListener('DOMContentLoaded', () => {
  const planner = document.querySelector('a.button[href="#recomendados"]');
  if (!planner) return;
  planner.href = @json(route('home') . '#buscar');
  planner.textContent = document.documentElement.lang === 'en' ? 'Find tickets →' : 'Buscar pasajes →';
  planner.title = document.documentElement.lang === 'en'
    ? 'Choose origin, destination, date and number of passengers'
    : 'Elige origen, destino, fecha y cantidad de pasajeros';
});
</script>
