<x-public-layout title="Afiliación de empresas · NavegaYA">
<main class="min-h-screen bg-slate-50 px-4 py-10 sm:px-6 lg:px-8"><div class="mx-auto max-w-6xl">
@if(session('status'))<div class="mb-6 rounded-2xl border border-emerald-200 bg-emerald-50 p-4 text-sm text-emerald-800">{{ session('status') }}</div>@endif
<div class="grid items-start gap-8 lg:grid-cols-[320px_minmax(0,1fr)]">
<aside class="rounded-3xl bg-emerald-950 p-7 text-white lg:sticky lg:top-6"><span class="text-xs font-black uppercase tracking-[.18em] text-emerald-300">Red de operadores</span><h1 class="mt-3 text-3xl font-black leading-tight">Afíliate a NavegaYA</h1><p class="mt-3 text-sm leading-6 text-emerald-100/75">Envía los datos legales de tu empresa. Revisaremos el expediente antes de habilitar tu panel.</p><ol class="mt-8 space-y-5 text-sm">@foreach([['1','Envía la solicitud','Completa los datos y adjunta los documentos.'],['2','Confirma tu correo','Usa el enlace que recibirás por email.'],['3','Validamos el expediente','NavegaYA revisa identidad y permisos.'],['4','Activa tu cuenta','Al aprobarse, crearás tu contraseña.']] as [$n,$title,$copy])<li class="flex gap-3"><span class="flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-emerald-300 font-black text-emerald-950">{{$n}}</span><span><strong class="block">{{$title}}</strong><small class="text-emerald-100/65">{{$copy}}</small></span></li>@endforeach</ol></aside>
<section class="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-xl"><header class="border-b border-slate-100 p-6 sm:p-8"><span class="text-xs font-black uppercase tracking-wider text-emerald-700">Solicitud de afiliación</span><h2 class="mt-2 text-2xl font-black text-slate-950">Datos de la empresa transportista</h2><p class="mt-1 text-sm text-slate-500">Los campos marcados son necesarios para evaluar la solicitud.</p></header>
@if($errors->any())<div class="mx-6 mt-6 rounded-2xl border border-rose-200 bg-rose-50 p-4 text-sm text-rose-800 sm:mx-8"><strong>Revisa la información ingresada.</strong><ul class="mt-2 list-inside list-disc">@foreach($errors->all() as $error)<li>{{$error}}</li>@endforeach</ul></div>@endif
<form action="{{ route('company.registration.store') }}" method="POST" enctype="multipart/form-data" class="space-y-8 p-6 sm:p-8">@csrf
<fieldset><legend class="mb-4 text-sm font-black text-slate-900">1. Información legal y operativa</legend><div class="grid gap-4 sm:grid-cols-2"><x-company-field name="ruc" label="RUC (11 dígitos)" placeholder="20XXXXXXXXX" required/><x-company-field name="legal_name" label="Razón social" placeholder="Transportes del Oriente S.A.C." required/><x-company-field name="commercial_name" label="Nombre comercial" placeholder="Amazonía Express"/><label class="rounded-2xl border border-slate-200 bg-slate-50 p-3 focus-within:ring-2 focus-within:ring-emerald-600"><span class="block text-[10px] font-bold uppercase text-slate-500">Modalidad</span><select name="modality" required class="mt-1 w-full border-0 bg-transparent p-0 text-sm font-bold focus:ring-0"><option value="fluvial" @selected(old('modality')==='fluvial')>Fluvial</option><option value="aereo" @selected(old('modality')==='aereo')>Aérea</option><option value="mixto" @selected(old('modality')==='mixto')>Mixta</option></select></label><x-company-field name="base_city" label="Ciudad base" placeholder="Iquitos" required/><x-company-field name="address" label="Dirección fiscal / base de operaciones" placeholder="Dirección principal" required/></div></fieldset>
<fieldset class="border-t border-slate-100 pt-7"><legend class="mb-4 text-sm font-black text-slate-900">2. Contacto responsable</legend><div class="grid gap-4 sm:grid-cols-2"><x-company-field name="contact_name" label="Nombres y apellidos" placeholder="Responsable legal" required/><x-company-field name="email" label="Correo corporativo" placeholder="administracion@empresa.pe" type="email" required/><x-company-field name="phone" label="Teléfono" placeholder="900 000 000" required/><x-company-field name="whatsapp" label="WhatsApp (opcional)" placeholder="900 000 000"/><x-company-field name="website" label="Sitio web (opcional)" placeholder="https://" type="url"/></div></fieldset>
<fieldset class="border-t border-slate-100 pt-7"><legend class="mb-1 text-sm font-black text-slate-900">3. Documentos para validación</legend><p class="mb-4 text-xs text-slate-500">Formatos PDF, JPG o PNG. Máximo 5 MB por archivo.</p><div class="grid gap-4 sm:grid-cols-3">@foreach([['ruc_document','Ficha RUC'],['representative_document','Documento del representante'],['operating_permit','Permiso de operación']] as [$name,$label])<label class="rounded-2xl border border-dashed border-slate-300 bg-slate-50 p-4 text-xs font-bold text-slate-700"><span class="mb-2 block">{{$label}} *</span><input type="file" name="{{$name}}" accept=".pdf,.jpg,.jpeg,.png" required class="block w-full text-xs file:mr-2 file:rounded-lg file:border-0 file:bg-emerald-100 file:px-3 file:py-2 file:font-bold file:text-emerald-900"></label>@endforeach</div></fieldset>
<div class="border-t border-slate-100 pt-7"><label class="flex items-start gap-3 text-sm text-slate-600"><input type="checkbox" name="terms" value="1" required class="mt-1 rounded border-slate-300 text-emerald-700 focus:ring-emerald-600"><span>Declaro que la información es correcta y autorizo su uso para validar la afiliación.</span></label><button class="mt-5 flex h-12 w-full items-center justify-center rounded-2xl bg-amber-500 text-sm font-black text-slate-950 shadow-sm transition hover:bg-amber-400">Enviar solicitud para revisión</button><p class="mt-3 text-center text-xs text-slate-500">No crearás una contraseña todavía. La configurarás cuando la solicitud sea aprobada.</p></div>
</form></section></div></div></main>
</x-public-layout>
