<x-app-layout>
<x-slot name="header"><h2 class="ny-page-title">{{ $title }}</h2></x-slot>
<div class="mx-auto max-w-7xl space-y-6 py-3">
@if($roles->contains('super_admin'))
<section class="overflow-hidden rounded-3xl bg-gradient-to-r from-[#062c21] via-emerald-950 to-slate-900 p-6 text-white shadow-xl sm:p-8">
 <div class="flex flex-col justify-between gap-5 lg:flex-row lg:items-center"><div><span class="rounded-full border border-emerald-500/30 bg-emerald-500/15 px-3 py-1 text-[10px] font-bold uppercase tracking-wider text-emerald-300">Panel comercial · Marketplace NavegaYA</span><h1 class="mt-3 text-2xl font-black tracking-tight sm:text-3xl">Centro de Control Comercial NavegaYA</h1><p class="mt-1 max-w-2xl text-sm text-emerald-100/75">Indicadores de ventas, comisiones y gestión de operadores afiliados en Loreto.</p></div><div class="flex flex-wrap gap-2"><a href="{{ route('admin.master-routes.index') }}" class="inline-flex h-11 items-center rounded-xl border border-white/20 px-4 text-xs font-bold">🧭 Catálogo de Rutas</a><a href="{{ route('admin.commissions.index') }}" class="inline-flex h-11 items-center rounded-xl bg-amber-500 px-5 text-xs font-black text-slate-950">Comisiones →</a></div></div>
</section>
<section class="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
 @foreach([['GMV Regional Hoy','S/ '.number_format($todayGmv??0,2),'Transacciones confirmadas','💰'],['Comisión Neta NavegaYA','S/ '.number_format($todayCommission??0,2),'Ingreso de plataforma','📈'],['Boletos Emitidos Hoy',number_format($todayTicketsTotal??0),($todayRiverTickets??0).' fluviales · '.($todayAirTickets??0).' aéreos','🎫'],['Operadores Activos',number_format($activeOperatorsToday??0),'Con salidas programadas hoy','🏢']] as [$label,$value,$note,$icon])
 <article class="rounded-2xl border border-slate-200/90 bg-white p-5 shadow-sm"><div class="flex items-center justify-between"><span class="text-[10px] font-bold uppercase tracking-wider text-slate-400">{{ $label }}</span><span class="text-xl">{{ $icon }}</span></div><strong class="mt-3 block text-2xl font-black {{ $label==='Comisión Neta NavegaYA'?'text-amber-600':'text-slate-900' }}">{{ $value }}</strong><span class="mt-1 block text-[11px] text-slate-500">{{ $note }}</span></article>
 @endforeach
</section>
<section class="grid gap-6 xl:grid-cols-12">
 <div class="space-y-6 xl:col-span-8">
  <section class="overflow-hidden rounded-3xl border border-slate-200/90 bg-white shadow-sm">
   <div class="flex items-center justify-between border-b border-slate-100 px-5 py-4"><div><span class="text-[10px] font-bold uppercase tracking-wider text-emerald-700">Operadores y agencias</span><h2 class="text-lg font-black text-slate-900">Solicitudes de afiliación</h2></div><a href="{{ route('admin.organizations.index') }}" class="text-xs font-bold text-emerald-800">Ver expediente completo →</a></div>
   <div class="overflow-x-auto"><table class="w-full min-w-[760px] text-left text-xs"><thead class="bg-slate-50 text-[10px] uppercase tracking-wider text-slate-400"><tr><th class="px-5 py-3">Empresa</th><th class="px-4 py-3">RUC</th><th class="px-4 py-3">Representante</th><th class="px-4 py-3">Ficha</th><th class="px-5 py-3 text-right">Decisión</th></tr></thead><tbody>
   @forelse($pendingApplications as $organization)<tr class="border-t border-slate-100"><td class="px-5 py-4"><strong class="text-slate-900">{{ $organization->commercial_name ?: $organization->legal_name }}</strong><span class="block text-[10px] text-slate-400">{{ $organization->email ?? 'Sin correo' }}</span></td><td class="px-4 py-4 font-bold text-slate-700">{{ $organization->ruc ?? 'Pendiente' }}</td><td class="px-4 py-4 text-slate-600">{{ $organization->contact_name ?? 'No registrado' }}</td><td class="px-4 py-4"><a href="{{ route('admin.organizations.index') }}" class="rounded-lg border border-slate-200 px-3 py-2 font-bold text-slate-700">Ver Ficha RUC</a></td><td class="px-5 py-4"><div class="flex justify-end gap-2"><form method="POST" action="{{ route('admin.organizations.reject',$organization) }}">@csrf @method('PATCH')<button class="rounded-lg border border-rose-200 px-3 py-2 font-bold text-rose-700">Rechazar</button></form><form method="POST" action="{{ route('admin.organizations.approve',$organization) }}">@csrf @method('PATCH')<button class="rounded-lg bg-emerald-700 px-3 py-2 font-bold text-white">Aprobar</button></form></div></td></tr>
   @empty<tr><td colspan="5" class="px-5 py-10 text-center text-slate-500">No hay solicitudes pendientes de validación.</td></tr>@endforelse
   </tbody></table></div>
  </section>
  <section class="overflow-hidden rounded-3xl border border-slate-200/90 bg-white shadow-sm">
   <div class="flex items-center justify-between border-b border-slate-100 px-5 py-4"><div><span class="text-[10px] font-bold uppercase tracking-wider text-emerald-700">Desempeño comercial</span><h2 class="text-lg font-black text-slate-900">Rendimiento de Operadores Afiliados</h2></div><a href="{{ route('admin.itineraries.index') }}" class="text-xs font-bold text-emerald-800">Ver itinerarios completos →</a></div>
   <div class="overflow-x-auto"><table class="w-full min-w-[820px] text-left text-xs"><thead class="bg-slate-50 text-[10px] uppercase tracking-wider text-slate-400"><tr><th class="px-5 py-3">Operador</th><th class="px-4 py-3">Modalidad</th><th class="px-4 py-3">Salidas hoy</th><th class="px-4 py-3">Ocupación</th><th class="px-4 py-3 text-right">GMV</th><th class="px-5 py-3 text-right">Auditoría</th></tr></thead><tbody>
   @forelse($operatorSummaries as $summary)@php($organization=$summary['organization'])<tr class="border-t border-slate-100"><td class="px-5 py-4"><strong class="text-slate-900">{{ $organization->commercial_name ?: $organization->legal_name }}</strong><span class="block text-[10px] text-slate-400">RUC {{ $organization->ruc ?? 'Sin registrar' }}</span></td><td class="px-4 py-4 font-semibold text-slate-600">{{ $summary['modality'] }}</td><td class="px-4 py-4 font-black text-slate-900">{{ $summary['departures'] }}</td><td class="px-4 py-4"><div class="flex items-center gap-2"><div class="h-2 w-24 overflow-hidden rounded-full bg-slate-100"><div class="h-full rounded-full bg-emerald-600" style="width:{{ $summary['occupancy'] }}%"></div></div><strong>{{ $summary['occupancy'] }}%</strong></div></td><td class="px-4 py-4 text-right font-black text-slate-900">S/ {{ number_format($summary['gross'],2) }}</td><td class="px-5 py-4 text-right"><a href="{{ route('admin.itineraries.index',['organization_id'=>$organization->id]) }}" class="rounded-lg bg-slate-100 px-3 py-2 font-bold text-slate-700">Ver itinerarios</a></td></tr>
   @empty<tr><td colspan="6" class="px-5 py-10 text-center text-slate-500">No hay operadores con salidas programadas hoy.</td></tr>@endforelse
   </tbody></table></div>
  </section>
 </div>
 <aside class="space-y-4 xl:col-span-4">
  <section class="rounded-3xl bg-[#062c21] p-5 text-white shadow-lg"><span class="text-[10px] font-bold uppercase tracking-wider text-emerald-300">DICAPI / DGAC</span><h2 class="mt-1 text-lg font-black">Monitoreo de terminales</h2><div class="mt-4 space-y-2">@foreach($portStatuses as $terminal)<div class="flex items-center justify-between gap-3 rounded-xl bg-white/5 px-3 py-2.5 text-xs"><span>📍 {{ $terminal['name'] }}</span><strong class="{{ $terminal['tone']==='emerald'?'text-emerald-300':($terminal['tone']==='rose'?'text-rose-300':'text-amber-300') }}">{{ $terminal['status'] }}</strong></div>@endforeach</div><p class="mt-4 text-[10px] leading-relaxed text-emerald-100/60">Información referencial. La autorización final de zarpe o vuelo corresponde a Capitanía, DGAC y al operador.</p></section>
  <section class="rounded-3xl border border-slate-200/90 bg-white p-5 shadow-sm"><span class="text-[10px] font-bold uppercase tracking-wider text-emerald-700">Catálogo regional</span><h3 class="mt-1 text-sm font-black text-slate-900">Control de geografía oficial</h3><p class="mt-2 text-xs leading-relaxed text-slate-500">Administra puertos y conexiones maestras para impedir rutas duplicadas o inválidas.</p><div class="mt-4 grid gap-2"><a href="{{ route('admin.master-routes.index') }}" class="rounded-xl bg-amber-500 px-4 py-3 text-center text-xs font-black text-slate-950">Gestionar Tramos Maestros</a><a href="{{ route('admin.ports.index') }}" class="rounded-xl border border-slate-200 px-4 py-3 text-center text-xs font-bold text-slate-700">Puertos y terminales</a></div></section>
 </aside>
</section>
@else
<section class="rounded-3xl bg-[#062c21] p-7 text-white shadow-xl"><span class="text-[10px] font-bold uppercase tracking-wider text-emerald-300">Mis viajes</span><h1 class="mt-2 text-3xl font-black">Hola, {{ auth()->user()->name }}</h1><p class="mt-2 text-sm text-emerald-100/75">Consulta tus reservas y boletos recientes.</p><a href="{{ route('routes.index') }}" class="mt-5 inline-flex rounded-xl bg-amber-500 px-5 py-3 text-xs font-black text-slate-950">Buscar una salida</a></section>
<section class="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><h2 class="text-lg font-black text-slate-900">Reservas recientes</h2>@forelse($travelerReservations as $reservation)<article class="mt-4 flex flex-wrap items-center justify-between gap-3 border-t border-slate-100 pt-4"><div><p class="font-bold text-slate-800">{{ $reservation->departure?->transportRoute?->originPort?->city ?? 'Origen' }} → {{ $reservation->departure?->transportRoute?->destinationPort?->city ?? 'Destino' }}</p><p class="text-xs text-slate-500">{{ $reservation->departure?->departure_at?->format('d/m/Y · H:i') }} · {{ ucfirst(str_replace('_',' ',$reservation->status)) }}</p></div><a href="{{ route('bookings.confirmation',$reservation->code) }}" class="rounded-lg bg-emerald-50 px-3 py-2 text-xs font-bold text-emerald-700">Ver reserva</a></article>@empty<p class="mt-3 text-sm text-slate-500">Aún no tienes reservas asociadas a esta cuenta.</p>@endforelse</section>
@endif
</div>
</x-app-layout>
