@php
 $siteBrand=\App\Models\SystemSetting::value('site_brand','NavegaYA'); $footerRights=\App\Models\SystemSetting::value('footer_rights','Todos los derechos reservados.');
 $heroImage=$slides->first()?->image_path ?: '/images/navegaya-hero-amazonas.png'; $activeTransport=$transport==='air'?'air':'river';
 $searchCities=collect($citiesForSearch)->merge(['Iquitos','Nauta','Yurimaguas','Santa Rosa'])->unique()->values();
 $cityLabels=['Iquitos'=>'Iquitos (Pto. Silico / Masusa)','Nauta'=>'Nauta (Embarcadero Principal)','Yurimaguas'=>'Yurimaguas (Puerto La Boca)','Santa Rosa'=>'Santa Rosa (Triple Frontera)'];
@endphp
<x-public-layout current="home" :title="$siteBrand.' · Viaja por río y aire'">
<x-slot:head><style>#resultados,footer>div{max-width:72rem!important}[hidden]{display:none!important}.ny-modal-open{display:grid!important}</style></x-slot:head>
<div class="min-h-screen w-full overflow-x-hidden bg-slate-50">
 <main class="mx-auto min-h-screen w-full max-w-7xl px-4 pb-16 pt-4 sm:px-6 lg:px-8">
  <x-amazon-hero-bg theme="home" class="min-h-[380px] w-full rounded-3xl text-center shadow-2xl" overlay="from-slate-950/90 via-[#062c21]/75 to-slate-900/45">
   <div class="flex w-full flex-col items-center pb-24 pt-8 sm:pb-28 sm:pt-12">
    <span class="rounded-full border border-emerald-500/30 bg-emerald-900/70 px-3.5 py-1 text-xs font-semibold uppercase tracking-widest text-emerald-300 backdrop-blur-sm">Pasajes fluviales y aéreos en Loreto</span>
    <h1 class="mt-4 max-w-3xl text-3xl font-bold leading-tight tracking-tight text-white md:text-5xl">Viaja por la Amazonía con total confianza</h1>
    <p class="mt-3 max-w-xl text-sm font-normal text-emerald-100/90 md:text-base">Compara rutas oficiales, consulta horarios y compra tus boletos con confirmación inmediata.</p>
   </div>
  </x-amazon-hero-bg>
  <button id="swapRoute" type="button" class="hidden" tabindex="-1" aria-hidden="true">Intercambiar origen y destino</button>

 <div id="buscar" class="relative z-20 mx-auto mt-6 max-w-5xl px-4">
  <div class="rounded-3xl border border-slate-100 bg-white p-5 shadow-xl md:p-6">
   <div class="mb-4 flex flex-wrap items-center justify-between gap-4 border-b border-slate-100 pb-3">
    <div class="inline-flex rounded-xl bg-slate-100 p-1" aria-label="Modalidad de transporte"><button type="button" data-transport-tab="river" class="flex items-center gap-1.5 rounded-lg px-3 py-1.5 text-xs font-semibold transition"><span>🚤</span> Fluvial</button><button type="button" data-transport-tab="air" class="flex items-center gap-1.5 rounded-lg px-3 py-1.5 text-xs font-medium transition"><span>✈️</span> Aéreo</button></div>
    <div class="flex items-center gap-1 rounded-xl border border-slate-200/60 bg-slate-50 p-1 text-xs"><button type="button" data-trip-type="one_way" class="rounded-lg px-3 py-1 font-semibold transition">Solo ida</button><button type="button" data-trip-type="round_trip" class="rounded-lg px-3 py-1 font-medium transition">Ida y vuelta</button></div>
   </div>
   <form id="homeSearchForm" action="{{route('home')}}#resultados" method="GET" class="grid grid-cols-1 items-center gap-1.5 rounded-2xl border border-slate-200 bg-slate-50 p-1.5 sm:grid-cols-2 lg:grid-cols-12">
    <input type="hidden" id="transportInput" name="transport" value="{{$activeTransport}}">
    <input type="hidden" id="tripTypeInput" name="trip_type" value="{{request('trip_type','one_way')}}">
    <div class="relative rounded-xl border border-slate-200/70 bg-white px-3 py-2 transition hover:border-slate-300 focus-within:ring-1 focus-within:ring-emerald-700 lg:col-span-3"><label for="origin" class="block text-[10px] font-semibold uppercase tracking-wider text-slate-400">Origen</label><div class="mt-0.5 flex items-center gap-1.5"><span class="flex h-4 w-4 shrink-0 items-center justify-center text-xs text-emerald-700">📍</span><select id="origin" name="origin" class="w-full cursor-pointer appearance-none border-0 bg-transparent py-0 pl-0 pr-4 text-xs font-semibold text-slate-800 outline-none focus:ring-0 sm:text-sm"><option value="">Selecciona origen</option>@foreach($searchCities as $city)<option value="{{$city}}" @selected(request('origin')===$city)>{{$cityLabels[$city]??$city}}</option>@endforeach</select><svg class="pointer-events-none absolute bottom-2.5 right-2.5 h-3 w-3 text-slate-400" fill="none" stroke="currentColor" viewBox="0 0 24 24" aria-hidden="true"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 9l-7 7-7-7"></path></svg></div></div>
    <div class="relative rounded-xl border border-slate-200/70 bg-white px-3 py-2 transition hover:border-slate-300 focus-within:ring-1 focus-within:ring-emerald-700 lg:col-span-3"><label for="destination" class="block text-[10px] font-semibold uppercase tracking-wider text-slate-400">Destino</label><div class="mt-0.5 flex items-center gap-1.5"><span class="flex h-4 w-4 shrink-0 items-center justify-center text-xs text-emerald-700">🎯</span><select id="destination" name="destination" class="w-full cursor-pointer appearance-none border-0 bg-transparent py-0 pl-0 pr-4 text-xs font-semibold text-slate-800 outline-none focus:ring-0 sm:text-sm"><option value="">Selecciona destino</option>@foreach($searchCities as $city)<option value="{{$city}}" @selected(request('destination')===$city)>{{$cityLabels[$city]??$city}}</option>@endforeach</select><svg class="pointer-events-none absolute bottom-2.5 right-2.5 h-3 w-3 text-slate-400" fill="none" stroke="currentColor" viewBox="0 0 24 24" aria-hidden="true"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 9l-7 7-7-7"></path></svg></div></div>
    <div class="rounded-xl border border-slate-200/70 bg-white px-3 py-2 transition hover:border-slate-300 focus-within:ring-1 focus-within:ring-emerald-700 lg:col-span-2"><label for="travel-date" class="block text-[10px] font-semibold uppercase tracking-wider text-slate-400">Fecha de salida</label><input id="travel-date" type="date" name="date" value="{{request('date',today()->toDateString())}}" min="{{today()->toDateString()}}" class="mt-0.5 w-full cursor-pointer border-0 bg-transparent p-0 text-xs font-semibold text-slate-800 outline-none focus:ring-0 sm:text-sm"></div>
    <div class="relative rounded-xl border border-slate-200/70 bg-white px-3 py-2 transition hover:border-slate-300 focus-within:ring-1 focus-within:ring-emerald-700 lg:col-span-2"><label for="passengers" class="block text-[10px] font-semibold uppercase tracking-wider text-slate-400">Pasajeros</label><div class="mt-0.5 flex items-center gap-1.5"><span class="flex h-4 w-4 shrink-0 items-center justify-center text-xs text-emerald-700">👤</span><select id="passengers" name="passengers" class="w-full cursor-pointer appearance-none border-0 bg-transparent p-0 pr-4 text-xs font-semibold text-slate-800 outline-none focus:ring-0 sm:text-sm">@foreach([1,2,3,4] as $count)<option value="{{$count}}" @selected((int)request('passengers',1)===$count)>{{$count}} {{$count===1?'adulto':'adultos'}}</option>@endforeach</select><svg class="pointer-events-none absolute bottom-2.5 right-2.5 h-3 w-3 text-slate-400" fill="none" stroke="currentColor" viewBox="0 0 24 24" aria-hidden="true"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 9l-7 7-7-7"></path></svg></div></div>
    <div class="p-1 lg:col-span-2"><button type="submit" class="flex h-10 w-full items-center justify-center gap-2 rounded-xl bg-amber-500 px-3 text-xs font-semibold text-slate-950 shadow-sm transition hover:bg-amber-600 active:scale-95 sm:text-sm"><svg class="h-3.5 w-3.5" fill="none" stroke="currentColor" stroke-width="2.5" viewBox="0 0 24 24" aria-hidden="true"><path stroke-linecap="round" stroke-linejoin="round" d="M21 21l-4.35-4.35m0 0A7.5 7.5 0 1 0 10.5 18a7.5 7.5 0 0 0 6.15-3.35z"></path></svg>Buscar pasajes</button></div>
   </form>
   <div class="mt-3 flex flex-wrap items-center gap-2 text-xs text-slate-500"><span class="font-medium text-slate-400">Rutas rápidas:</span><a href="{{route('home',['transport'=>'river','origin'=>'Iquitos','destination'=>'Nauta'])}}#resultados" class="rounded-md bg-slate-100 px-2.5 py-0.5 transition hover:bg-emerald-50 hover:text-emerald-700">Iquitos ➔ Nauta</a><a href="{{route('home',['transport'=>'river','origin'=>'Nauta','destination'=>'Yurimaguas'])}}#resultados" class="rounded-md bg-slate-100 px-2.5 py-0.5 transition hover:bg-emerald-50 hover:text-emerald-700">Nauta ➔ Yurimaguas</a><a href="{{route('home',['transport'=>'river','origin'=>'Iquitos','destination'=>'Santa Rosa'])}}#resultados" class="rounded-md bg-slate-100 px-2.5 py-0.5 transition hover:bg-emerald-50 hover:text-emerald-700">Iquitos ➔ Santa Rosa</a></div>
  </div>
 </div>

 <script>document.addEventListener('DOMContentLoaded',()=>{const input=document.getElementById('tripTypeInput'),buttons=[...document.querySelectorAll('[data-trip-type]')];if(!input)return;const select=value=>{input.value=value;buttons.forEach(button=>{const active=button.dataset.tripType===value;button.classList.toggle('bg-emerald-800',active);button.classList.toggle('text-white',active);button.classList.toggle('shadow-sm',active);button.classList.toggle('text-slate-600',!active);button.classList.toggle('hover:text-slate-900',!active)})};buttons.forEach(button=>button.addEventListener('click',()=>select(button.dataset.tripType)));select(input.value)});</script>

 @if(false)
 <div id="resultados-anterior" class="mx-auto max-w-7xl px-4 sm:px-6">@if($hasSearch)<div class="mt-8 flex flex-col gap-3 rounded-2xl border border-emerald-100 bg-emerald-50 px-5 py-4 sm:flex-row sm:items-center sm:justify-between"><div><strong class="block text-sm text-emerald-950">Resultados de tu búsqueda</strong><span class="text-sm text-emerald-700">{{request('origin')?:'Cualquier origen'}} → {{request('destination')?:'Cualquier destino'}}{{request('date')?' · '.\Carbon\Carbon::parse(request('date'))->format('d/m/Y'):''}} · {{request('passengers',1)}} pasajero(s)</span></div><a href="{{route('home')}}#buscar" class="text-sm font-extrabold text-emerald-800">Limpiar filtros</a></div>@endif
 <section class="py-16"><div class="mb-7 flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p class="text-xs font-black uppercase tracking-[.2em] text-emerald-700">Disponibilidad actualizada</p><h2 class="mt-2 text-3xl font-bold text-emerald-950 sm:text-4xl">Próximas salidas</h2></div><a href="{{route('routes.index',['transport'=>$activeTransport])}}" class="text-sm font-extrabold text-emerald-700">Ver todos los horarios →</a></div>
 <div id="riverResults" class="grid gap-5 md:grid-cols-2 xl:grid-cols-3">@forelse($departures as $departure)@php($route=$departure->transportRoute)@php($available=max(0,($departure->vessel->seat_capacity??0)-$departure->reservations->sum(fn($r)=>$r->seats->count())))<article class="rounded-2xl border border-slate-100 bg-white p-5 shadow-sm transition hover:-translate-y-0.5 hover:shadow-md"><header class="flex items-start justify-between gap-4"><div><span class="inline-flex rounded-full bg-emerald-50 px-2.5 py-1 text-[11px] font-medium text-emerald-700">{{$departure->cargo_enabled?'Ferry · Carga':'Rápida'}}</span><h3 class="mt-3 text-sm font-semibold text-slate-800">{{$departure->vessel->organization->commercial_name?:$departure->vessel->organization->legal_name}}</h3><p class="mt-1 text-xs text-slate-500">{{$departure->vessel->name}}</p></div><div class="text-right"><span class="block text-[11px] uppercase tracking-wider text-slate-400">Salida</span><strong class="mt-1 block text-xl font-semibold text-slate-900">{{$departure->departure_at->format('H:i')}}</strong></div></header><div class="my-5 border-y border-dashed border-slate-200 py-4"><p class="text-sm font-medium text-slate-700">{{$route->originPort->city}} <span class="mx-1 text-emerald-600">➔</span> {{$route->destinationPort->city}}</p><p class="mt-2 text-xs text-slate-500">📍 {{$route->originPort->name}} · {{$departure->departure_at->translatedFormat('D d M')}}</p></div></article>@empty<div class="col-span-full rounded-2xl border border-dashed border-slate-300 bg-white p-10 text-center text-sm text-slate-500">No hay salidas fluviales con esos criterios.</div>@endforelse</div>
 <div id="airResults" class="grid gap-5 md:grid-cols-2 xl:grid-cols-3">@forelse($airDepartures as $air)@php($route=$air->airRoute)@php($available=max(0,($air->aircraft->seat_capacity??0)-$air->reservations->sum(fn($r)=>$r->seats->count())))<article class="rounded-2xl border border-slate-100 bg-white p-5 shadow-sm transition hover:-translate-y-0.5 hover:shadow-md"><header class="flex items-start justify-between gap-4"><div><span class="inline-flex rounded-full bg-sky-50 px-2.5 py-1 text-[11px] font-medium text-sky-700">Vuelo regional</span><h3 class="mt-3 text-sm font-semibold text-slate-800">{{$air->aircraft->organization->commercial_name?:$air->aircraft->organization->legal_name}}</h3><p class="mt-1 text-xs text-slate-500">{{$air->aircraft->name}}</p></div><div class="text-right"><span class="block text-[11px] uppercase tracking-wider text-slate-400">Salida</span><strong class="mt-1 block text-xl font-semibold text-slate-900">{{$air->departure_at->format('H:i')}}</strong></div></header><div class="my-5 border-y border-dashed border-slate-200 py-4"><p class="text-sm font-medium text-slate-700">{{$route->origin_city}} <span class="mx-1 text-sky-600">➔</span> {{$route->destination_city}}</p><p class="mt-2 text-xs text-slate-500">📍 Terminal aéreo · {{$air->departure_at->translatedFormat('D d M')}}</p></div></article>@empty<div class="col-span-full rounded-2xl border border-dashed border-slate-300 bg-white p-10 text-center text-sm text-slate-500">No hay vuelos con esos criterios.</div>@endforelse</div></section>

 <section class="pb-16" aria-label="Publicidad">@if($ads->isNotEmpty())<x-ad-placement :ads="$ads" compact />@else<a href="{{route('advertising.create')}}" class="flex min-h-[110px] items-center justify-between gap-6 rounded-2xl border border-dashed border-emerald-300 bg-emerald-50 px-6 py-5"><div><span class="text-[9px] font-black uppercase tracking-[.18em] text-emerald-600">Espacio publicitario · 728 × 90</span><h3 class="mt-2 text-lg font-black text-emerald-950">Promociona tu hotel, agencia o experiencia amazónica</h3></div><span class="rounded-xl bg-emerald-900 px-4 py-2 text-xs font-black text-white">Anunciar aquí</span></a>@endif</section>
 <section class="grid gap-5 pb-20 md:grid-cols-3"><article class="rounded-2xl border border-slate-100 bg-white p-6"><span class="flex h-10 w-10 items-center justify-center rounded-xl bg-emerald-50 text-emerald-700">✓</span><h3 class="mt-4 text-base font-semibold text-slate-900">Empresas verificadas</h3><p class="mt-2 text-xs leading-relaxed text-slate-500">Operadores identificados y salidas administradas por cada empresa.</p></article><article class="rounded-2xl border border-slate-100 bg-white p-6"><span class="flex h-10 w-10 items-center justify-center rounded-xl bg-emerald-50 text-emerald-700">▣</span><h3 class="mt-4 text-base font-semibold text-slate-900">Boletos con QR</h3><p class="mt-2 text-xs leading-relaxed text-slate-500">Un boleto único por pasajero listo para el embarque.</p></article><article class="rounded-2xl border border-slate-100 bg-white p-6"><span class="flex h-10 w-10 items-center justify-center rounded-xl bg-emerald-50 text-emerald-700">◈</span><h3 class="mt-4 text-base font-semibold text-slate-900">Una sola compra</h3><p class="mt-2 text-xs leading-relaxed text-slate-500">Combina pasajes fluviales y aéreos en el mismo carrito.</p></article></section></div>
 @endif

 <div id="resultados" class="mx-auto mb-16 mt-12 max-w-7xl px-4 sm:px-6 lg:px-8">
  @if($hasSearch)<div class="mt-8 flex flex-col gap-3 rounded-2xl border border-emerald-100 bg-emerald-50 px-5 py-4 sm:flex-row sm:items-center sm:justify-between"><div><strong class="block text-sm text-emerald-950">Resultados de tu búsqueda</strong><span class="text-sm text-emerald-700">{{request('origin')?:'Cualquier origen'}} → {{request('destination')?:'Cualquier destino'}}{{request('date')?' · '.\Carbon\Carbon::parse(request('date'))->format('d/m/Y'):''}} · {{request('passengers',1)}} pasajero(s)</span></div><a href="{{route('home')}}#buscar" class="text-sm font-semibold text-emerald-800">Limpiar filtros</a></div>@endif
  <section class="mt-14">
   <div class="mb-6 flex flex-col justify-between gap-2 border-b border-slate-200/60 pb-2 sm:flex-row sm:items-end"><div><span class="text-xs font-semibold uppercase tracking-wider text-emerald-700">Disponibilidad en tiempo real</span><h2 class="text-2xl font-bold tracking-tight text-slate-900">Próximas salidas verificadas</h2></div><a href="{{route('routes.index',['transport'=>$activeTransport])}}" class="flex items-center gap-1 text-sm font-semibold text-emerald-700 transition hover:text-emerald-800">Ver todos los horarios y rutas <svg class="h-4 w-4" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24" aria-hidden="true"><path stroke-linecap="round" stroke-linejoin="round" d="m9 5 7 7-7 7"></path></svg></a></div>

   <div id="riverResults" class="grid grid-cols-1 gap-5 md:grid-cols-2 lg:grid-cols-3">@forelse($departures->take(6) as $departure)@php($route=$departure->transportRoute)@php($available=max(0,($departure->vessel->seat_capacity??0)-$departure->reservations->sum(fn($r)=>$r->seats->count())))<article class="flex flex-col justify-between rounded-2xl border border-slate-200/80 bg-white p-4 shadow-sm transition-all hover:border-emerald-400 hover:shadow-md"><div><header class="flex items-center justify-between gap-2"><span class="rounded-full border border-emerald-200 bg-emerald-50 px-2.5 py-0.5 text-xs font-semibold text-emerald-800">{{$departure->cargo_enabled?'⛴️ Ferry':'🚤 Rápida'}}</span><span class="rounded-md bg-emerald-50/80 px-2 py-0.5 text-xs font-semibold text-emerald-700">{{$available}} asientos</span></header><h3 class="mt-2 flex items-center gap-2 text-base font-bold text-slate-900">{{$route->originPort->city}} ➔ {{$route->destinationPort->city}}</h3><p class="mt-1"><strong class="text-sm font-extrabold text-emerald-900">{{$departure->departure_at->format('H:i')}}</strong><span class="text-xs text-slate-500"> · {{$route->originPort->name}}</span></p><p class="mt-1 text-xs text-slate-500">{{$departure->vessel->organization->commercial_name?:$departure->vessel->organization->legal_name}} · {{$departure->vessel->name}}</p></div></article>@empty<div class="col-span-full rounded-2xl border border-dashed border-slate-300 bg-white p-10 text-center text-sm text-slate-500">No hay salidas fluviales con esos criterios.</div>@endforelse</div>

   <div id="airResults" class="grid grid-cols-1 gap-5 md:grid-cols-2 lg:grid-cols-3">@forelse($airDepartures->take(6) as $air)@php($route=$air->airRoute)@php($available=max(0,($air->aircraft->seat_capacity??0)-$air->reservations->sum(fn($r)=>$r->seats->count())))<article class="flex flex-col justify-between rounded-2xl border border-slate-200/80 bg-white p-4 shadow-sm transition-all hover:border-sky-400 hover:shadow-md"><div><header class="flex items-center justify-between gap-2"><span class="rounded-full border border-sky-200 bg-sky-50 px-2.5 py-0.5 text-xs font-semibold text-sky-800">✈️ Vuelo regional</span><span class="rounded-md bg-emerald-50/80 px-2 py-0.5 text-xs font-semibold text-emerald-700">{{$available}} asientos</span></header><h3 class="mt-2 flex items-center gap-2 text-base font-bold text-slate-900">{{$route->origin_city}} ➔ {{$route->destination_city}}</h3><p class="mt-1"><strong class="text-sm font-extrabold text-sky-900">{{$air->departure_at->format('H:i')}}</strong><span class="text-xs text-slate-500"> · Aeropuerto / terminal aéreo</span></p><p class="mt-1 text-xs text-slate-500">{{$air->aircraft->organization->commercial_name?:$air->aircraft->organization->legal_name}} · {{$air->aircraft->name}}</p></div></article>@empty<div class="col-span-full rounded-2xl border border-dashed border-slate-300 bg-white p-10 text-center text-sm text-slate-500">No hay vuelos con esos criterios.</div>@endforelse</div>
  </section>

  <section class="my-14">@if($ads->isNotEmpty())<x-b2b-ad-banner placement="home_hero" class="my-0" />@else<div class="relative flex flex-col items-center justify-between gap-6 overflow-hidden rounded-2xl border border-emerald-200/70 bg-gradient-to-r from-emerald-50 via-teal-50 to-emerald-50 p-6 shadow-sm sm:p-8 md:flex-row"><div class="relative z-10 max-w-xl"><span class="mb-2 inline-block rounded-full border border-emerald-200 bg-white px-2.5 py-0.5 text-[10px] font-bold uppercase tracking-widest text-emerald-800">Espacio publicitario</span><h3 class="text-lg font-bold text-slate-900 sm:text-xl">Promociona tu lodge, hotel o agencia de turismo</h3><p class="mt-1 text-xs text-slate-600 sm:text-sm">Llega a pasajeros que viajan por río y aire en toda la cuenca de Loreto.</p></div><a href="{{ route('advertising.create') }}" class="relative z-10 inline-flex shrink-0 items-center gap-2 rounded-xl bg-emerald-800 px-5 py-2.5 text-xs font-semibold text-white shadow-sm transition hover:bg-emerald-900 sm:text-sm">Conocer planes y tarifas <span aria-hidden="true">→</span></a></div>@endif</section>

  <section class="mb-10"><div class="grid grid-cols-1 gap-6 md:grid-cols-3"><article class="flex items-start gap-4 rounded-2xl border border-slate-200/80 bg-white p-6"><div class="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-emerald-50 font-bold text-emerald-700">✓</div><div><h3 class="text-sm font-bold text-slate-900">Operadores verificados</h3><p class="mt-1 text-xs leading-relaxed text-slate-500">Embarcaciones y aerotaxis autorizados con salidas confirmadas y registro oficial de viaje.</p></div></article><article class="flex items-start gap-4 rounded-2xl border border-slate-200/80 bg-white p-6"><div class="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-emerald-50 font-bold text-emerald-700">📱</div><div><h3 class="text-sm font-bold text-slate-900">Boleto digital con QR</h3><p class="mt-1 text-xs leading-relaxed text-slate-500">Recibe tu boleto por medios digitales y preséntalo directamente desde tu celular al embarcar.</p></div></article><article class="flex items-start gap-4 rounded-2xl border border-slate-200/80 bg-white p-6"><div class="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-emerald-50 font-bold text-emerald-700">💳</div><div><h3 class="text-sm font-bold text-slate-900">Pagos 100% seguros</h3><p class="mt-1 text-xs leading-relaxed text-slate-500">Paga con Yape, Plin o tarjetas de débito y crédito mediante una operación protegida.</p></div></article></div></section>
 </div>
</main>
</div>

<div id="consulta-pasaje" class="fixed inset-0 z-[10000] hidden place-items-center bg-emerald-950/70 p-4 backdrop-blur-sm" aria-hidden="true"><section class="relative w-full max-w-2xl rounded-2xl bg-white p-6 shadow-2xl"><button class="ticket-modal-close absolute right-4 top-4 h-9 w-9 rounded-full bg-slate-100 text-xl">×</button><p class="text-xs font-black uppercase tracking-[.18em] text-emerald-700">Consulta rápida</p><h2 class="mt-2 text-2xl font-black text-emerald-950">Busca tu pasaje</h2><p class="mt-2 text-sm text-slate-500">Ingresa el DNI y el código de reserva o boleto.</p><form id="ticketLookupForm" class="mt-5 grid gap-3 sm:grid-cols-[1fr_1fr_auto]"><input id="ticketLookupDocument" required placeholder="DNI o documento" class="rounded-xl border-slate-200"><input id="ticketLookupReference" required placeholder="Reserva RES-... o boleto BOL-..." class="rounded-xl border-slate-200"><button class="rounded-xl bg-amber-400 px-5 py-3 text-sm font-black">Buscar</button></form><div id="ticketLookupResult" class="mt-5"></div></section></div>



<script>document.addEventListener('DOMContentLoaded',()=>{const input=document.getElementById('transportInput'),river=document.getElementById('riverResults'),air=document.getElementById('airResults'),tabs=[...document.querySelectorAll('[data-transport-tab]')],show=type=>{input.value=type;river.classList.toggle('hidden',type==='air');air.classList.toggle('hidden',type==='river');tabs.forEach(t=>{const on=t.dataset.transportTab===type;t.classList.toggle('bg-white',on);t.classList.toggle('shadow-sm',on);t.classList.toggle('text-slate-500',!on);t.classList.toggle('text-emerald-800',on&&type==='river');t.classList.toggle('text-sky-800',on&&type==='air')})};tabs.forEach(t=>t.onclick=()=>show(t.dataset.transportTab));show(input.value);document.getElementById('swapRoute').onclick=()=>{const a=document.getElementById('origin'),b=document.getElementById('destination'),v=a.value;a.value=b.value;b.value=v};const modal=document.getElementById('consulta-pasaje'),close=document.querySelector('.ticket-modal-close'),result=document.getElementById('ticketLookupResult'),form=document.getElementById('ticketLookupForm');document.querySelectorAll('[data-ticket-modal]').forEach(b=>b.onclick=()=>{modal.classList.add('ny-modal-open');modal.setAttribute('aria-hidden','false')});close.onclick=()=>{modal.classList.remove('ny-modal-open');modal.setAttribute('aria-hidden','true')};modal.onclick=e=>{if(e.target===modal)close.click()};form.onsubmit=async e=>{e.preventDefault();result.textContent='Buscando pasaje…';try{const response=await fetch('{{route('travels.lookup')}}',{method:'POST',headers:{'Content-Type':'application/json','Accept':'application/json','X-CSRF-TOKEN':'{{csrf_token()}}'},body:JSON.stringify({document:document.getElementById('ticketLookupDocument').value.trim(),reference:document.getElementById('ticketLookupReference').value.trim()})}),data=await response.json();if(!response.ok)throw Error(data.message||'No se pudo consultar.');result.innerHTML=data.tickets.length?data.tickets.map(t=>`<article class="mt-3 grid grid-cols-[1fr_auto] gap-4 rounded-xl border p-4"><div><strong>${t.passenger}</strong><br><small>${t.route}</small><br><small>${t.departure} · ${t.vessel} · Asiento ${t.seat}</small></div><div><img class="h-20 w-20" src="${t.qr_url}"><a class="block text-xs font-bold text-emerald-700" href="${t.pdf_url}" target="_blank">Descargar PDF</a></div></article>`).join(''):'<p class="rounded-xl bg-amber-50 p-4 text-sm">No encontramos el boleto.</p>'}catch(error){result.innerHTML='<p class="rounded-xl bg-red-50 p-4 text-sm text-red-700">'+error.message+'</p>'}}});</script>
</x-public-layout>


