<x-app-layout>
    <x-slot name="header"><h2 class="ny-page-title">Publicidad y campañas</h2></x-slot>
    <div class="mx-auto max-w-6xl space-y-6">
        @if(session('success'))<p class="rounded-xl bg-emerald-50 p-4 text-emerald-800">{{session('success')}}</p>@endif
        @if($errors->any())<div class="rounded-xl bg-rose-50 p-4 text-rose-800"><strong>Revisa estos datos:</strong><ul class="mt-2 list-disc pl-5">@foreach($errors->all() as $error)<li>{{$error}}</li>@endforeach</ul></div>@endif
        <section style="border-radius:20px;padding:30px;background:linear-gradient(110deg,#103d35,#1d705e);color:white">
            <p style="margin:0;color:#f2c348;font-size:12px;font-weight:800;letter-spacing:.12em;text-transform:uppercase">Ingresos publicitarios</p><h1 style="margin:8px 0;font-size:28px">Crear campaña</h1><p style="max-width:700px;margin:0 0 24px;color:#d9ece6">Registra el anuncio de un negocio. Se enviará como pendiente para que el administrador principal lo revise antes de mostrarlo a los viajeros.</p>
            <form method="POST" action="{{route('admin.ads.store')}}" style="display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:16px">@csrf
                <label style="font-weight:700">Destino donde aparecerá la campaña<select required name="destination_city_id" style="display:block;width:100%;margin-top:7px;border:1px solid #c9ddd6;border-radius:9px;padding:12px;background:#fff;color:#173b33"><option value="">Selecciona una ciudad</option>@foreach($cities as $city)<option value="{{$city->id}}" @selected(old('destination_city_id')==$city->id)>{{$city->name}}</option>@endforeach</select></label>
                <label style="font-weight:700">Nombre del negocio<input required name="business_name" value="{{old('business_name')}}" placeholder="Ej. Hotel Río Verde" style="display:block;width:100%;margin-top:7px;border:1px solid #c9ddd6;border-radius:9px;padding:12px;color:#173b33"></label>
                <label style="font-weight:700">Categoría<input required name="category" value="{{old('category')}}" placeholder="Hotel, restaurante, agencia o tour" style="display:block;width:100%;margin-top:7px;border:1px solid #c9ddd6;border-radius:9px;padding:12px;color:#173b33"></label>
                <label style="font-weight:700">Título que verá el viajero<input required name="title" value="{{old('title')}}" placeholder="Ej. Hospédate frente al río" style="display:block;width:100%;margin-top:7px;border:1px solid #c9ddd6;border-radius:9px;padding:12px;color:#173b33"></label>
                <label style="font-weight:700">Enlace de contacto o sitio web<input name="target_url" value="{{old('target_url')}}" placeholder="https://... o https://wa.me/..." style="display:block;width:100%;margin-top:7px;border:1px solid #c9ddd6;border-radius:9px;padding:12px;color:#173b33"><span style="display:block;margin-top:5px;color:#cfe4dc;font-size:12px;font-weight:400">Al hacer clic, el viajero será enviado a este enlace.</span></label>
                <label style="font-weight:700">URL de imagen (opcional)<input name="image_url" value="{{old('image_url')}}" placeholder="https://ejemplo.com/imagen.jpg" style="display:block;width:100%;margin-top:7px;border:1px solid #c9ddd6;border-radius:9px;padding:12px;color:#173b33"><span style="display:block;margin-top:5px;color:#cfe4dc;font-size:12px;font-weight:400">Luego podremos habilitar carga directa de imágenes.</span></label>
                <label style="font-weight:700">Inicio de campaña<input type="date" name="starts_on" value="{{old('starts_on')}}" style="display:block;width:100%;margin-top:7px;border:1px solid #c9ddd6;border-radius:9px;padding:12px;color:#173b33"></label>
                <label style="font-weight:700">Fin de campaña<input type="date" name="ends_on" value="{{old('ends_on')}}" style="display:block;width:100%;margin-top:7px;border:1px solid #c9ddd6;border-radius:9px;padding:12px;color:#173b33"></label>
                <label style="grid-column:1/-1;font-weight:700">Descripción<textarea name="description" rows="4" placeholder="Describe la oferta, servicio o promoción" style="display:block;width:100%;margin-top:7px;border:1px solid #c9ddd6;border-radius:9px;padding:12px;color:#173b33">{{old('description')}}</textarea></label>
                <div style="grid-column:1/-1;display:flex;align-items:center;justify-content:space-between;gap:16px;border-top:1px solid #ffffff30;padding-top:18px"><small style="color:#d9ece6">Estado inicial: <strong>Pendiente de aprobación</strong>.</small><button style="border:0;border-radius:9px;padding:13px 20px;background:#f2c348;color:#12372d;font-size:15px;font-weight:800;cursor:pointer">Enviar para aprobación</button></div>
            </form>
        </section>
        <section><div style="display:flex;align-items:end;justify-content:space-between;gap:16px;margin-bottom:15px"><div><p style="margin:0;color:#0d6b5e;font-size:12px;font-weight:800;letter-spacing:.12em">SEGUIMIENTO</p><h2 style="margin:5px 0;font-size:24px">Campañas registradas</h2></div><p style="margin:0;color:#64748b;font-size:13px">Vistas: aperturas en Descubrir · Clics: visitas al enlace del negocio.</p></div><div style="display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:16px">@forelse($ads as $ad)<article style="overflow:hidden;border:1px solid #dbe6e1;border-radius:16px;background:#fff">@if($ad->image_url)<img src="{{$ad->image_url}}" alt="" style="display:block;width:100%;height:150px;object-fit:cover">@endif<div style="padding:20px"><div style="display:flex;justify-content:space-between;gap:10px"><h3 style="margin:0">{{$ad->business_name}}</h3><span style="border-radius:20px;padding:5px 9px;background:{{ $ad->status==='active'?'#dff6e9':($ad->status==='paused'?'#eef1f3':'#fff1c9') }};font-size:12px;font-weight:800">{{ $ad->status==='active'?'Publicada':($ad->status==='paused'?'Pausada':'Pendiente') }}</span></div><p style="margin:7px 0;color:#60736c;font-size:13px">{{$ad->city->name}} · {{$ad->category}}</p><strong>{{$ad->title}}</strong><p style="margin:10px 0;color:#50645d;font-size:14px">{{$ad->description ?: 'Sin descripción.'}}</p><p style="margin:12px 0 0;color:#71847d;font-size:12px">Vistas: {{$ad->views}} · Clics: {{$ad->clicks}} · {{ $ad->starts_on?->format('d/m/Y') ?: 'Sin fecha de inicio' }} — {{ $ad->ends_on?->format('d/m/Y') ?: 'Sin fecha de fin' }}</p>@if(auth()->user()->roles()->where('code','super_admin')->exists())<div style="display:flex;gap:8px;margin-top:16px">@if($ad->status==='pending')<form method="POST" action="{{route('admin.ads.approve',$ad)}}">@csrf @method('PATCH')<button style="border:0;border-radius:8px;padding:9px 13px;background:#0d6b5e;color:#fff;font-weight:800;cursor:pointer">Aprobar y publicar</button></form>@elseif($ad->status==='active')<form method="POST" action="{{route('admin.ads.pause',$ad)}}">@csrf @method('PATCH')<button style="border:1px solid #d6ddd9;border-radius:8px;padding:9px 13px;background:#fff;font-weight:800;cursor:pointer">Pausar</button></form>@else<form method="POST" action="{{route('admin.ads.resume',$ad)}}">@csrf @method('PATCH')<button style="border:0;border-radius:8px;padding:9px 13px;background:#0d6b5e;color:#fff;font-weight:800;cursor:pointer">Reactivar</button></form>@endif</div>@endif</div></article>@empty<p style="grid-column:1/-1;border-radius:14px;background:#fff;padding:28px;color:#64748b">Aún no hay campañas registradas.</p>@endforelse</div></section>
    </div>
</x-app-layout>
