@extends('layouts.admin')
@section('content')
<div class="space-y-5">
<section class="flex flex-col gap-4 rounded-2xl bg-gradient-to-r from-emerald-950 to-slate-900 p-6 text-white md:flex-row md:items-center md:justify-between"><div><p class="text-[10px] font-bold uppercase tracking-[.18em] text-amber-300">Pipeline comercial B2B</p><h1 class="mt-1 text-2xl font-black">Publicidad y pautas B2B</h1><p class="mt-1 text-xs text-emerald-100/70">Capta, modera y distribuye campañas en los puntos de venta de NavegaYA.</p></div><a href="{{ route('advertising.create') }}" target="_blank" class="rounded-xl bg-amber-400 px-4 py-2.5 text-xs font-black text-slate-950">Ver landing pública ↗</a></section>
@if(session('success'))<div class="rounded-xl bg-emerald-50 p-3 text-xs font-bold text-emerald-800">{{ session('success') }}</div>@endif
<section class="grid grid-cols-2 gap-3 lg:grid-cols-4">@foreach(['lead_pending'=>'Leads pendientes','active'=>'Campañas activas','paused'=>'Pausadas','expired'=>'Vencidas'] as $key=>$label)<a href="{{ route('admin.advertisements.index',['status'=>$key]) }}" class="rounded-xl border border-slate-200 bg-white p-4 shadow-sm"><span class="text-[10px] font-bold uppercase text-slate-400">{{ $label }}</span><strong class="mt-1 block text-2xl text-slate-900">{{ $pipeline[$key] ?? 0 }}</strong></a>@endforeach</section>
<form method="GET" class="flex flex-wrap gap-2 rounded-xl border border-slate-200 bg-white p-3"><input name="search" value="{{ request('search') }}" placeholder="Negocio, contacto o WhatsApp" class="min-w-60 flex-1 rounded-lg border-slate-200 text-xs"><select name="status" class="rounded-lg border-slate-200 text-xs"><option value="">Todos los estados</option>@foreach(['lead_pending'=>'Pendiente','active'=>'Activa','paused'=>'Pausada','expired'=>'Vencida'] as $value=>$label)<option value="{{ $value }}" @selected(request('status')===$value)>{{ $label }}</option>@endforeach</select><button class="rounded-lg bg-[#062c21] px-4 text-xs font-bold text-white">Filtrar</button></form>
<section class="space-y-3">@forelse($ads as $ad)<article x-data="{edit:false}" class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div class="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between"><div class="flex gap-4">@if($ad->creative_url)<img src="{{ $ad->creative_url }}" class="h-20 w-28 rounded-xl object-cover" alt="">@endif<div><div class="flex flex-wrap items-center gap-2"><h2 class="text-sm font-black text-slate-900">{{ $ad->business_name }}</h2><span class="rounded-full px-2 py-1 text-[9px] font-bold {{ $ad->status==='active'?'bg-emerald-50 text-emerald-700':($ad->status==='lead_pending'?'bg-amber-50 text-amber-700':'bg-slate-100 text-slate-600') }}">{{ strtoupper(str_replace('_',' ',$ad->status)) }}</span></div><p class="mt-1 text-[11px] text-slate-500">{{ $businessTypes[$ad->business_type] ?? $ad->category }} · {{ $ad->city_destination }} · {{ $ad->contact_name ?: 'Sin contacto' }} · {{ $ad->phone_whatsapp }}</p><p class="mt-2 text-[10px] text-slate-400">Ubicaciones: {{ collect($ad->placements)->map(fn($p)=>$placements[$p]??$p)->join(' · ') ?: 'Sin asignar' }} · S/ {{ number_format((float)$ad->monthly_fee,2) }}/mes · {{ $ad->views }} vistas · {{ $ad->clicks }} clics</p></div></div><div class="flex gap-2"><button type="button" @click="edit=!edit" class="rounded-lg border border-slate-200 px-3 py-2 text-[10px] font-bold">Editar</button>@if($ad->status==='lead_pending')<form method="POST" action="{{ route('admin.advertisements.approve',$ad) }}">@csrf @method('PATCH')<button class="rounded-lg bg-emerald-700 px-3 py-2 text-[10px] font-bold text-white">Aprobar</button></form>@elseif($ad->status==='active')<form method="POST" action="{{ route('admin.advertisements.pause',$ad) }}">@csrf @method('PATCH')<button class="rounded-lg bg-slate-100 px-3 py-2 text-[10px] font-bold">Pausar</button></form>@else<form method="POST" action="{{ route('admin.advertisements.resume',$ad) }}">@csrf @method('PATCH')<button class="rounded-lg bg-emerald-700 px-3 py-2 text-[10px] font-bold text-white">Reactivar</button></form>@endif</div></div>
<form x-show="edit" x-cloak method="POST" action="{{ route('admin.advertisements.update',$ad) }}" class="mt-5 grid gap-3 border-t border-slate-100 pt-5 md:grid-cols-3">@csrf @method('PATCH')
<input type="hidden" name="business_name" value="{{ $ad->business_name }}"><input type="hidden" name="business_type" value="{{ $ad->business_type ?: 'lodge_hotel' }}"><input type="hidden" name="contact_name" value="{{ $ad->contact_name ?: $ad->business_name }}"><input type="hidden" name="phone_whatsapp" value="{{ $ad->phone_whatsapp ?: 'Sin registrar' }}"><input type="hidden" name="city_destination" value="{{ $ad->city_destination ?: 'Iquitos' }}"><input type="hidden" name="title" value="{{ $ad->title }}">
<label class="text-[10px] font-bold uppercase text-slate-500">Tarifa mensual<input name="monthly_fee" value="{{ $ad->monthly_fee }}" type="number" step="0.01" class="mt-1 w-full rounded-lg border-slate-200 text-xs"></label><label class="text-[10px] font-bold uppercase text-slate-500">Inicio<input name="starts_on" value="{{ $ad->starts_on?->format('Y-m-d') }}" type="date" class="mt-1 w-full rounded-lg border-slate-200 text-xs"></label><label class="text-[10px] font-bold uppercase text-slate-500">Fin<input name="ends_on" value="{{ $ad->ends_on?->format('Y-m-d') }}" type="date" class="mt-1 w-full rounded-lg border-slate-200 text-xs"></label><fieldset class="md:col-span-2"><legend class="text-[10px] font-bold uppercase text-slate-500">Ubicaciones</legend><div class="mt-2 flex flex-wrap gap-2">@foreach($placements as $value=>$label)<label class="rounded-lg border border-slate-200 px-2 py-1 text-[10px]"><input type="checkbox" name="placements[]" value="{{ $value }}" @checked(in_array($value,$ad->placements??[]))> {{ $label }}</label>@endforeach</div></fieldset><label class="text-[10px] font-bold uppercase text-slate-500">Estado<select name="status" class="mt-1 w-full rounded-lg border-slate-200 text-xs">@foreach(['lead_pending','active','paused','expired'] as $state)<option value="{{ $state }}" @selected($ad->status===$state)>{{ $state }}</option>@endforeach</select></label><label class="md:col-span-3 text-[10px] font-bold uppercase text-slate-500">Notas internas<textarea name="admin_notes" class="mt-1 w-full rounded-lg border-slate-200 text-xs">{{ $ad->admin_notes }}</textarea></label><button class="md:col-span-3 rounded-lg bg-amber-400 py-2.5 text-xs font-black text-slate-950">Guardar cambios</button></form></article>@empty<div class="rounded-xl border border-dashed border-slate-300 bg-white p-10 text-center text-xs text-slate-500">No hay solicitudes ni campañas con estos filtros.</div>@endforelse</section>
{{ $ads->links() }}
</div>
@endsection
