@extends('layouts.admin')
@section('header')<h1 class="ny-page-title">Flota y permisos DICAPI / DGAC</h1>@endsection
@section('content')
<div class="space-y-6">
 <section class="rounded-3xl bg-[#062c21] p-7 text-white"><span class="text-[10px] font-black uppercase tracking-widest text-emerald-300">Cumplimiento normativo</span><h1 class="mt-2 text-2xl font-black">Registro regional de unidades</h1><p class="mt-1 text-xs text-emerald-100/70">Matrículas, capacidad, certificados e inspecciones de las empresas afiliadas.</p></section>
 @if(session('success'))<div class="rounded-xl bg-emerald-50 p-4 text-sm font-bold text-emerald-800">{{ session('success') }}</div>@endif
 <section class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><header class="border-b border-slate-100 p-5"><h2 class="font-black text-slate-900">Embarcaciones fluviales</h2></header><div class="overflow-x-auto"><table class="min-w-[980px] w-full text-left text-xs"><thead class="bg-slate-50 text-[10px] uppercase text-slate-400"><tr><th class="p-4">Matrícula</th><th class="p-4">Unidad</th><th class="p-4">Empresa</th><th class="p-4">Capacidad</th><th class="p-4">Inspección</th><th class="p-4">Estado</th><th class="p-4 text-right">Acción</th></tr></thead><tbody class="divide-y divide-slate-100">@forelse($vessels as $vessel)<tr><td class="p-4 font-mono font-bold">{{ $vessel->registration_number }}</td><td class="p-4 font-bold text-slate-900">{{ $vessel->name }}</td><td class="p-4">{{ $vessel->organization->commercial_name ?? $vessel->organization->legal_name ?? '—' }}</td><td class="p-4">{{ $vessel->seat_capacity }} pasajeros</td><td class="p-4">{{ $vessel->inspection_expires_at?->format('d/m/Y') ?? 'Por registrar' }}</td><td class="p-4">{{ ucfirst($vessel->status) }}</td><td class="p-4"><form method="POST" action="{{ route('admin.fleet-compliance.verify',$vessel) }}" class="flex justify-end gap-2">@csrf @method('PATCH')<select name="status" class="h-8 rounded-lg border-slate-200 text-[10px]"><option value="ready">Aprobado</option><option value="maintenance">En revisión</option><option value="inactive">Inhabilitado</option></select><button class="rounded-lg bg-amber-500 px-3 text-[10px] font-bold">Aplicar</button></form></td></tr>@empty<tr><td colspan="7" class="p-10 text-center text-slate-400">No hay embarcaciones registradas.</td></tr>@endforelse</tbody></table></div><div class="border-t p-4">{{ $vessels->links() }}</div></section>
 <section class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><header class="border-b border-slate-100 p-5"><h2 class="font-black text-slate-900">Aeronaves regionales</h2></header><div class="grid gap-3 p-5 md:grid-cols-2 xl:grid-cols-3">@forelse($aircraft as $unit)<article class="rounded-2xl border border-slate-200 p-4"><span class="text-[10px] font-bold text-sky-700">✈ MATRÍCULA {{ $unit->registration_number }}</span><h3 class="mt-1 font-black">{{ $unit->name }}</h3><p class="text-xs text-slate-500">{{ $unit->organization->commercial_name ?? $unit->organization->legal_name ?? '—' }} · {{ $unit->seat_capacity }} pasajeros</p></article>@empty<p class="text-sm text-slate-400">No hay aeronaves registradas.</p>@endforelse</div></section>
</div>
@endsection
