<x-app-layout>
    <x-slot name="header"><h2 class="ny-page-title">Portada principal</h2></x-slot>
    <div class="mx-auto max-w-6xl space-y-6">
        @if(session('success'))<p class="rounded-xl bg-emerald-50 p-4 text-emerald-800">{{session('success')}}</p>@endif
        <section class="rounded-2xl bg-white p-7 shadow-sm ring-1 ring-slate-200">
            <p class="text-xs font-bold uppercase tracking-widest text-[#0d6b5e]">Transición automática</p>
            <div class="mt-3 flex flex-wrap items-end justify-between gap-5"><div><h1 class="text-2xl font-bold">Imágenes de la portada</h1><p class="mt-1 text-slate-600">La página pública usa las imágenes activas según el orden indicado.</p></div>
            <form method="POST" action="{{route('admin.home-hero.duration')}}" class="flex items-end gap-3">@csrf @method('PATCH')<label class="font-semibold">Segundos por imagen<input class="mt-1 block w-28 rounded-lg border-slate-300" type="number" min="3" max="15" name="duration" value="{{$duration}}"></label><button class="rounded-lg bg-[#0d6b5e] px-4 py-2.5 font-bold text-white">Guardar</button></form></div>
        </section>
        @foreach($slides as $slide)
        <form method="POST" action="{{route('admin.home-hero.update',$slide)}}" enctype="multipart/form-data" class="rounded-2xl bg-white p-7 shadow-sm ring-1 ring-slate-200">@csrf @method('PATCH')
            <div class="mb-5 flex items-center justify-between"><h2 class="text-xl font-bold">Imagen {{$loop->iteration}}</h2><label class="inline-flex items-center gap-2 font-semibold"><input type="checkbox" name="is_active" value="1" @checked($slide->is_active)> Visible</label></div>
            <div class="grid gap-5 md:grid-cols-2"><label class="font-semibold">Ruta o URL de imagen<input class="mt-1 w-full rounded-lg border-slate-300" name="image_path" value="{{old('image_path',$slide->image_path)}}"></label><label class="font-semibold">Reemplazar con archivo <input class="mt-1 w-full rounded-lg border-slate-300" type="file" accept="image/*" name="image"></label><label class="font-semibold">Título<input required class="mt-1 w-full rounded-lg border-slate-300" name="title" value="{{old('title',$slide->title)}}"></label><label class="font-semibold">Orden<input required class="mt-1 w-full rounded-lg border-slate-300" type="number" min="1" name="sort_order" value="{{old('sort_order',$slide->sort_order)}}"></label><label class="font-semibold md:col-span-2">Texto descriptivo<textarea class="mt-1 w-full rounded-lg border-slate-300" rows="2" name="subtitle">{{old('subtitle',$slide->subtitle)}}</textarea></label><label class="font-semibold">Texto del botón<input required class="mt-1 w-full rounded-lg border-slate-300" name="button_label" value="{{old('button_label',$slide->button_label)}}"></label><label class="font-semibold">Destino del botón<input required class="mt-1 w-full rounded-lg border-slate-300" name="button_url" value="{{old('button_url',$slide->button_url)}}"></label></div>
            <div class="mt-5 flex gap-3"><button class="rounded-lg bg-[#0d6b5e] px-5 py-3 font-bold text-white">Guardar cambios</button><button formmethod="POST" formaction="{{route('admin.home-hero.destroy',$slide)}}" name="_method" value="DELETE" onclick="return confirm('¿Retirar esta imagen de la portada?')" class="rounded-lg border border-rose-300 px-5 py-3 font-bold text-rose-700">Eliminar</button></div>
        </form>
        @endforeach
        <details class="rounded-2xl bg-white p-7 shadow-sm ring-1 ring-slate-200"><summary class="cursor-pointer text-lg font-bold">Agregar nueva imagen</summary><form method="POST" action="{{route('admin.home-hero.store')}}" enctype="multipart/form-data" class="mt-6 grid gap-5 md:grid-cols-2">@csrf <label class="font-semibold">Imagen (archivo)<input class="mt-1 w-full rounded-lg border-slate-300" type="file" accept="image/*" name="image"></label><label class="font-semibold">o ruta / URL<input class="mt-1 w-full rounded-lg border-slate-300" name="image_path" placeholder="/images/mi-imagen.png"></label><label class="font-semibold">Título<input required class="mt-1 w-full rounded-lg border-slate-300" name="title"></label><label class="font-semibold">Orden<input required class="mt-1 w-full rounded-lg border-slate-300" type="number" min="1" name="sort_order" value="{{$slides->count()+1}}"></label><label class="font-semibold md:col-span-2">Texto<textarea class="mt-1 w-full rounded-lg border-slate-300" name="subtitle"></textarea></label><label class="font-semibold">Botón<input required class="mt-1 w-full rounded-lg border-slate-300" name="button_label" value="Buscar salida"></label><label class="font-semibold">Enlace<input required class="mt-1 w-full rounded-lg border-slate-300" name="button_url" value="#buscar"></label><label class="inline-flex items-center gap-2 font-semibold"><input type="checkbox" name="is_active" value="1" checked> Visible</label><div class="md:col-span-2"><button class="rounded-lg bg-[#d9a814] px-5 py-3 font-bold text-[#103a31]">Agregar imagen</button></div></form></details>
    </div>
</x-app-layout>
