<x-app-layout>
    <x-slot name="header"><h2 class="ny-page-title">Operación de transporte</h2></x-slot>
    <style>
        .ny-operation{max-width:1100px;margin:0 auto}.ny-operation-hero{padding:34px 38px;border-radius:20px;background:linear-gradient(120deg,#10352f,#176d60);color:#fff;box-shadow:0 12px 30px rgba(12,55,47,.15)}.ny-operation-eyebrow{margin:0;color:#b7e8d8;font-size:11px;font-weight:800;letter-spacing:.14em;text-transform:uppercase}.ny-operation-hero h1{margin:8px 0;font-size:30px;line-height:1.15}.ny-operation-hero p{max-width:760px;margin:0;color:#e5f6f0;line-height:1.6}.ny-mode-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:22px;margin-top:24px}.ny-mode-card{overflow:hidden;border:1px solid #dce7e4;border-radius:18px;background:#fff;box-shadow:0 8px 22px rgba(15,23,42,.06)}.ny-mode-line{height:5px}.ny-mode-card-body{padding:26px}.ny-mode-top{display:flex;align-items:start;justify-content:space-between;gap:12px}.ny-mode-icon{display:grid;place-items:center;width:48px;height:48px;border-radius:14px;font-size:23px}.ny-status{border-radius:999px;padding:7px 10px;font-size:11px;font-weight:800}.ny-mode-card h2{margin:22px 0 8px;font-size:25px;color:#152e2b}.ny-mode-card p{margin:0;color:#52636a;line-height:1.55}.ny-list{margin:18px 0 0;padding:0;list-style:none;color:#334155;font-size:14px}.ny-list li{padding:5px 0}.ny-list li:before{content:'✓';margin-right:8px;font-weight:800;color:#16856b}.ny-mode-note{margin:20px 0 0;font-size:11px;font-weight:800;letter-spacing:.07em;text-transform:uppercase}.ny-river .ny-mode-line{background:#16a07c}.ny-river .ny-mode-icon{background:#d9f7ed}.ny-river .ny-status{background:#e7fbf1;color:#087057}.ny-river .ny-mode-note{color:#087057}.ny-air .ny-mode-line{background:#4f88df}.ny-air .ny-mode-icon{background:#e3efff}.ny-air .ny-status{background:#eaf3ff;color:#2769be}.ny-air .ny-mode-note{color:#2769be}@media(max-width:780px){.ny-operation-hero{padding:25px}.ny-mode-grid{grid-template-columns:1fr}.ny-operation-hero h1{font-size:26px}}
    </style>
    <div class="ny-operation">
        <section class="ny-operation-hero"><p class="ny-operation-eyebrow">Configuración operativa</p><h1>Transporte fluvial y aéreo</h1><p>NavegaYA inicia con la operación fluvial. El transporte aéreo se incorporará mediante integraciones autorizadas con proveedores de vuelos.</p></section>
        <div class="ny-mode-grid">
            <article class="ny-mode-card ny-river"><div class="ny-mode-line"></div><div class="ny-mode-card-body"><div class="ny-mode-top"><div class="ny-mode-icon">🚢</div><span class="ny-status">PRINCIPAL · ACTIVO</span></div><h2>Transporte fluvial</h2><p>Empresas de transporte, embarcaciones, puertos, rutas, salidas, mapas de asientos, reservas y boletos.</p><ul class="ny-list"><li>Registro y validación de operadores</li><li>Rutas y horarios por río</li><li>Venta de pasajes y control de embarque</li></ul><p class="ny-mode-note">Desarrollo por módulos desde el Sprint 2</p></div></article>
            <article class="ny-mode-card ny-air"><div class="ny-mode-line"></div><div class="ny-mode-card-body"><div class="ny-mode-top"><div class="ny-mode-icon">✈</div><span class="ny-status">FASE FUTURA</span></div><h2>Transporte aéreo</h2><p>Consulta y comercialización mediante una integración formal con un proveedor autorizado de vuelos; no se registran vuelos manualmente.</p><ul class="ny-list"><li>Proveedor, contrato y credenciales autorizadas</li><li>Consulta de disponibilidad y tarifas</li><li>Reservas, emisión y conciliación mediante API</li></ul><p class="ny-mode-note">Se habilitará luego de consolidar la operación fluvial</p></div></article>
        </div>
    </div>
</x-app-layout>
