<?php

use App\Http\Controllers\Admin\AdminAdvertisementController;
use App\Http\Controllers\Admin\AdminCompanyController;
use App\Http\Controllers\Admin\AdminDashboardController;
use App\Http\Controllers\Admin\AdminFleetComplianceController;
use App\Http\Controllers\Admin\AdminFleetController;
use App\Http\Controllers\Admin\AdminItineraryController;
use App\Http\Controllers\Admin\AdminRefundController;
use App\Http\Controllers\Admin\AdminSalesController;
use App\Http\Controllers\Admin\AdminSettlementController;
use App\Http\Controllers\Admin\AdminSupervisionController;
use App\Http\Controllers\Admin\AdminTourController;
use App\Http\Controllers\Admin\AdminTourismPartnerController;
use App\Http\Controllers\AdminAircraftController;
use App\Http\Controllers\AdminAirRouteController;
use App\Http\Controllers\AdminAuditLogController;
use App\Http\Controllers\AdminBoardingController;
use App\Http\Controllers\AdminCargoShipmentController;
use App\Http\Controllers\AdminDestinationController;
use App\Http\Controllers\AdminDestinationListingController;
use App\Http\Controllers\AdminHomeHeroController;
use App\Http\Controllers\AdminManifestController;
use App\Http\Controllers\AdminMasterRouteController;
use App\Http\Controllers\AdminNavigationController;
use App\Http\Controllers\AdminOperationController;
use App\Http\Controllers\AdminOrganizationDirectoryController;
use App\Http\Controllers\AdminOrganizationReviewController;
use App\Http\Controllers\AdminPortController;
use App\Http\Controllers\AdminReportController;
use App\Http\Controllers\AdminSettingsController;
use App\Http\Controllers\AdminTransportRouteController;
use App\Http\Controllers\AdminUserController;
use App\Http\Controllers\AdminVesselController;
use App\Http\Controllers\AdminVesselSeatController;
use App\Http\Controllers\AirBookingController;
use App\Http\Controllers\Auth\CompanyRegisterController;
use App\Http\Controllers\BookingController;
use App\Http\Controllers\CartController;
use App\Http\Controllers\Company\CompanyBoardingController;
use App\Http\Controllers\Company\CompanyDepartureController;
use App\Http\Controllers\Company\CompanyFleetController;
use App\Http\Controllers\Company\CompanyPosController;
use App\Http\Controllers\Company\CompanySalesController;
use App\Http\Controllers\Company\CompanySettlementController;
use App\Http\Controllers\Company\CompanyStaffController as CompanyPortalStaffController;
use App\Http\Controllers\CompanyActivationController;
use App\Http\Controllers\CompanyCounterController;
use App\Http\Controllers\CompanyDashboardController;
use App\Http\Controllers\CompanyRegistrationController;
use App\Http\Controllers\CompanyStaffController;
use App\Http\Controllers\CulqiPaymentController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\DiscoverController;
use App\Http\Controllers\GuideController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\PaymentController;
use App\Http\Controllers\PaymentWebhookController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\PublicAdController;
use App\Http\Controllers\PublicCompanyController;
use App\Http\Controllers\PublicLocaleController;
use App\Http\Controllers\PublicPageController;
use App\Http\Controllers\PublicPortController;
use App\Http\Controllers\PublicRouteCatalogController;
use App\Http\Controllers\TravelController;
use App\Http\Controllers\WeatherController;
use Illuminate\Support\Facades\Route;

Route::get('/', HomeController::class)->name('home');
Route::get('/anunciate', [PublicAdController::class, 'showLanding'])->name('advertising.create');
Route::post('/anunciate', [PublicAdController::class, 'storeLead'])->middleware('throttle:10,1')->name('advertising.store');
Route::get('/pagina/{slug}', [PublicPageController::class, 'show'])->name('pages.show');
Route::get('/clima-loreto', [WeatherController::class, 'index'])->name('weather.index');
Route::match(['get', 'post'], '/idioma', [PublicLocaleController::class, 'store'])->name('public.locale');
Route::get('/descubrir', [DiscoverController::class, 'index'])->name('discover.index');
Route::view('/quienes-somos', 'about')->name('about');
Route::get('/rutas-fluviales', [PublicRouteCatalogController::class, 'index'])->name('routes.index');
Route::get('/empresas', [PublicCompanyController::class, 'index'])->name('companies.index');
Route::get('/puertos-y-muelles', [PublicPortController::class, 'index'])->name('ports.public');
Route::get('/guia-loreto', [GuideController::class, 'index'])->name('guide.index');
Route::get('/empresas/{organization}', [PublicCompanyController::class, 'show'])->name('companies.show');
Route::post('/empresas/{organization}/valoraciones', [PublicCompanyController::class, 'review'])->middleware(['auth', 'verified'])->name('companies.review');
Route::get('/anuncio/{ad}', [DiscoverController::class, 'advertisement'])->name('discover.ad');
Route::get('/destinos/{city}', [DiscoverController::class, 'show'])->name('discover.show');
Route::post('/destinos/{city}/valoraciones', [DiscoverController::class, 'review'])->middleware(['auth', 'verified'])->name('discover.review');

Route::get('/dashboard', DashboardController::class)->middleware('auth')->name('dashboard');
Route::redirect('/empresa/panel', '/empresa/salidas')->middleware(['auth', 'role:company_admin'])->name('company.dashboard');
Route::patch('/empresa/panel/perfil', [CompanyDashboardController::class, 'updateProfile'])->middleware(['auth', 'role:company_admin'])->name('company.dashboard.profile');
Route::post('/empresa/personal', [CompanyStaffController::class, 'store'])->middleware(['auth', 'role:company_admin'])->name('company.staff.store');
Route::patch('/empresa/personal/{user}/estado', [CompanyStaffController::class, 'toggle'])->middleware(['auth', 'role:company_admin'])->name('company.staff.toggle');
Route::delete('/empresa/personal/{user}', [CompanyStaffController::class, 'destroy'])->middleware(['auth', 'role:company_admin'])->name('company.staff.destroy');
Route::get('/empresa/despacho', [CompanyCounterController::class, 'index'])->middleware(['auth', 'role:company_admin|company_counter'])->name('company.counter.index');
Route::middleware(['auth', 'role:company_admin|company_counter'])->prefix('empresa')->name('company.')->group(function () {
    Route::get('/salidas', [CompanyDepartureController::class, 'index'])->name('departures.index');
    Route::post('/salidas', [CompanyDepartureController::class, 'store'])->name('departures.store');
    Route::get('/salidas/{departure}/embarque', [CompanyBoardingController::class, 'show'])->name('boarding.show');
    Route::patch('/salidas/{departure}/embarque/{ticket}', [CompanyBoardingController::class, 'toggle'])->name('boarding.toggle');
    Route::get('/salidas/{departure}/manifiesto', [CompanyDepartureController::class, 'manifest'])->name('departures.manifest');
    Route::get('/flota', [CompanyFleetController::class, 'index'])->name('fleet.index');
    Route::get('/personal', [CompanyPortalStaffController::class, 'index'])->name('staff.index');
    Route::get('/liquidaciones', [CompanySettlementController::class, 'index'])->name('settlements.index');
    Route::get('/pos', [CompanyPosController::class, 'index'])->name('pos.index');
    Route::post('/pos', [CompanyPosController::class, 'store'])->name('pos.store');
});
Route::middleware(['auth', 'role:company_admin'])->prefix('empresa')->name('company.')->group(function () {
    Route::get('/ventas', [CompanySalesController::class, 'index'])->name('sales.index');
    Route::get('/ventas/exportar', [CompanySalesController::class, 'export'])->name('sales.export');
    Route::post('/flota/embarcaciones', [CompanyFleetController::class, 'storeVessel'])->name('fleet.vessels.store');
    Route::post('/flota/aeronaves', [CompanyFleetController::class, 'storeAircraft'])->name('fleet.aircraft.store');
    Route::get('/equipo', fn () => redirect()->route('company.staff.index'))->name('personnel.index');
    Route::get('/finanzas', fn () => redirect()->route('company.settlements.index'))->name('finance.index');
    Route::patch('/liquidaciones/cuenta-bancaria', [CompanySettlementController::class, 'updateBank'])->name('finance.bank');
});
Route::middleware(['auth', 'role:company_admin'])->prefix('empresa/salidas')->name('company.departures.')->group(function () {
    Route::get('/programar', [AdminTransportRouteController::class, 'createDeparture'])->name('create');
    Route::get('/{departure}/editar', [AdminTransportRouteController::class, 'editDeparture'])->name('edit');
    Route::patch('/{departure}', [AdminTransportRouteController::class, 'updateDeparture'])->name('update');
    Route::patch('/{departure}/estado', [AdminTransportRouteController::class, 'updateDepartureStatus'])->name('status');
});
Route::get('/reservar/{departure}', [BookingController::class, 'create'])->name('bookings.create');
Route::post('/reservar/{departure}', [BookingController::class, 'store'])->name('bookings.store');
Route::get('/reservar-aereo/{departure}', [AirBookingController::class, 'create'])->name('air-bookings.create');
Route::post('/reservar-aereo/{departure}', [AirBookingController::class, 'store'])->name('air-bookings.store');
Route::get('/reserva/{code}/confirmacion', [BookingController::class, 'confirmation'])->name('bookings.confirmation');
Route::get('/carrito', [CartController::class, 'index'])->name('cart.index');
Route::delete('/carrito/{reservation}', [CartController::class, 'remove'])->name('cart.remove');
Route::post('/carrito/confirmar', [CartController::class, 'checkout'])->name('cart.checkout');
Route::get('/carrito/{code}/pago', [CartController::class, 'payment'])->name('cart.payment');
Route::post('/carrito/{code}/pago/prueba', [CartController::class, 'sandboxConfirm'])->name('cart.sandbox-confirm');
Route::get('/carrito/{code}/boletos', [CartController::class, 'tickets'])->name('cart.tickets');
Route::get('/carrito/{code}/boletos/pdf', [CartController::class, 'pdf'])->name('cart.tickets.pdf');
Route::get('/carrito/{code}/boletos/descargar', [CartController::class, 'pdf'])->name('cart.pdf');
Route::get('/reserva/{code}/pago', [PaymentController::class, 'show'])->name('payments.show');
Route::post('/reserva/{code}/pago/prueba', [PaymentController::class, 'sandboxConfirm'])->name('payments.sandbox-confirm');
Route::post('/reserva/{code}/pago/culqi', [CulqiPaymentController::class, 'charge'])->name('payments.culqi.charge');
Route::post('/reserva/{code}/pago/culqi/orden', [CulqiPaymentController::class, 'order'])->name('payments.culqi.order');
Route::post('/webhooks/culqi', [PaymentWebhookController::class, 'culqi'])->name('webhooks.culqi');
Route::get('/reserva/{code}/boletos', [PaymentController::class, 'tickets'])->name('tickets.show');
Route::get('/boleto/{ticketCode}/qr', [PaymentController::class, 'qr'])->name('tickets.qr');
Route::get('/boleto/{ticketCode}/pdf', [PaymentController::class, 'pdf'])->name('tickets.pdf');
Route::get('/abordaje/verificar/{token}', [PaymentController::class, 'verify'])->name('tickets.verify');
Route::get('/mis-viajes', [TravelController::class, 'index'])->name('travels.index');
Route::post('/mis-viajes/buscar', [TravelController::class, 'search'])->name('travels.search');
Route::post('/mis-viajes/consulta', [TravelController::class, 'lookup'])->name('travels.lookup');

Route::middleware('auth')->group(function () {
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
});

Route::get('/registro-empresa', [CompanyRegistrationController::class, 'create'])->name('company.registration');
Route::post('/registro-empresa', [CompanyRegisterController::class, 'register'])->name('company.registration.store');
Route::get('/afiliate', [CompanyRegisterController::class, 'create'])->name('company.register');
Route::post('/afiliate', [CompanyRegisterController::class, 'register'])->name('company.register.store');
Route::get('/registro-empresa/verificar/{organization}', [CompanyRegistrationController::class, 'verify'])->middleware('signed')->name('company.registration.verify');

Route::middleware(['auth', 'role:super_admin'])->prefix('admin')->name('admin.')->group(function () {
    Route::get('/dashboard', [AdminDashboardController::class, 'index'])->name('dashboard');
    Route::resource('/empresas', AdminCompanyController::class)
        ->parameters(['empresas' => 'organization'])->names('companies');
    Route::patch('/empresas/{organization}/toggle-status', [AdminCompanyController::class, 'toggleStatus'])->name('companies.toggle-status');
    Route::get('/flota-unidades', fn () => redirect()->route('admin.companies.index'))->name('fleet.index');
    Route::patch('/flota-unidades/embarcaciones/{vessel}/estado', [AdminFleetController::class, 'updateVesselStatus'])->name('fleet.vessels.status');
    Route::patch('/flota-unidades/aeronaves/{aircraft}/estado', [AdminFleetController::class, 'updateAircraftStatus'])->name('fleet.aircraft.status');
    Route::get('/itinerarios', [AdminItineraryController::class, 'index'])->name('itineraries.index');
    Route::patch('/itinerarios/operadores/{organization}/ventas', [AdminItineraryController::class, 'toggleOperatorSales'])->name('itineraries.operator-sales');
    Route::patch('/itinerarios/{departure}/publicacion', [AdminItineraryController::class, 'togglePublication'])->name('itineraries.publication');
    Route::get('/itinerarios/{departure}/editar', [AdminItineraryController::class, 'edit'])->name('itineraries.edit');
    Route::put('/itinerarios/{departure}', [AdminItineraryController::class, 'update'])->name('itineraries.update');
    Route::get('/supervision-salidas', fn () => redirect()->route('admin.itineraries.index', request()->query()))->name('supervision.index');
    Route::get('/supervision-salidas/{departure}/editar', fn (int $departure) => redirect()->route('admin.itineraries.edit', ['departure' => $departure, ...request()->query()]))->name('supervision.edit');
    Route::put('/supervision-salidas/{departure}', [AdminSupervisionController::class, 'update'])->name('supervision.update');
    Route::get('/flota-permisos', [AdminFleetComplianceController::class, 'index'])->name('fleet-compliance.index');
    Route::patch('/flota-permisos/{vessel}/verify', [AdminFleetComplianceController::class, 'verifyVessel'])->name('fleet-compliance.verify');
    Route::get('/liquidaciones', [AdminSettlementController::class, 'index'])->name('settlements.index');
    Route::post('/liquidaciones/{organization}/pagar', [AdminSettlementController::class, 'storeSettlement'])->name('settlements.store');
    Route::get('/ventas-globales', [AdminSalesController::class, 'index'])->name('sales.index');
    Route::get('/tours-experiencias', [AdminTourController::class, 'index'])->name('tours.index');
    Route::get('/aliados-turisticos', [AdminTourismPartnerController::class, 'index'])->name('tourism-partners.index');
    Route::get('/publicidad-pautas', [AdminAdvertisementController::class, 'index'])->name('advertisements.index');
    Route::post('/publicidad-pautas', [AdminAdvertisementController::class, 'store'])->name('advertisements.store');
    Route::patch('/publicidad-pautas/{ad}', [AdminAdvertisementController::class, 'update'])->name('advertisements.update');
    Route::patch('/publicidad-pautas/{ad}/aprobar', [AdminAdvertisementController::class, 'approve'])->name('advertisements.approve');
    Route::patch('/publicidad-pautas/{ad}/pausar', [AdminAdvertisementController::class, 'pause'])->name('advertisements.pause');
    Route::patch('/publicidad-pautas/{ad}/reactivar', [AdminAdvertisementController::class, 'resume'])->name('advertisements.resume');
    Route::get('/reembolsos-soporte', [AdminRefundController::class, 'index'])->name('refunds.index');
    Route::get('/configuracion', [AdminSettingsController::class, 'index'])->name('settings.index');
    Route::post('/configuracion', [AdminSettingsController::class, 'update'])->name('settings.update');
    Route::get('/menu-paginas', [AdminNavigationController::class, 'index'])->name('navigation.index');
    Route::post('/menu-paginas/pestanas', [AdminNavigationController::class, 'storeItem'])->name('navigation.items.store');
    Route::patch('/menu-paginas/pestanas/{item}', [AdminNavigationController::class, 'updateItem'])->name('navigation.items.update');
    Route::delete('/menu-paginas/pestanas/{item}', [AdminNavigationController::class, 'destroyItem'])->name('navigation.items.destroy');
    Route::post('/menu-paginas/paginas', [AdminNavigationController::class, 'storePage'])->name('navigation.pages.store');
    Route::patch('/menu-paginas/paginas/{page}', [AdminNavigationController::class, 'updatePage'])->name('navigation.pages.update');
    Route::delete('/menu-paginas/paginas/{page}', [AdminNavigationController::class, 'destroyPage'])->name('navigation.pages.destroy');
    Route::get('/publicidad', [AdminAdvertisementController::class, 'index'])->name('ads.index');
    Route::post('/publicidad', [AdminAdvertisementController::class, 'store'])->name('ads.store');
    Route::patch('/publicidad/{ad}/aprobar', [AdminAdvertisementController::class, 'approve'])->name('ads.approve');
    Route::patch('/publicidad/{ad}/pausar', [AdminAdvertisementController::class, 'pause'])->name('ads.pause');
    Route::patch('/publicidad/{ad}/reactivar', [AdminAdvertisementController::class, 'resume'])->name('ads.resume');
    Route::get('/destinos', [AdminDestinationController::class, 'index'])->name('destinations.index');
    Route::get('/destinos/crear', [AdminDestinationController::class, 'create'])->name('destinations.create');
    Route::post('/destinos', [AdminDestinationController::class, 'store'])->name('destinations.store');
    Route::get('/destinos/valoraciones', [AdminDestinationController::class, 'reviews'])->name('destinations.reviews');
    Route::patch('/destinos/valoraciones/{review}/aprobar', [AdminDestinationController::class, 'approveReview'])->name('destinations.reviews.approve');
    Route::get('/destinos/{city}/editar', [AdminDestinationController::class, 'edit'])->name('destinations.edit');
    Route::patch('/destinos/{city}', [AdminDestinationController::class, 'update'])->name('destinations.update');
    Route::delete('/destinos/{city}', [AdminDestinationController::class, 'destroy'])->name('destinations.destroy');
    Route::get('/contenido/{type}', [AdminDestinationListingController::class, 'index'])->name('destination-listings.index');
    Route::get('/contenido/{type}/crear', [AdminDestinationListingController::class, 'create'])->name('destination-listings.create');
    Route::post('/contenido/{type}', [AdminDestinationListingController::class, 'store'])->name('destination-listings.store');
    Route::get('/contenido/{type}/{item}/editar', [AdminDestinationListingController::class, 'edit'])->name('destination-listings.edit');
    Route::patch('/contenido/{type}/{item}', [AdminDestinationListingController::class, 'update'])->name('destination-listings.update');
    Route::delete('/contenido/{type}/{item}', [AdminDestinationListingController::class, 'destroy'])->name('destination-listings.destroy');
    Route::patch('/contenido/{type}/{item}/imagenes/{image}/portada', [AdminDestinationListingController::class, 'cover'])->name('destination-listings.images.cover');
    Route::delete('/contenido/{type}/{item}/imagenes/{image}', [AdminDestinationListingController::class, 'deleteImage'])->name('destination-listings.images.destroy');
    Route::get('/auditoria', [AdminAuditLogController::class, 'index'])->name('audit.index');
    Route::patch('/configuracion/whatsapp', [AdminSettingsController::class, 'updateWhatsApp'])->name('settings.whatsapp');
    Route::patch('/configuracion/encabezado-pie', [AdminSettingsController::class, 'updateChrome'])->name('settings.chrome');
    Route::patch('/configuracion/diseno', [AdminSettingsController::class, 'updateTheme'])->name('settings.theme');
    Route::patch('/configuracion/pagos', [AdminSettingsController::class, 'updatePayments'])->name('settings.payments');
    Route::get('/portada-principal', [AdminHomeHeroController::class, 'index'])->name('home-hero.index');
    Route::post('/portada-principal', [AdminHomeHeroController::class, 'store'])->name('home-hero.store');
    Route::patch('/portada-principal/duracion', [AdminHomeHeroController::class, 'updateDuration'])->name('home-hero.duration');
    Route::patch('/portada-principal/{slide}', [AdminHomeHeroController::class, 'update'])->name('home-hero.update');
    Route::delete('/portada-principal/{slide}', [AdminHomeHeroController::class, 'destroy'])->name('home-hero.destroy');
    Route::get('/reportes', [AdminReportController::class, 'index'])->name('reports.index');
    Route::get('/reportes/exportar', [AdminReportController::class, 'export'])->name('reports.export');
    Route::get('/salidas/{departure}/manifiesto', [AdminManifestController::class, 'show'])->name('manifests.show');
    Route::get('/salidas/{departure}/manifiesto/csv', [AdminManifestController::class, 'csv'])->name('manifests.csv');
    Route::resource('/usuarios', AdminUserController::class)->parameters(['usuarios' => 'user'])->names('users');
    Route::get('/solicitudes-empresa', [AdminOrganizationReviewController::class, 'index'])->name('organizations.index');
    Route::post('/solicitudes-empresa/provisionar', [AdminOrganizationReviewController::class, 'storeManual'])->name('organizations.provision');
    Route::get('/empresas-agencias', [AdminOrganizationDirectoryController::class, 'index'])->name('organization-directory.index');
    Route::get('/operacion-transporte', [AdminOperationController::class, 'index'])->name('operation.index');
    Route::get('/puertos-terminales', [AdminPortController::class, 'index'])->name('ports.index');
    Route::get('/puertos-terminales/crear', [AdminPortController::class, 'create'])->name('ports.create');
    Route::get('/ubicacion/departamentos/{department}/provincias', [AdminPortController::class, 'provinces'])->name('locations.provinces');
    Route::get('/ubicacion/provincias/{province}/distritos', [AdminPortController::class, 'districts'])->name('locations.districts');
    Route::post('/puertos-terminales', [AdminPortController::class, 'store'])->name('ports.store');
    Route::get('/puertos-terminales/{port}', [AdminPortController::class, 'show'])->name('ports.show');
    Route::get('/puertos-terminales/{port}/editar', [AdminPortController::class, 'edit'])->name('ports.edit');
    Route::match(['put', 'patch'], '/puertos-terminales/{port}', [AdminPortController::class, 'update'])->name('ports.update');
    Route::delete('/puertos-terminales/{port}', [AdminPortController::class, 'destroy'])->name('ports.destroy');
    Route::get('/carga-encomiendas', [AdminCargoShipmentController::class, 'index'])->name('cargo.index');
    Route::get('/carga-general', fn () => redirect()->route('admin.cargo.index'))->name('cargo.legacy');
    Route::get('/carga/registrar', [AdminCargoShipmentController::class, 'create'])->name('cargo.create');
    Route::get('/carga/buscar-pasajero', [AdminCargoShipmentController::class, 'passengerLookup'])->name('cargo.passenger-lookup');
    Route::post('/carga', [AdminCargoShipmentController::class, 'store'])->name('cargo.store');
    Route::patch('/carga/{cargo}/verificar', [AdminCargoShipmentController::class, 'verify'])->name('cargo.verify');
    Route::patch('/carga/{cargo}/entregar', [AdminCargoShipmentController::class, 'deliver'])->name('cargo.deliver');
    Route::get('/control-embarque', [AdminBoardingController::class, 'index'])->name('boarding.index');
    Route::patch('/control-embarque/{ticket}/embarcar', [AdminBoardingController::class, 'board'])->name('boarding.board');
    Route::get('/rutas-salidas', [AdminTransportRouteController::class, 'index'])->name('transport-routes.index');
    Route::get('/rutas-salidas/ciudades/{city}/puertos', [AdminTransportRouteController::class, 'portsByCity'])->name('transport-routes.city-ports');
    Route::resource('/rutas-oficiales', AdminMasterRouteController::class)
        ->parameters(['rutas-oficiales' => 'master_route'])->names('master-routes');
    Route::get('/embarcaciones', [AdminVesselController::class, 'index'])->name('vessels.index');
    Route::get('/embarcaciones/crear', [AdminVesselController::class, 'create'])->name('vessels.create');
    Route::post('/embarcaciones', [AdminVesselController::class, 'store'])->name('vessels.store');
    Route::get('/embarcaciones/{vessel}/editar', [AdminVesselController::class, 'edit'])->name('vessels.edit');
    Route::patch('/embarcaciones/{vessel}', [AdminVesselController::class, 'update'])->name('vessels.update');
    Route::get('/embarcaciones/{vessel}/asientos', [AdminVesselSeatController::class, 'edit'])->name('vessels.seats.edit');
    Route::post('/embarcaciones/{vessel}/asientos/generar', [AdminVesselSeatController::class, 'generate'])->name('vessels.seats.generate');
    Route::patch('/embarcaciones/{vessel}/asientos/{seat}/estado', [AdminVesselSeatController::class, 'toggle'])->name('vessels.seats.toggle');
    Route::delete('/embarcaciones/{vessel}/asientos/cubierta', [AdminVesselSeatController::class, 'destroyDeck'])->name('vessels.seats.destroy-deck');
    Route::get('/aeronaves', fn () => redirect()->route('admin.companies.index'))->name('aircraft.index');
    Route::get('/rutas-aereas', [AdminAirRouteController::class, 'index'])->name('air-routes.index');
    Route::get('/rutas-aereas/crear', [AdminAirRouteController::class, 'form'])->name('air-routes.form');
    Route::get('/salidas-aereas/programar', [AdminAirRouteController::class, 'departureForm'])->name('air-routes.departures.form');
    Route::post('/rutas-aereas', [AdminAirRouteController::class, 'store'])->name('air-routes.store');
    Route::get('/rutas-aereas/{airRoute}/editar', [AdminAirRouteController::class, 'edit'])->name('air-routes.edit');
    Route::patch('/rutas-aereas/{airRoute}', [AdminAirRouteController::class, 'update'])->name('air-routes.update');
    Route::delete('/rutas-aereas/{airRoute}', [AdminAirRouteController::class, 'destroy'])->name('air-routes.destroy');
    Route::post('/rutas-aereas/salidas', [AdminAirRouteController::class, 'storeDeparture'])->name('air-routes.departures.store');
    Route::get('/aeronaves/crear', [AdminAircraftController::class, 'create'])->name('aircraft.create');
    Route::post('/aeronaves', [AdminAircraftController::class, 'store'])->name('aircraft.store');
    Route::get('/aeronaves/{aircraft}/editar', [AdminAircraftController::class, 'edit'])->name('aircraft.edit');
    Route::patch('/aeronaves/{aircraft}', [AdminAircraftController::class, 'update'])->name('aircraft.update');
    Route::get('/aeronaves/{aircraft}/asientos', [AdminAircraftController::class, 'seats'])->name('aircraft.seats');
    Route::post('/aeronaves/{aircraft}/asientos/generar', [AdminAircraftController::class, 'generateSeats'])->name('aircraft.seats.generate');
    Route::get('/empresas-agencias/{organization}', [AdminOrganizationDirectoryController::class, 'show'])->name('organization-directory.show');
    Route::patch('/empresas-agencias/{organization}/perfil-publico', [AdminOrganizationDirectoryController::class, 'updatePublicProfile'])->name('organization-directory.public-profile');
    Route::patch('/empresas-agencias/{organization}/valoraciones/{review}/aprobar', [AdminOrganizationDirectoryController::class, 'approveReview'])->name('organization-directory.reviews.approve');
    Route::patch('/solicitudes-empresa/{organization}/aprobar', [AdminOrganizationReviewController::class, 'approve'])->name('organizations.approve');
    Route::patch('/solicitudes-empresa/{organization}/rechazar', [AdminOrganizationReviewController::class, 'reject'])->name('organizations.reject');
});

Route::get('/activar-empresa/{token}', [CompanyActivationController::class, 'create'])->name('company.activation');
Route::post('/activar-empresa/{token}', [CompanyActivationController::class, 'store']);

require __DIR__.'/auth.php';
