@extends('layouts.company')
@section('title', 'Venta en muelle')
@section('page-title', 'Punto de Venta en Muelle')
@section('content')
<div class="mx-auto max-w-6xl space-y-5">
 <section class="rounded-3xl bg-[#062c21] p-6 text-white shadow-xl"><span class="text-[10px] font-bold uppercase tracking-wider text-emerald-300">Venta presencial</span><div class="mt-2 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><h2 class="text-2xl font-black">Emitir boleto en counter</h2><p class="mt-1 text-xs text-emerald-100/75">Selecciona una salida de hoy, cobra en efectivo y entrega el boleto inmediatamente.</p></div><span class="rounded-xl border border-white/15 bg-white/10 px-3 py-2 text-[10px] font-bold">Sin comisión web · según configuración</span></div></section>
 @if($departures->isEmpty())<div class="rounded-3xl border border-slate-200 bg-white p-10 text-center text-sm text-slate-500">No existen salidas fluviales programadas para hoy.</div>@else
 <form method="GET" class="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><label class="text-[10px] font-bold uppercase text-slate-400">Salida de hoy</label><div class="mt-1 flex gap-2"><select name="departure" class="h-11 flex-1 rounded-xl border-slate-200 bg-slate-50 text-xs font-bold" onchange="this.form.submit()">@foreach($departures as $departure)<option value="{{ $departure->id }}" @selected($selectedDeparture?->id === $departure->id)>{{ $departure->departure_at->format('H:i') }} · {{ $departure->transportRoute->originPort->city }} ➔ {{ $departure->transportRoute->destinationPort->city }} · {{ $departure->vessel->name }}</option>@endforeach</select></div></form>
 <form method="POST" action="{{ route('company.pos.store') }}" class="grid gap-5 lg:grid-cols-[1fr_380px]">@csrf<input type="hidden" name="departure_id" value="{{ $selectedDeparture->id }}">
  <section class="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><div class="border-b border-slate-100 pb-3"><h3 class="font-black text-slate-900">Selecciona un asiento</h3><p class="text-xs text-slate-400">Los asientos grises ya están ocupados o retenidos.</p></div><div class="mt-5 grid grid-cols-4 gap-3 sm:grid-cols-6">@foreach($selectedDeparture->vessel->seats->sortBy(['row_position','column_position']) as $seat)<label class="cursor-pointer"><input type="radio" name="seat_id" value="{{ $seat->id }}" class="peer sr-only" @disabled(in_array($seat->id,$occupiedSeatIds,true)) required><span class="grid h-12 place-items-center rounded-xl border-2 border-emerald-200 bg-white text-xs font-black text-emerald-800 peer-checked:border-amber-500 peer-checked:bg-[#062c21] peer-checked:text-amber-300 peer-disabled:cursor-not-allowed peer-disabled:border-slate-200 peer-disabled:bg-slate-200 peer-disabled:text-slate-400">{{ $seat->code }}</span></label>@endforeach</div></section>
  <aside class="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><h3 class="font-black text-slate-900">Datos del pasajero</h3><div class="mt-4 space-y-3">@foreach([['passenger_name','Nombres y apellidos','text'],['document_number','DNI / documento','text'],['passenger_age','Edad','number'],['phone','Teléfono / WhatsApp','text'],['email','Correo (opcional)','email']] as [$name,$label,$type])<label class="block"><span class="text-[9px] font-bold uppercase tracking-wider text-slate-400">{{ $label }}</span><input type="{{ $type }}" name="{{ $name }}" value="{{ old($name) }}" @required($name!=='email') class="mt-1 h-10 w-full rounded-xl border-slate-200 bg-slate-50 text-xs font-semibold"></label>@endforeach<label class="block"><span class="text-[9px] font-bold uppercase tracking-wider text-slate-400">Tipo de documento</span><select name="document_type" class="mt-1 h-10 w-full rounded-xl border-slate-200 bg-slate-50 text-xs font-semibold"><option>DNI</option><option>CE</option><option>Pasaporte</option></select></label></div>@if($errors->any())<p class="mt-3 rounded-xl bg-rose-50 p-3 text-xs text-rose-700">{{ $errors->first() }}</p>@endif<div class="mt-4 rounded-xl bg-emerald-50 p-3 text-xs"><span class="text-slate-500">Cobro en efectivo</span><strong class="float-right text-lg text-slate-900">S/ {{ number_format((float)$selectedDeparture->fare,2) }}</strong></div><button class="mt-4 h-11 w-full rounded-xl bg-amber-500 text-xs font-black text-slate-950 hover:bg-amber-600">Cobrar y emitir boleto</button></aside>
 </form>
 @endif
</div>
@endsection
