<x-public-layout current="companies" title="Empresas de transporte · NavegaYA">
<div class="min-h-screen bg-slate-50">
<div class="mx-auto max-w-7xl px-4 pb-16 pt-4 sm:px-6 lg:px-8">
<x-amazon-hero-bg theme="companies" class="rounded-3xl text-center shadow-2xl md:rounded-[2.5rem]" overlay="from-slate-950/95 via-[#062c21]/85 to-slate-900/55"><div class="mx-auto max-w-3xl px-2 pb-14 pt-6 sm:pb-16 sm:pt-8"><div class="mb-3 inline-flex items-center gap-2 rounded-full border border-emerald-400/30 bg-emerald-950/70 px-3 py-1 text-[11px] font-bold uppercase tracking-wider text-emerald-200 shadow-inner backdrop-blur-sm"><svg class="h-3.5 w-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path stroke-linecap="round" stroke-linejoin="round" d="m9 12 2 2 4-5M12 3l7 3v5c0 5-3 8-7 10-4-2-7-5-7-10V6l7-3Z"/></svg><span>Operadores oficiales y verificados</span></div><h1 class="text-3xl font-extrabold leading-tight tracking-tight text-white sm:text-4xl md:text-5xl">Empresas de transporte autorizadas</h1><p class="mx-auto mt-3 max-w-xl text-xs leading-relaxed text-emerald-100/80 sm:text-sm md:text-base">Conoce la flota, itinerarios y garantías de las empresas fluviales y aéreas que conectan la Amazonía.</p></div></x-amazon-hero-bg>

<section class="relative z-20 mx-auto mt-6 max-w-6xl px-2 sm:px-4" x-data="{filter:'all'}">
<div class="mb-6 flex flex-wrap items-center justify-between gap-4 rounded-2xl border border-slate-200/80 bg-white p-4 shadow-sm"><div class="flex flex-wrap items-center gap-2"><span class="text-xs font-bold uppercase tracking-wider text-slate-400">Filtrar por:</span><div class="inline-flex rounded-xl bg-slate-100 p-1 text-xs"><button type="button" @click="filter='all'" :class="filter==='all'?'bg-white text-emerald-900 shadow-sm':'text-slate-500'" class="rounded-lg px-3 py-1.5 font-semibold transition">Todos ({{$companies->count()}})</button><button type="button" @click="filter='river'" :class="filter==='river'?'bg-white text-emerald-900 shadow-sm':'text-slate-500'" class="flex items-center gap-1 rounded-lg px-3 py-1.5 font-medium transition"><svg class="h-3.5 w-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path stroke-linecap="round" stroke-linejoin="round" d="M3 15.5 5.2 19h13.6l2.2-3.5L19.2 9H4.8L3 15.5Z"/></svg>Fluviales</button><button type="button" @click="filter='air'" :class="filter==='air'?'bg-white text-sky-900 shadow-sm':'text-slate-500'" class="flex items-center gap-1 rounded-lg px-3 py-1.5 font-medium transition"><svg class="h-3.5 w-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path stroke-linecap="round" stroke-linejoin="round" d="M21 16.5 13.2 13V6.2c0-1.5-.5-3.7-1.2-3.7s-1.2 2.2-1.2 3.7V13L3 16.5v1.8l7.8-1.7V20l-2.2 1.2V22l3.4-.6 3.4.6v-.8L13.2 20v-3.4l7.8 1.7v-1.8Z"/></svg>Aéreos</button></div></div><div class="flex items-center gap-1.5 text-xs text-slate-500"><span class="h-2 w-2 rounded-full bg-emerald-500"></span><span>Operadoras con permisos vigentes</span></div></div>

<div class="grid grid-cols-1 gap-6 md:grid-cols-2 lg:grid-cols-3">
@forelse($companies as $company)
@php
    $name = $company->commercial_name ?: $company->legal_name;
    $hasRiver = $company->vessels_count > 0 || $company->transport_routes_count > 0;
    $hasAir = $company->aircraft_count > 0 || $company->air_routes_count > 0;
    $modeLabel = $hasRiver && $hasAir ? 'Fluvial y aéreo' : ($hasAir ? 'Operador aéreo' : 'Transporte fluvial');
@endphp
<a x-show="filter==='all'||(filter==='river'&&{{$hasRiver?'true':'false'}})||(filter==='air'&&{{$hasAir?'true':'false'}})" href="{{route('companies.show',$company)}}" class="group block cursor-pointer rounded-3xl border border-slate-200/80 bg-white p-6 shadow-sm transition-all duration-200 hover:-translate-y-0.5 hover:border-emerald-600/50 hover:shadow-xl focus:outline-none focus:ring-2 focus:ring-emerald-700 focus:ring-offset-2"><div class="flex h-full flex-col justify-between"><div><div class="mb-4 flex items-start justify-between gap-3"><div class="grid h-12 w-12 shrink-0 place-items-center rounded-2xl border {{$hasAir&&!$hasRiver?'border-sky-100 bg-sky-50 text-sky-800':'border-emerald-100 bg-emerald-50 text-emerald-800'}} text-xl font-black transition group-hover:scale-105">{{$hasAir&&!$hasRiver?'✈':'🚤'}}</div><span class="inline-flex items-center gap-1 rounded-full border border-emerald-200 bg-emerald-50 px-2.5 py-1 text-[11px] font-bold text-emerald-700">✓ Verificada</span></div><h2 class="text-lg font-extrabold text-slate-900 transition group-hover:text-emerald-800">{{$name}}</h2><p class="mt-1 line-clamp-2 text-xs leading-relaxed text-slate-500">{{$company->public_description?:'Operador formal de transporte con rutas y horarios programados en Loreto.'}}</p><div class="mt-5 grid grid-cols-2 gap-2 border-t border-slate-100 pt-4 text-center"><div class="rounded-xl bg-slate-50 p-2"><span class="block text-[10px] font-bold uppercase text-slate-400">Flota activa</span><span class="text-xs font-black text-slate-800">{{$company->vessels_count+$company->aircraft_count}} unidad(es)</span></div><div class="rounded-xl bg-slate-50 p-2"><span class="block text-[10px] font-bold uppercase text-slate-400">Rutas</span><span class="text-xs font-black text-slate-800">{{$company->transport_routes_count+$company->air_routes_count}} ruta(s)</span></div></div></div><div class="mt-4 flex items-center justify-between border-t border-slate-100 pt-3 text-xs font-bold {{$hasAir&&!$hasRiver?'text-sky-700':'text-emerald-700'}}"><span>{{$modeLabel}}</span><span class="flex items-center gap-1 transition-transform group-hover:translate-x-1">Ver salidas y flota →</span></div></div></a>
@empty
<div class="rounded-3xl border border-dashed border-slate-300 bg-white p-10 text-center text-sm text-slate-500 md:col-span-2">No hay empresas verificadas disponibles.</div>
@endforelse

<article class="flex flex-col justify-between rounded-3xl border border-emerald-800 bg-gradient-to-br from-emerald-900 to-[#062c21] p-6 text-white shadow-md"><div><div class="mb-4 grid h-12 w-12 place-items-center rounded-2xl border border-white/20 bg-white/10 backdrop-blur"><svg class="h-6 w-6" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path stroke-linecap="round" stroke-linejoin="round" d="M8 12h8m-4-4v8M5 21h14a2 2 0 0 0 2-2V7l-4-4H7L3 7v12a2 2 0 0 0 2 2Z"/></svg></div><span class="text-[10px] font-bold uppercase tracking-wider text-amber-400">¿Eres operador?</span><h2 class="mt-1 text-lg font-bold">Afilia tu empresa en NavegaYA</h2><p class="mt-2 text-xs leading-relaxed text-emerald-100/80">Vende boletos las 24 horas, controla abordajes con QR y administra tu flota con reportes automatizados.</p></div><a href="{{route('company.registration')}}" class="mt-6 inline-flex w-full items-center justify-center gap-2 rounded-xl bg-amber-500 px-4 py-3 text-xs font-bold text-slate-950 shadow-sm transition hover:bg-amber-600">Solicitar afiliación <span>→</span></a></article>
</div>
</section>
</div></div>
</x-public-layout>

