@extends('layouts.company')
@section('title','Liquidaciones y finanzas')
@section('page-title','Liquidaciones & Finanzas')
@section('content')
<div class="mx-auto max-w-7xl space-y-6">
<section class="rounded-3xl bg-[#062c21] p-6 text-white"><span class="text-[10px] font-bold uppercase tracking-wider text-emerald-300">Conciliación empresarial</span><h2 class="mt-1 text-2xl font-black">Ingresos y liquidaciones</h2><p class="mt-1 text-xs text-emerald-100/70">La comisión NavegaYA configurada para tu empresa es {{ number_format($commissionRate,2) }}%.</p></section>
<section class="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">@foreach([['GMV hoy',$grossToday],['Comisión hoy',$commissionToday],['GMV del mes',$grossMonth],['Neto estimado del mes',$grossMonth-$commissionMonth]] as [$label,$amount])<article class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><span class="text-[10px] font-bold uppercase tracking-wider text-slate-400">{{ $label }}</span><strong class="mt-2 block text-2xl font-black {{ str_contains($label,'Comisión')?'text-amber-600':'text-slate-900' }}">S/ {{ number_format($amount,2) }}</strong></article>@endforeach</section>
<section class="grid gap-6 lg:grid-cols-12"><div class="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm lg:col-span-8"><div class="border-b border-slate-100 px-5 py-4"><h3 class="font-black text-slate-900">Ventas confirmadas recientes</h3></div><div class="overflow-x-auto"><table class="w-full min-w-[650px] text-left text-xs"><thead class="bg-slate-50 text-[10px] uppercase text-slate-400"><tr><th class="px-5 py-3">Reserva</th><th class="px-4 py-3">Ruta</th><th class="px-4 py-3">Fecha</th><th class="px-5 py-3 text-right">Total</th></tr></thead><tbody>@forelse($recentReservations as $reservation)@php($air=$reservation->isAir())<tr class="border-t border-slate-100"><td class="px-5 py-4 font-bold">{{ $reservation->code }}</td><td class="px-4 py-4">{{ $air?($reservation->airDeparture?->airRoute?->origin_city??'Origen'):($reservation->departure?->transportRoute?->originPort?->city??'Origen') }} ➔ {{ $air?($reservation->airDeparture?->airRoute?->destination_city??'Destino'):($reservation->departure?->transportRoute?->destinationPort?->city??'Destino') }}</td><td class="px-4 py-4 text-slate-500">{{ $reservation->updated_at->format('d/m/Y H:i') }}</td><td class="px-5 py-4 text-right font-black">S/ {{ number_format((float)$reservation->total_amount,2) }}</td></tr>@empty<tr><td colspan="4" class="px-5 py-12 text-center text-slate-500">No hay ventas confirmadas.</td></tr>@endforelse</tbody></table></div></div>
<aside class="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm lg:col-span-4"><span class="text-[10px] font-bold uppercase tracking-wider text-emerald-700">Cuenta de abono</span><h3 class="mt-1 font-black text-slate-900">Datos bancarios</h3><form method="POST" action="{{ route('company.finance.bank') }}" class="mt-4 grid gap-3">@csrf @method('PATCH')<label class="text-xs font-bold">Banco<input required name="bank_name" value="{{ old('bank_name',$organization->bank_name) }}" class="mt-1 w-full rounded-xl border-slate-200 text-sm"></label><label class="text-xs font-bold">Número de cuenta<input required name="bank_account" value="{{ old('bank_account',$organization->bank_account) }}" class="mt-1 w-full rounded-xl border-slate-200 text-sm"></label><label class="text-xs font-bold">CCI<input name="bank_cci" value="{{ old('bank_cci',$organization->bank_cci) }}" class="mt-1 w-full rounded-xl border-slate-200 text-sm"></label><button class="rounded-xl bg-amber-500 px-4 py-3 text-xs font-black text-slate-950">Guardar cuenta bancaria</button></form><p class="mt-3 text-[10px] leading-relaxed text-slate-400">Los montos son conciliaciones de reservas confirmadas y se muestran en soles peruanos.</p></aside></section>
</div>
@endsection
