<x-public-layout current="routes" title="Vuelos amazónicos · NavegaYA">
@php
    $searched = request()->hasAny(['origin','destination','date']);
    $popularRoutes = $airDepartures->groupBy(fn($flight) => $flight->airRoute->origin_city.' → '.$flight->airRoute->destination_city);
@endphp
<div class="min-h-screen bg-slate-50">
<div class="mx-auto max-w-7xl px-4 pb-4 pt-4 sm:px-6 lg:px-8">
<section class="relative overflow-hidden rounded-3xl bg-gradient-to-br from-sky-950 via-[#0b3b5a] to-slate-950 px-6 pb-28 pt-12 text-center shadow-2xl sm:px-10 md:rounded-[2.5rem] md:pb-32"><div class="pointer-events-none absolute inset-0 opacity-10"><div class="absolute -top-24 left-1/2 h-[300px] w-[600px] -translate-x-1/2 rounded-full bg-cyan-300 blur-3xl"></div></div><div class="relative z-10 mx-auto max-w-3xl"><div class="mx-auto mb-4 grid h-12 w-12 place-items-center rounded-2xl border border-sky-300/30 bg-sky-400/10 text-sky-200 shadow-lg shadow-sky-950/30 backdrop-blur"><svg class="h-7 w-7" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" aria-hidden="true"><path stroke-linecap="round" stroke-linejoin="round" d="M21 16.5 13.2 13V6.2c0-1.5-.5-3.7-1.2-3.7s-1.2 2.2-1.2 3.7V13L3 16.5v1.8l7.8-1.7V20l-2.2 1.2V22l3.4-.6 3.4.6v-.8L13.2 20v-3.4l7.8 1.7v-1.8Z"/></svg></div><div class="mb-3 inline-flex items-center gap-1.5 rounded-full border border-sky-400/30 bg-sky-950/70 px-3 py-1 text-[11px] font-bold uppercase tracking-wider text-sky-200"><span>Conexiones aéreas de la Amazonía</span></div><h1 class="mx-auto max-w-3xl text-3xl font-extrabold leading-tight tracking-tight text-white sm:text-4xl md:text-5xl">{{ $searched?'Vuelos disponibles':'Horarios y salidas programadas' }}</h1><p class="mx-auto mt-2.5 max-w-lg text-xs leading-relaxed text-sky-100/80 sm:text-sm">Consulta frecuencias aéreas, compara operadores verificados y reserva varios asientos con confirmación inmediata.</p></div></section>

<div class="relative z-20 mx-auto mt-6 max-w-5xl px-2 sm:px-4"><div class="rounded-3xl border border-slate-100 bg-white p-4 shadow-xl shadow-slate-900/5 sm:p-6"><div class="mb-4 flex flex-wrap items-center justify-between gap-3 border-b border-slate-100 pb-3"><nav class="inline-flex rounded-xl bg-slate-100 p-1 text-xs"><a href="{{route('routes.index',['transport'=>'river'])}}" class="flex items-center gap-1.5 rounded-lg px-3 py-1.5 font-medium text-slate-500 transition hover:text-slate-800"><svg class="h-3.5 w-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path stroke-linecap="round" stroke-linejoin="round" d="M3 15.5 5.2 19h13.6l2.2-3.5L19.2 9H4.8L3 15.5Z"/></svg>Fluvial</a><a href="{{route('routes.index',['transport'=>'air'])}}" class="flex items-center gap-1.5 rounded-lg bg-white px-3 py-1.5 font-semibold text-sky-900 shadow-sm"><svg class="h-3.5 w-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path stroke-linecap="round" stroke-linejoin="round" d="M21 16.5 13.2 13V6.2c0-1.5-.5-3.7-1.2-3.7s-1.2 2.2-1.2 3.7V13L3 16.5v1.8l7.8-1.7V20l-2.2 1.2V22l3.4-.6 3.4.6v-.8L13.2 20v-3.4l7.8 1.7v-1.8Z"/></svg>Aéreo</a></nav><nav class="hidden flex-wrap items-center gap-1.5 text-xs text-slate-500 sm:flex"><span class="mr-1 text-[11px] font-semibold text-slate-400">Rutas frecuentes:</span>@foreach($popularRoutes->keys()->take(3) as $name)<a href="{{route('routes.index',['transport'=>'air','origin'=>str($name)->before(' → '),'destination'=>str($name)->after(' → ')])}}" class="whitespace-nowrap rounded-lg border border-slate-200/70 bg-slate-50 px-2.5 py-1 text-[11px] font-medium text-slate-500 transition hover:bg-sky-50 hover:text-sky-800">{{$name}}</a>@endforeach</nav></div>
<form action="{{route('routes.index')}}" method="GET" class="grid grid-cols-1 items-center gap-1.5 rounded-2xl border border-slate-200/80 bg-slate-50 p-1.5 sm:grid-cols-2 lg:grid-cols-12"><input type="hidden" name="transport" value="air"><label class="relative rounded-xl border border-transparent bg-white px-3 py-2 transition hover:border-slate-200 focus-within:ring-2 focus-within:ring-sky-600 lg:col-span-4"><span class="block text-[10px] font-semibold uppercase tracking-wider text-slate-400">Origen</span><span class="flex items-center gap-1.5"><span class="text-xs">📍</span><select name="origin" class="w-full appearance-none border-0 bg-transparent p-0 pr-4 text-xs font-semibold text-slate-800 focus:ring-0"><option value="">Selecciona ciudad</option>@foreach($cities as $city)<option value="{{$city}}" @selected(request('origin')===$city)>{{$city}}</option>@endforeach</select></span><span class="pointer-events-none absolute bottom-2.5 right-3 text-xs text-slate-400">⌄</span></label><label class="relative rounded-xl border border-transparent bg-white px-3 py-2 transition hover:border-slate-200 focus-within:ring-2 focus-within:ring-sky-600 lg:col-span-4"><span class="block text-[10px] font-semibold uppercase tracking-wider text-slate-400">Destino</span><span class="flex items-center gap-1.5"><span class="text-xs">🎯</span><select name="destination" class="w-full appearance-none border-0 bg-transparent p-0 pr-4 text-xs font-semibold text-slate-800 focus:ring-0"><option value="">Selecciona ciudad</option>@foreach($cities as $city)<option value="{{$city}}" @selected(request('destination')===$city)>{{$city}}</option>@endforeach</select></span><span class="pointer-events-none absolute bottom-2.5 right-3 text-xs text-slate-400">⌄</span></label><label class="rounded-xl border border-transparent bg-white px-3 py-2 transition hover:border-slate-200 focus-within:ring-2 focus-within:ring-sky-600 lg:col-span-2"><span class="block text-[10px] font-semibold uppercase tracking-wider text-slate-400">Fecha salida</span><input type="date" name="date" value="{{request('date')}}" class="w-full border-0 bg-transparent p-0 text-xs font-semibold text-slate-800 focus:ring-0"></label><div class="p-0.5 lg:col-span-2"><button class="flex h-11 w-full items-center justify-center gap-1.5 rounded-xl bg-amber-500 text-xs font-bold text-slate-950 shadow-sm transition hover:bg-amber-600 active:scale-95">⌕ Filtrar</button></div></form></div></div>
</div>

<main class="mx-auto max-w-5xl px-4 pb-16 pt-4"><x-b2b-ad-banner placement="routes_sidebar" class="mb-5" /><div class="mb-5 flex items-end justify-between"><div><span class="text-[10px] font-bold uppercase tracking-widest text-sky-700">Transporte aéreo</span><h2 class="text-xl font-bold text-slate-900">Vuelos disponibles</h2></div><a href="{{route('routes.index',['transport'=>'air'])}}" class="text-xs font-semibold text-sky-700">Limpiar filtros</a></div>
@forelse($dateGroups as $date=>$items)<div class="mb-3 mt-7 flex items-center gap-3"><span class="rounded-full bg-sky-50 px-3 py-1 text-xs font-bold uppercase text-sky-800">{{\Carbon\Carbon::parse($date)->isToday()?'Hoy':(\Carbon\Carbon::parse($date)->isTomorrow()?'Mañana':\Carbon\Carbon::parse($date)->translatedFormat('D d M'))}}</span><span class="text-xs capitalize text-slate-500">{{\Carbon\Carbon::parse($date)->translatedFormat('l d \d\e F')}}</span></div>@foreach($items as $flight)
<x-departure-card :departure="$flight" />
@endforeach
@empty<div class="rounded-3xl border border-dashed border-slate-300 bg-white p-12 text-center"><h3 class="text-sm font-bold text-slate-800">No encontramos vuelos</h3><p class="mt-1 text-xs text-slate-500">Prueba con otra fecha, origen o destino.</p></div>@endforelse</main>
</div>
</x-public-layout>

