@extends('layouts.company')
@section('title','Personal Counter')
@section('page-title','Personal Counter')
@section('content')
<div class="mx-auto max-w-6xl space-y-6" x-data="{open:false}">
<section class="flex flex-col justify-between gap-4 rounded-3xl bg-[#062c21] p-6 text-white sm:flex-row sm:items-center"><div><span class="text-[10px] font-bold uppercase tracking-wider text-emerald-300">Accesos limitados por empresa</span><h2 class="mt-1 text-2xl font-black">Equipo de muelle y counter</h2><p class="mt-1 text-xs text-emerald-100/70">Estos usuarios solo pueden despachar pasajeros y consultar manifiestos de {{ $organization->commercial_name?:$organization->legal_name }}.</p></div><button @click="open=!open" class="rounded-xl bg-amber-500 px-4 py-2.5 text-xs font-black text-slate-950">＋ Nuevo Counter</button></section>
@if($errors->any())<div class="rounded-xl border border-rose-200 bg-rose-50 p-4 text-xs text-rose-700">{{ $errors->first() }}</div>@endif
<form x-show="open" x-cloak method="POST" action="{{ route('company.staff.store') }}" class="grid gap-4 rounded-3xl border border-slate-200 bg-white p-6 shadow-sm sm:grid-cols-2 lg:grid-cols-3">@csrf<input required name="name" placeholder="Nombre completo" class="rounded-xl border-slate-200 text-sm"><input required type="email" name="email" placeholder="Correo" class="rounded-xl border-slate-200 text-sm"><input required name="document_number" placeholder="DNI / documento" class="rounded-xl border-slate-200 text-sm"><input required name="phone" placeholder="Teléfono" class="rounded-xl border-slate-200 text-sm"><input required type="password" name="password" placeholder="Contraseña temporal" class="rounded-xl border-slate-200 text-sm"><input required type="password" name="password_confirmation" placeholder="Confirmar contraseña" class="rounded-xl border-slate-200 text-sm"><button class="rounded-xl bg-[#062c21] px-5 py-3 text-xs font-black text-white sm:col-span-2 lg:col-span-3">Crear acceso Counter</button></form>
<section class="overflow-hidden rounded-3xl border border-slate-200/90 bg-white shadow-sm"><div class="border-b border-slate-100 px-5 py-4"><h3 class="font-black text-slate-900">Usuarios vinculados</h3></div><div class="overflow-x-auto"><table class="w-full min-w-[720px] text-left text-xs"><thead class="bg-slate-50 text-[10px] uppercase tracking-wider text-slate-400"><tr><th class="px-5 py-3">Usuario</th><th class="px-4 py-3">Documento</th><th class="px-4 py-3">Teléfono</th><th class="px-4 py-3">Estado</th><th class="px-5 py-3 text-right">Acciones</th></tr></thead><tbody>@forelse($counterStaff as $staff)@php($membership=$staff->organizations->first()?->pivot)<tr class="border-t border-slate-100"><td class="px-5 py-4"><strong>{{ $staff->name }}</strong><span class="block text-[10px] text-slate-400">{{ $staff->email }}</span></td><td class="px-4 py-4">{{ $staff->document_number }}</td><td class="px-4 py-4">{{ $staff->phone }}</td><td class="px-4 py-4"><span class="rounded-full px-2.5 py-1 text-[10px] font-bold {{ $membership?->status==='active'?'bg-emerald-50 text-emerald-700':'bg-slate-100 text-slate-500' }}">{{ $membership?->status==='active'?'Activo':'Inactivo' }}</span></td><td class="px-5 py-4"><div class="flex justify-end gap-2"><form method="POST" action="{{ route('company.staff.toggle',$staff) }}">@csrf @method('PATCH')<button class="rounded-lg border border-slate-200 px-3 py-2 font-bold">{{ $membership?->status==='active'?'Deshabilitar':'Habilitar' }}</button></form><form method="POST" action="{{ route('company.staff.destroy',$staff) }}">@csrf @method('DELETE')<button class="rounded-lg bg-rose-50 px-3 py-2 font-bold text-rose-700">Retirar</button></form></div></td></tr>@empty<tr><td colspan="5" class="px-5 py-12 text-center text-slate-500">Todavía no hay usuarios Counter.</td></tr>@endforelse</tbody></table></div></section>
</div>
@endsection
