<x-app-layout>
@php($editing=(bool) $masterRoute)
<x-slot name="header"><h2 class="ny-page-title">{{ $editing ? 'Editar Tramo Maestro' : 'Nuevo Tramo Maestro' }}</h2></x-slot>
<div class="mx-auto max-w-5xl px-4 py-4 sm:px-6">
 <a href="{{ route('admin.master-routes.index') }}" class="text-xs font-bold text-emerald-800">← Volver al catálogo</a>
 <form method="POST" action="{{ $editing?route('admin.master-routes.update',$masterRoute):route('admin.master-routes.store') }}" class="mt-4 overflow-hidden rounded-3xl border border-slate-200/90 bg-white shadow-sm">@csrf @if($editing)@method('PUT')@endif
  <div class="bg-[#062c21] px-6 py-6 text-white sm:px-8"><span class="text-[10px] font-bold uppercase tracking-wider text-emerald-300">Gobernanza geográfica</span><h1 class="mt-1 text-2xl font-black">{{ $editing?'Editar conexión oficial':'Registrar conexión oficial' }}</h1><p class="mt-1 text-xs text-emerald-100/70">El origen y destino deben ser terminales distintos y pertenecer a sus ciudades declaradas.</p></div>
  <div class="grid gap-5 p-6 sm:grid-cols-2 sm:p-8">
   <label class="text-xs font-bold text-slate-700">Código oficial<input name="code" required maxlength="30" value="{{ old('code',$masterRoute->code??'') }}" placeholder="TRM-IQT-NAU" class="mt-1.5 h-11 w-full rounded-xl border-slate-200 bg-slate-50 text-sm uppercase"></label>
   <label class="text-xs font-bold text-slate-700">Modalidad<select name="modality" required class="mt-1.5 h-11 w-full rounded-xl border-slate-200 bg-slate-50 text-sm"><option value="fluvial" @selected(old('modality',$masterRoute->modality??'fluvial')==='fluvial')>🚤 Fluvial</option><option value="aereo" @selected(old('modality',$masterRoute->modality??'')==='aereo')>✈️ Aéreo</option></select></label>
   <label class="text-xs font-bold text-slate-700">Ciudad de origen<input name="origin_city" required value="{{ old('origin_city',$masterRoute->origin_city??'') }}" class="mt-1.5 h-11 w-full rounded-xl border-slate-200 bg-slate-50 text-sm"></label>
   <label class="text-xs font-bold text-slate-700">Terminal oficial de origen<select name="origin_port_id" required class="mt-1.5 h-11 w-full rounded-xl border-slate-200 bg-slate-50 text-sm"><option value="">Seleccionar terminal</option>@foreach($ports as $port)<option value="{{ $port->id }}" @selected(old('origin_port_id',$masterRoute->origin_port_id??null)==$port->id)>{{ $port->city }} · {{ $port->name }}</option>@endforeach</select></label>
   <label class="text-xs font-bold text-slate-700">Ciudad de destino<input name="destination_city" required value="{{ old('destination_city',$masterRoute->destination_city??'') }}" class="mt-1.5 h-11 w-full rounded-xl border-slate-200 bg-slate-50 text-sm"></label>
   <label class="text-xs font-bold text-slate-700">Terminal oficial de destino<select name="destination_port_id" required class="mt-1.5 h-11 w-full rounded-xl border-slate-200 bg-slate-50 text-sm"><option value="">Seleccionar terminal</option>@foreach($ports as $port)<option value="{{ $port->id }}" @selected(old('destination_port_id',$masterRoute->destination_port_id??null)==$port->id)>{{ $port->city }} · {{ $port->name }}</option>@endforeach</select></label>
   <label class="text-xs font-bold text-slate-700">Cuenca hidrográfica<input name="river_basin" value="{{ old('river_basin',$masterRoute->river_basin??'') }}" placeholder="Río Amazonas / Marañón" class="mt-1.5 h-11 w-full rounded-xl border-slate-200 bg-slate-50 text-sm"></label>
   <label class="text-xs font-bold text-slate-700">Corredor regional<input name="corridor" value="{{ old('corridor',$masterRoute->corridor??'') }}" placeholder="Corredor Nororiente" class="mt-1.5 h-11 w-full rounded-xl border-slate-200 bg-slate-50 text-sm"></label>
   <label class="text-xs font-bold text-slate-700">Duración referencial<input name="estimated_duration_text" value="{{ old('estimated_duration_text',$masterRoute->estimated_duration_text??'') }}" placeholder="1 h 45 min" class="mt-1.5 h-11 w-full rounded-xl border-slate-200 bg-slate-50 text-sm"></label>
   <label class="text-xs font-bold text-slate-700">Estado hidrológico / operativo<select name="status" required class="mt-1.5 h-11 w-full rounded-xl border-slate-200 bg-slate-50 text-sm"><option value="active" @selected(old('status',$masterRoute->status??'active')==='active')>Operativo</option><option value="suspended_river_level" @selected(old('status',$masterRoute->status??'')==='suspended_river_level')>Precaución / zarpes suspendidos</option><option value="maintenance" @selected(old('status',$masterRoute->status??'')==='maintenance')>Mantenimiento</option></select></label>
   @if($errors->any())<div class="sm:col-span-2 rounded-xl border border-rose-200 bg-rose-50 p-4 text-xs text-rose-700"><ul class="list-disc pl-4">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
   <div class="flex justify-end sm:col-span-2"><button class="h-11 rounded-xl bg-amber-500 px-6 text-xs font-black text-slate-950 hover:bg-amber-600">{{ $editing?'Guardar cambios':'Crear tramo maestro' }}</button></div>
  </div>
 </form>
</div>
</x-app-layout>
