@extends('layouts.admin')
@section('header')<h1 class="ny-page-title">Registrar empresa</h1>@endsection
@section('content')
<div class="mx-auto max-w-6xl"><form method="POST" action="{{ route('admin.companies.store') }}" class="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-xl">@csrf
 <header class="flex flex-col justify-between gap-4 bg-[#062c21] p-7 text-white sm:flex-row sm:items-center"><div><span class="text-[10px] font-bold uppercase tracking-[.18em] text-emerald-300">Provisionamiento manual</span><h1 class="mt-2 text-2xl font-black">Registrar y activar empresa</h1><p class="mt-1 text-xs text-emerald-100/70">Se generará automáticamente el acceso raíz al portal de empresa.</p></div><span class="rounded-full border border-emerald-500/40 bg-emerald-900/50 px-3 py-1.5 text-[10px] font-bold text-emerald-200">Rol automático: company_admin</span></header>
 <div class="grid gap-8 p-7 lg:grid-cols-2">
  <section><h2 class="font-black text-slate-900">1. Datos de la empresa transportista</h2><div class="mt-5 grid gap-4 sm:grid-cols-2"><label class="text-xs font-bold text-slate-600 sm:col-span-2">Razón social<input name="company_name" required value="{{ old('company_name') }}" class="mt-1 h-11 w-full rounded-xl border-slate-200 bg-slate-50"></label><label class="text-xs font-bold text-slate-600 sm:col-span-2">Nombre comercial<input name="commercial_name" value="{{ old('commercial_name') }}" class="mt-1 h-11 w-full rounded-xl border-slate-200 bg-slate-50"></label><label class="text-xs font-bold text-slate-600">RUC<input name="ruc" required maxlength="11" inputmode="numeric" value="{{ old('ruc') }}" class="mt-1 h-11 w-full rounded-xl border-slate-200 bg-slate-50"></label><label class="text-xs font-bold text-slate-600">Modalidad<select name="modality" class="mt-1 h-11 w-full rounded-xl border-slate-200 bg-slate-50">@foreach(['fluvial'=>'Fluvial','aereo'=>'Aéreo','mixto'=>'Mixto'] as $value=>$label)<option value="{{ $value }}" @selected(old('modality','fluvial')===$value)>{{ $label }}</option>@endforeach</select></label><label class="text-xs font-bold text-slate-600">Ciudad base<input name="base_city" required value="{{ old('base_city','Iquitos') }}" class="mt-1 h-11 w-full rounded-xl border-slate-200 bg-slate-50"></label><label class="text-xs font-bold text-slate-600">Teléfono / WhatsApp<input name="phone" required value="{{ old('phone') }}" class="mt-1 h-11 w-full rounded-xl border-slate-200 bg-slate-50"></label><label class="text-xs font-bold text-slate-600 sm:col-span-2">Comisión NavegaYA (%)<input type="number" name="commission_rate" min="0" max="100" step=".01" required value="{{ old('commission_rate','8.00') }}" class="mt-1 h-11 w-full rounded-xl border-slate-200 bg-slate-50"></label></div></section>
  <section class="rounded-2xl bg-slate-50 p-5"><h2 class="font-black text-slate-900">2. Credenciales del administrador</h2><p class="mt-1 text-xs text-slate-400">Cuenta principal responsable de flota, salidas, personal y ventas.</p><div class="mt-5 grid gap-4"><label class="text-xs font-bold text-slate-600">Nombre completo<input name="admin_name" required value="{{ old('admin_name') }}" class="mt-1 h-11 w-full rounded-xl border-slate-200 bg-white"></label><label class="text-xs font-bold text-slate-600">Correo electrónico de acceso<input type="email" name="admin_email" required value="{{ old('admin_email') }}" class="mt-1 h-11 w-full rounded-xl border-slate-200 bg-white"></label><label class="text-xs font-bold text-slate-600">Contraseña de acceso<input type="password" name="admin_password" required minlength="8" class="mt-1 h-11 w-full rounded-xl border-slate-200 bg-white"></label><label class="text-xs font-bold text-slate-600">Confirmar contraseña<input type="password" name="admin_password_confirmation" required minlength="8" class="mt-1 h-11 w-full rounded-xl border-slate-200 bg-white"></label><div class="rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-xs text-emerald-800"><strong class="block">Permiso automático</strong>Rol company_admin con acceso aislado a las herramientas de la empresa.</div></div></section>
  @if($errors->any())<div class="rounded-xl bg-rose-50 p-4 text-xs text-rose-700 lg:col-span-2"><ul class="list-disc pl-5">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
 </div><footer class="flex justify-end gap-3 border-t border-slate-100 bg-slate-50 px-7 py-5"><a href="{{ route('admin.companies.index') }}" class="rounded-xl border border-slate-200 bg-white px-5 py-3 text-xs font-bold text-slate-600">Cancelar</a><button class="rounded-xl bg-amber-500 px-6 py-3 text-xs font-black text-slate-950">Guardar y Activar Empresa</button></footer>
</form></div>
@endsection
