<aside class="ny-side"><div class="flex items-center justify-between border-b border-emerald-900/50 px-5 py-4"><div class="flex items-center space-x-3"><div class="flex h-8 w-8 items-center justify-center rounded-lg bg-amber-400 text-lg font-black text-emerald-950 shadow-sm">N</div><div><span class="block text-base font-black leading-none tracking-tight text-white">NavegaYA</span><span class="mt-1 block text-[9px] font-bold uppercase tracking-widest text-emerald-300">Panel Administrador</span></div></div></div>@php($isSuper=auth()->user()->roles()->where('code','super_admin')->exists())
@php($isCompanyAdmin=auth()->user()->roles()->where('code','company_admin')->exists())
@php($isCounter=auth()->user()->roles()->where('code','company_counter')->exists())
@php($can=fn(string $permission)=>$isSuper || auth()->user()->hasPermission($permission))
<nav class="ny-nav overflow-y-auto" aria-label="Menú administrativo">
@if($isSuper)
<div class="space-y-4 p-3.5 text-xs">
<section><p class="mb-1.5 px-2.5 text-[10px] font-bold uppercase tracking-wider text-emerald-400/80">Principal</p><a href="{{ route('admin.dashboard') }}" class="flex items-center space-x-2.5 rounded-lg px-2.5 py-2 font-semibold transition {{ request()->routeIs('admin.dashboard') ? 'bg-emerald-800 text-white shadow-sm' : 'text-emerald-100/70 hover:bg-emerald-900/50 hover:text-white' }}"><span>📊</span><span>Dashboard Gerencial</span></a></section>
<section><p class="mb-1.5 px-2.5 text-[10px] font-bold uppercase tracking-wider text-emerald-400/80">Empresas y Gobernanza</p><div class="space-y-0.5"><a href="{{ route('admin.companies.index') }}" class="flex items-center space-x-2.5 rounded-lg px-2.5 py-1.5 transition {{ request()->routeIs('admin.companies.*') ? 'bg-emerald-800 text-white font-bold' : 'text-emerald-100/70 hover:bg-emerald-900/40 hover:text-white' }}"><span>🏢</span><span>Empresas y Afiliaciones</span></a><a href="{{ route('admin.itineraries.index') }}" class="flex items-center space-x-2.5 rounded-lg px-2.5 py-1.5 transition {{ request()->routeIs('admin.itineraries.*','admin.supervision.*') ? 'bg-emerald-800 text-white font-bold' : 'text-emerald-100/70 hover:bg-emerald-900/40 hover:text-white' }}"><span>🕒</span><span>Inventario e Itinerarios</span></a></div></section>
<section><p class="mb-1.5 px-2.5 text-[10px] font-bold uppercase tracking-wider text-emerald-400/80">Turismo y Pautas B2B</p><div class="space-y-0.5"><a href="{{ route('admin.tourism-partners.index') }}" class="flex items-center space-x-2.5 rounded-lg px-2.5 py-1.5 transition {{ request()->routeIs('admin.tourism-partners.*') ? 'bg-emerald-800 text-white font-bold' : 'text-emerald-100/70 hover:bg-emerald-900/40 hover:text-white' }}"><span>🏡</span><span>Lodges, Hoteles y Rest.</span></a><a href="{{ route('admin.tours.index') }}" class="flex items-center space-x-2.5 rounded-lg px-2.5 py-1.5 transition {{ request()->routeIs('admin.tours.*') ? 'bg-emerald-800 text-white font-bold' : 'text-emerald-100/70 hover:bg-emerald-900/40 hover:text-white' }}"><span>🌿</span><span>Tours y Experiencias</span></a><a href="{{ route('admin.advertisements.index') }}" class="flex items-center space-x-2.5 rounded-lg px-2.5 py-1.5 transition {{ request()->routeIs('admin.advertisements.*','admin.ads.*') ? 'bg-emerald-800 text-white font-bold' : 'text-emerald-100/70 hover:bg-emerald-900/40 hover:text-white' }}"><span>📢</span><span>Pautas y Banners Ads</span></a></div></section>
<section><p class="mb-1.5 px-2.5 text-[10px] font-bold uppercase tracking-wider text-emerald-400/80">Catálogo Regional</p><div class="space-y-0.5"><a href="{{ route('admin.master-routes.index') }}" class="flex items-center space-x-2.5 rounded-lg px-2.5 py-1.5 transition {{ request()->routeIs('admin.master-routes.*') ? 'bg-emerald-800 text-white font-bold' : 'text-emerald-100/70 hover:bg-emerald-900/40 hover:text-white' }}"><span>🧭</span><span>Rutas y Corredores</span></a><a href="{{ route('admin.ports.index') }}" class="flex items-center space-x-2.5 rounded-lg px-2.5 py-1.5 transition {{ request()->routeIs('admin.ports.*') ? 'bg-emerald-800 text-white font-bold' : 'text-emerald-100/70 hover:bg-emerald-900/40 hover:text-white' }}"><span>⚓</span><span>Puertos y Aeródromos</span></a></div></section>
<section><p class="mb-1.5 px-2.5 text-[10px] font-bold uppercase tracking-wider text-emerald-400/80">Monetización NavegaYA</p><div class="space-y-0.5"><a href="{{ route('admin.sales.index') }}" class="flex items-center space-x-2.5 rounded-lg px-2.5 py-1.5 transition {{ request()->routeIs('admin.sales.*','admin.reports.*') ? 'bg-emerald-800 text-white font-bold' : 'text-emerald-100/70 hover:bg-emerald-900/40 hover:text-white' }}"><span>💳</span><span>Transacciones Marketplace</span></a><a href="{{ route('admin.commissions.index') }}" class="flex items-center space-x-2.5 rounded-lg px-2.5 py-1.5 transition {{ request()->routeIs('admin.commissions.*','admin.settlements.*') ? 'bg-emerald-800 text-white font-bold' : 'text-emerald-100/70 hover:bg-emerald-900/40 hover:text-white' }}"><span>📈</span><span>Comisiones y Facturación</span></a><a href="{{ route('admin.cargo.index') }}" class="flex items-center space-x-2.5 rounded-lg px-2.5 py-1.5 transition {{ request()->routeIs('admin.cargo.*') ? 'bg-emerald-800 text-white font-bold' : 'text-emerald-100/70 hover:bg-emerald-900/40 hover:text-white' }}"><span>📦</span><span>Carga y Encomiendas</span></a><a href="{{ route('admin.refunds.index') }}" class="flex items-center space-x-2.5 rounded-lg px-2.5 py-1.5 transition {{ request()->routeIs('admin.refunds.*') ? 'bg-emerald-800 text-white font-bold' : 'text-emerald-100/70 hover:bg-emerald-900/40 hover:text-white' }}"><span>⚠️</span><span>Incidencias y Reembolsos</span></a></div></section>
<section><p class="mb-1.5 px-2.5 text-[10px] font-bold uppercase tracking-wider text-emerald-400/80">Configuración</p><div class="space-y-0.5"><a href="{{ route('admin.users.index') }}" class="flex items-center space-x-2.5 rounded-lg px-2.5 py-1.5 transition {{ request()->routeIs('admin.users.*') ? 'bg-emerald-800 text-white font-bold' : 'text-emerald-100/70 hover:bg-emerald-900/40 hover:text-white' }}"><span>👥</span><span>Usuarios y Permisos</span></a><a href="{{ route('admin.settings.index') }}" class="flex items-center space-x-2.5 rounded-lg px-2.5 py-1.5 transition {{ request()->routeIs('admin.settings.*') ? 'bg-emerald-800 text-white font-bold' : 'text-emerald-100/70 hover:bg-emerald-900/40 hover:text-white' }}"><span>⚙️</span><span>Integraciones y Ajustes</span></a></div></section>
</div>@else<section class="ny-group"><p class="ny-category blue">Principal</p><a class="ny-link {{ request()->routeIs($isCounter?'company.counter.*':'dashboard') ? 'active' : '' }}" href="{{ $isCounter?route('company.counter.index'):route('dashboard') }}"><span class="ny-icon"><x-nav-icon name="dashboard"/></span>{{$isCounter?'Despacho de hoy':'Dashboard'}}</a>@if($isCompanyAdmin)<a class="ny-link {{ request()->routeIs('company.dashboard*') ? 'active' : '' }}" href="{{ route('company.dashboard') }}"><span class="ny-icon"><x-nav-icon name="building"/></span>Mi empresa</a>@endif</section>
@if($can('companies')||$can('ports')||$can('routes')||$can('fleet'))<section class="ny-group"><p class="ny-category green">Operación</p>
@if($can('companies'))<a class="ny-link {{ request()->routeIs('admin.organizations.*') ? 'active' : '' }}" href="{{ route('admin.organizations.index') }}"><span class="ny-icon"><x-nav-icon name="building"/></span>Solicitudes de empresas</a><a class="ny-link {{ request()->routeIs('admin.organization-directory.*') ? 'active' : '' }}" href="{{ route('admin.organization-directory.index') }}"><span class="ny-icon"><x-nav-icon name="handshake"/></span>Empresas y agencias</a>@endif
<p class="ny-category green" style="margin-top:18px">Fluvial</p>@if($can('fleet'))<a class="ny-link {{ request()->routeIs('admin.vessels.*') ? 'active' : '' }}" href="{{ route('admin.vessels.index') }}"><span class="ny-icon"><x-nav-icon name="boat"/></span>Embarcaciones fluviales</a>@endif
@if($can('ports'))<a class="ny-link {{ request()->routeIs('admin.ports.*') ? 'active' : '' }}" href="{{ route('admin.ports.index') }}"><span class="ny-icon"><x-nav-icon name="pin"/></span>Puertos de embarque</a>@endif
@if($can('routes'))<a class="ny-link {{ request()->routeIs('admin.transport-routes.*') ? 'active' : '' }}" href="{{ route('admin.transport-routes.index') }}"><span class="ny-icon"><x-nav-icon name="route"/></span>Rutas y salidas</a>@endif <p class="ny-category blue" style="margin-top:18px">Aéreo</p>@if($can('fleet'))<a class="ny-link {{ request()->routeIs('admin.aircraft.*') ? 'active' : '' }}" href="{{ route('admin.aircraft.index') }}"><span class="ny-icon">✈</span>Aeronaves</a><a class="ny-link {{ request()->routeIs('admin.air-routes.*') ? 'active' : '' }}" href="{{ route('admin.air-routes.index') }}"><span class="ny-icon">↗</span>Rutas y salidas aéreas</a>@endif
</section>@endif
@if($can('cargo')||$can('boarding')||$can('reports'))<section class="ny-group"><p class="ny-category gold">Ventas</p>@if($can('cargo'))<a class="ny-link {{ request()->routeIs('admin.cargo.*') ? 'active' : '' }}" href="{{ route('admin.cargo.index') }}"><span class="ny-icon"><x-nav-icon name="cargo"/></span>Carga</a>@endif
@if(!$isSuper && $can('boarding'))<a class="ny-link {{ request()->routeIs('admin.boarding.*') ? 'active' : '' }}" href="{{ route('admin.boarding.index') }}"><span class="ny-icon"><x-nav-icon name="ticket"/></span>Control de embarque</a>@endif
@if($can('reports'))<a class="ny-link {{ request()->routeIs('admin.reports.*') ? 'active' : '' }}" href="{{ route('admin.reports.index') }}"><span class="ny-icon"><x-nav-icon name="chart"/></span>Reportes</a>@endif</section>@endif
@if($can('ads'))<section class="ny-group"><p class="ny-category violet">Contenido</p><a class="ny-link {{ request()->routeIs('admin.ads.*') ? 'active' : '' }}" href="{{ route('admin.ads.index') }}"><span class="ny-icon"><x-nav-icon name="megaphone"/></span>Publicidad y campañas</a><a class="ny-link {{ request()->routeIs('admin.destinations.*') ? 'active' : '' }}" href="{{ route('admin.destinations.index') }}"><span class="ny-icon"><x-nav-icon name="leaf"/></span>Ciudades y destinos</a><a class="ny-link {{ request()->routeIs('admin.destination-listings.*') && request()->route('type') === 'attraction' ? 'active' : '' }}" href="{{ route('admin.destination-listings.index','attraction') }}"><span class="ny-icon"><x-nav-icon name="pin"/></span>Lugares turísticos</a><a class="ny-link {{ request()->routeIs('admin.destination-listings.*') && request()->route('type') === 'lodging' ? 'active' : '' }}" href="{{ route('admin.destination-listings.index','lodging') }}"><span class="ny-icon"><x-nav-icon name="building"/></span>Hoteles y hospedajes</a><a class="ny-link {{ request()->routeIs('admin.destination-listings.*') && request()->route('type') === 'gastronomy' ? 'active' : '' }}" href="{{ route('admin.destination-listings.index','gastronomy') }}"><span class="ny-icon"><x-nav-icon name="cargo"/></span>Gastronomía</a></section>@endif
@if($can('users')||$can('audit')||$can('settings'))<section class="ny-group"><p class="ny-category rose">Sistema</p>@if($can('users'))<a class="ny-link {{ request()->routeIs('admin.users.*') ? 'active' : '' }}" href="{{ route('admin.users.index') }}"><span class="ny-icon"><x-nav-icon name="users"/></span>Usuarios y permisos</a>@endif
@if($can('audit'))<a class="ny-link {{ request()->routeIs('admin.audit.*') ? 'active' : '' }}" href="{{ route('admin.audit.index') }}"><span class="ny-icon"><x-nav-icon name="shield"/></span>Auditoría y seguridad</a>@endif
@if($can('settings'))<a class="ny-link {{ request()->routeIs('admin.navigation.*') ? 'active' : '' }}" href="{{ route('admin.navigation.index') }}"><span class="ny-icon">☰</span>Menú y páginas</a><a class="ny-link {{ request()->routeIs('admin.settings.*') ? 'active' : '' }}" href="{{ route('admin.settings.index') }}"><span class="ny-icon"><x-nav-icon name="settings"/></span>Configuración</a>@endif</section>@endif
@endif
</nav></aside>
