@php($supportNumber=preg_replace('/\D/','',\App\Models\SystemSetting::value('whatsapp_number','51900000000')))
<footer class="w-full border-t border-emerald-900/60 bg-[#07241b] pb-8 pt-12 text-slate-300"><div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div class="grid grid-cols-1 gap-8 border-b border-emerald-900/50 pb-10 md:grid-cols-2 lg:grid-cols-4">
 <div class="space-y-3"><div class="flex items-center gap-2"><span class="text-xl">🚤</span><span class="text-lg font-bold text-white">NavegaYA</span></div><p class="text-xs leading-relaxed text-emerald-100/70">Plataforma digital de pasajes fluviales y aéreos en la Amazonía peruana. Compra segura y confirmación inmediata.</p><a href="https://wa.me/{{$supportNumber}}" target="_blank" class="inline-flex items-center gap-2 rounded-lg border border-emerald-700/50 bg-emerald-900/60 px-3 py-1.5 text-xs text-emerald-200">💬 Ayuda por WhatsApp</a></div>
 <div><h4 class="mb-3 text-xs font-bold uppercase tracking-wider text-amber-400">Rutas populares</h4><ul class="space-y-2 text-xs text-emerald-100/80"><li><a href="{{route('routes.index',['origin'=>'Iquitos','destination'=>'Nauta'])}}">Iquitos ➔ Nauta</a></li><li><a href="{{route('routes.index',['origin'=>'Nauta','destination'=>'Yurimaguas'])}}">Nauta ➔ Yurimaguas</a></li><li><a href="{{route('routes.index',['origin'=>'Iquitos','destination'=>'Santa Rosa'])}}">Iquitos ➔ Santa Rosa</a></li></ul></div>
 <div><h4 class="mb-3 text-xs font-bold uppercase tracking-wider text-amber-400">Servicios</h4><ul class="space-y-2 text-xs text-emerald-100/80"><li><a href="{{route('travels.index')}}">Consultar o descargar boleto</a></li><li><a href="{{route('ports.public')}}">Puertos y embarcaderos</a></li><li><a href="{{route('guide.index')}}">Guía comercial de Loreto</a></li><li><a href="{{route('company.registration')}}">Afiliar empresa</a></li></ul></div>
 <div><h4 class="mb-3 text-xs font-bold uppercase tracking-wider text-amber-400">Atención y confianza</h4><ul class="space-y-2 text-xs text-emerald-100/80"><li><a href="{{route('about')}}">Quiénes somos</a></li><li><a href="{{route('pages.show','terminos')}}">Términos y condiciones</a></li><li><a href="{{route('pages.show','privacidad')}}">Privacidad</a></li></ul><div class="mt-4 border-t border-emerald-900/40 pt-3 text-[11px] text-emerald-200/60">🔒 Pagos procesados de forma segura.</div></div>
 </div><div class="flex flex-col items-center justify-between gap-3 pt-6 text-[11px] text-emerald-100/60 sm:flex-row"><p>© {{now()->year}} NavegaYA. Conectando los ríos y cielos de Loreto.</p><p>Rápido • Seguro • Oficial</p></div></div></footer>



