<header class="sticky top-0 z-50 w-full border-b border-emerald-900/60 bg-[#062c21] px-4 py-3 text-white shadow-md sm:px-6 lg:px-8" x-data="{open:false}">
<div class="mx-auto flex max-w-7xl items-center justify-between gap-5">
<a href="{{route('home')}}" class="flex shrink-0 items-center gap-2"><div class="flex h-8 max-h-[32px] w-8 max-w-[32px] shrink-0 items-center justify-center overflow-hidden"><svg width="32" height="32" class="h-8 max-h-[32px] w-8 max-w-[32px]" viewBox="0 0 32 32" fill="none" aria-hidden="true"><rect x="1" y="1" width="30" height="30" rx="9" fill="white" fill-opacity=".12"/><path d="M7 19.5 10 24h12l3-4.5-2.2-7.5H9.2L7 19.5Z" stroke="white" stroke-width="2" stroke-linejoin="round"/><path d="M12 12V8h8v4M16 8V5.5" stroke="#FBBF24" stroke-width="2" stroke-linecap="round"/></svg></div><span class="text-lg font-extrabold tracking-tight text-white">Navega<span class="text-amber-400">YA</span></span></a>
<nav class="hidden items-center gap-6 text-xs md:flex">
<a href="{{route('routes.index')}}" class="pb-0.5 transition-colors {{request()->routeIs('routes.*')?'border-b-2 border-amber-400 font-bold text-amber-400':'font-medium text-emerald-100/80 hover:text-white'}}">Rutas y horarios</a>
<a href="{{route('companies.index')}}" class="pb-0.5 transition-colors {{request()->routeIs('companies.*')?'border-b-2 border-amber-400 font-bold text-amber-400':'font-medium text-emerald-100/80 hover:text-white'}}">Empresas</a>
<a href="{{route('ports.public')}}" class="pb-0.5 transition-colors {{request()->routeIs('ports.*')?'border-b-2 border-amber-400 font-bold text-amber-400':'font-medium text-emerald-100/80 hover:text-white'}}">Puertos y muelles</a>
<a href="{{route('guide.index')}}" class="pb-0.5 transition-colors {{request()->routeIs('guide.*')?'border-b-2 border-amber-400 font-bold text-amber-400':'font-medium text-emerald-100/80 hover:text-white'}}">Guía Loreto</a>
<a href="{{route('travels.index')}}" class="pb-0.5 transition-colors {{request()->routeIs('travels.*')?'border-b-2 border-amber-400 font-bold text-amber-400':'font-medium text-emerald-100/80 hover:text-white'}}">Consultar pasaje</a>
<a href="{{route('company.registration')}}" class="rounded-full px-3.5 py-1.5 text-xs font-semibold transition-all duration-150 {{request()->routeIs('company.registration*')?'border-2 border-amber-400 bg-white/10 font-bold text-amber-300 shadow-sm':'border border-emerald-900/60 text-emerald-100 hover:border-emerald-400 hover:text-white'}}">Afiliar empresa</a>
</nav>
<div class="flex items-center gap-2">@auth<a href="{{route('dashboard')}}" class="hidden rounded-xl bg-amber-400 px-4 py-2 text-sm font-bold text-emerald-950 sm:inline-flex">Mi cuenta</a>@else<a href="{{route('login')}}" class="hidden rounded-xl border border-white/25 px-4 py-2 text-sm font-semibold text-white sm:inline-flex">Ingresar</a>@endauth<button type="button" class="grid h-10 w-10 place-items-center rounded-xl border border-white/20 md:hidden" @click="open=!open" aria-label="Abrir menú"><svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path stroke-linecap="round" d="M4 7h16M4 12h16M4 17h16"/></svg></button></div>
</div><nav x-show="open" x-cloak class="mx-auto mt-3 grid max-w-7xl gap-1 border-t border-white/10 pt-3 md:hidden"><a href="{{route('routes.index')}}" class="rounded-lg px-3 py-2 text-sm">Rutas y horarios</a><a href="{{route('companies.index')}}" class="rounded-lg px-3 py-2 text-sm">Empresas</a><a href="{{route('ports.public')}}" class="rounded-lg px-3 py-2 text-sm">Puertos y muelles</a><a href="{{route('guide.index')}}" class="rounded-lg px-3 py-2 text-sm">Guía Loreto</a><a href="{{route('travels.index')}}" class="rounded-lg px-3 py-2 text-sm">Consultar pasaje</a><a href="{{route('company.registration')}}" class="rounded-lg px-3 py-2 text-sm text-amber-300">Afiliar empresa</a></nav>
</header>
