<x-app-layout>
<x-slot name="header"><h2 class="ny-page-title">Plano de asientos aéreo</h2></x-slot>
<style>
.ap{max-width:1120px;margin:auto;color:#173b33}.back{color:#126b88;font-weight:850;text-decoration:none}.hero{display:flex;justify-content:space-between;align-items:center;gap:20px;margin-top:15px;padding:27px 30px;border-radius:22px;background:linear-gradient(120deg,#123f64,#167da2);color:#fff}.hero small{color:#92dcf4;font-weight:900;letter-spacing:.14em}.hero h1{margin:6px 0;font-size:30px}.hero p{margin:0;color:#dceff7}.hero b{font-size:24px}.body{display:grid;grid-template-columns:330px minmax(0,1fr);gap:22px;margin-top:20px}.card{padding:24px;border:1px solid #d8e8ee;border-radius:20px;background:#fff;box-shadow:0 10px 30px #145b7810}.card h2{margin:0;color:#164d63;font-size:19px}.card p{color:#687f88;font-size:13px;line-height:1.5}.form label{display:block;margin-top:14px;color:#345866;font-size:12px;font-weight:850}.form input{width:100%;margin-top:6px;padding:11px;border:1px solid #c6dce5;border-radius:10px;background:#fafdff}.form button{width:100%;margin-top:18px;padding:12px;border:0;border-radius:11px;background:#146f91;color:#fff;font-weight:850}.ok{padding:11px;border-radius:10px;background:#e6f6fb;color:#096686}
.stage{overflow:auto;margin-top:16px;padding:55px 16px 34px;border:1px solid #d8edf5;border-radius:18px;background:radial-gradient(circle at 50% 5%,#dff4fc,#f5fbfe 62%,#fff)}.plane{position:relative;width:var(--plane-width);min-height:var(--plane-height);margin:auto;padding:80px 38px 70px;border:2px solid #72b8d1;border-radius:48% 48% 36% 36% / 11% 11% 8% 8%;background:linear-gradient(90deg,#e2f4fa,#fff 14%,#fff 86%,#e2f4fa);box-shadow:0 22px 42px #145b7826,inset 0 0 0 8px #f2fafd}.plane:before{content:"";position:absolute;z-index:0;top:42%;left:50%;transform:translate(-50%,-50%);width:calc(100% + 230px);height:90px;border:2px solid #72b8d1;border-radius:65% 65% 25% 25%;background:#e6f5fa;box-shadow:0 12px 24px #145b7817}.plane:after{content:"";position:absolute;left:50%;bottom:-32px;transform:translateX(-50%);width:85px;height:72px;border:2px solid #72b8d1;border-radius:15% 15% 65% 65%;background:#e1f2f8}.cockpit,.cabin{position:relative;z-index:2}.cockpit{position:absolute;top:22px;left:50%;transform:translateX(-50%);width:64%;padding:11px;border:1px solid #b5dce9;border-radius:50% 50% 12px 12px;background:#dff2f9;color:#245e74;text-align:center;font-size:9px;font-weight:900;letter-spacing:.11em}.cabin{padding:16px;border:1px solid #cce5ef;border-radius:25px;background:#fafdffff}.cabin:before{content:"PASILLO";position:absolute;top:50%;left:50%;transform:translate(-50%,-50%) rotate(-90deg);padding:4px 7px;border-radius:99px;background:#fff;color:#7da0ae;font-size:7px;font-weight:900;letter-spacing:.1em;box-shadow:0 0 0 1px #dcecf2}.row{position:relative;z-index:2;display:grid;align-items:center;gap:7px;margin:8px 0}.rowno{font-size:9px;font-weight:900;color:#7093a1;text-align:center}.aisle{width:23px}.seat{display:grid;place-items:center;width:40px;height:38px;border:1px solid #86c7de;border-radius:12px 12px 8px 8px;background:linear-gradient(#dff5fc,#c9ebf7);color:#075f82;font-size:11px;font-weight:900;box-shadow:0 3px 0 #8dc8dc}.nose,.tail{position:absolute;z-index:3;left:50%;transform:translateX(-50%);font-size:8px;font-weight:900;letter-spacing:.14em;color:#0d6687}.nose{top:-26px}.tail{bottom:20px}.empty{padding:65px 20px;text-align:center;color:#6d838b}.empty i{display:block;font-size:45px;font-style:normal}.legend{display:flex;gap:14px;margin-top:14px;color:#667d86;font-size:11px}
@media(max-width:850px){.body{grid-template-columns:1fr}}@media(max-width:600px){.hero{display:block}.hero b{display:block;margin-top:14px}.card{padding:16px}.stage{margin-left:-8px;margin-right:-8px}}
</style>
<div class="ap"><a class="back" href="{{route('admin.aircraft.index')}}">← Volver a aeronaves</a>
<section class="hero"><div><small>CONFIGURACIÓN DE AERONAVE</small><h1>{{$aircraft->name}}</h1><p>{{$aircraft->model}} · Matrícula {{$aircraft->registration_number}}</p></div><b>{{$aircraft->seats->count()}} / {{$aircraft->seat_capacity}} asientos</b></section>
<div class="body"><section class="card"><h2>Distribución de pasajeros</h2><p>Define filas y asientos por fila. El sistema dibujará automáticamente el pasillo central.</p>@if(session('success'))<p class="ok">✓ {{session('success')}}</p>@endif
<form class="form" method="POST" action="{{route('admin.aircraft.seats.generate',$aircraft)}}">@csrf<label>Filas<input type="number" name="rows" min="1" max="60" required value="{{max(1,$aircraft->seats->max('row_position')?:8)}}"></label><label>Asientos por fila<input type="number" name="columns" min="1" max="8" required value="{{max(1,$aircraft->seats->where('row_position',1)->count()?:4)}}"></label><label>Clase o cabina<input name="cabin" value="{{$aircraft->seats->first()?->cabin?:'Económica'}}"></label><button>Generar plano del avión</button></form></section>
<section class="card"><h2>Vista de cabina</h2><p>Solo se muestran los asientos destinados a pasajeros.</p>
@php($allSeats=$aircraft->seats()->orderBy('row_position')->orderBy('column_position')->get())
@if($allSeats->isNotEmpty()) @php($cols=$allSeats->max('column_position')) @php($middle=(int)ceil($cols/2)) @php($rows=$allSeats->max('row_position'))
<div class="stage"><div class="plane" style="--plane-width:{{max(330,100+($cols*47)+23)}}px;--plane-height:{{max(360,180+($rows*46))}}px"><span class="nose">NARIZ</span><div class="cockpit">◉ CABINA DE PILOTOS</div><div class="cabin">
@foreach($allSeats->groupBy('row_position') as $row=>$rowSeats)<div class="row" style="grid-template-columns:26px repeat({{$middle}},40px) 23px repeat({{$cols-$middle}},40px)"><span class="rowno">{{str_pad($row,2,'0',STR_PAD_LEFT)}}</span>
@for($col=1;$col<=$cols;$col++) @php($seat=$rowSeats->firstWhere('column_position',$col)) @if($seat)<span class="seat">{{$seat->code}}</span>@endif @if($col===$middle)<span class="aisle"></span>@endif @endfor
</div>@endforeach</div><span class="tail">COLA</span></div></div>
<div class="legend"><span>Azul: asiento de viajero</span><span>El pasillo no es seleccionable</span></div>
@else<div class="empty"><i>✈</i><strong>Aún no hay asientos</strong><br>Define la distribución desde el panel izquierdo.</div>@endif
</section></div></div>
</x-app-layout>
