<x-public-layout title="Guía de Loreto: hospedajes, gastronomía y experiencias · NavegaYA">
@php
    $support = preg_replace('/\D/', '', \App\Models\SystemSetting::value('whatsapp_number', '51900000000'));
@endphp
<div class="min-h-screen bg-slate-50 pb-20"><div class="mx-auto max-w-7xl px-4 pt-4 sm:px-6 lg:px-8">
<x-amazon-hero-bg theme="guide" class="rounded-3xl text-center shadow-2xl md:rounded-[2.5rem]" overlay="from-slate-950/95 via-[#062c21]/82 to-slate-900/50"><div class="mx-auto max-w-3xl px-2 pb-16 pt-6"><span class="inline-flex rounded-full border border-emerald-400/30 bg-emerald-950/70 px-3 py-1 text-[11px] font-bold uppercase tracking-wider text-emerald-200 shadow-inner">Explora la Selva Peruana</span><h1 class="mt-3 text-3xl font-extrabold leading-tight tracking-tight text-white sm:text-4xl md:text-5xl">Guía de Destinos y Turismo en Loreto</h1><p class="mx-auto mt-3 max-w-2xl text-xs leading-relaxed text-emerald-100/80 sm:text-sm md:text-base">Descubre qué hacer, dónde hospedarte y cómo moverte en los ríos y reservas amazónicas.</p></div></x-amazon-hero-bg>
<section class="relative z-20 mx-auto -mt-4 max-w-5xl px-2 sm:px-4"><div class="flex flex-wrap items-center justify-between gap-3 rounded-2xl border border-slate-100 bg-white p-4 shadow-xl shadow-slate-900/10"><nav class="flex flex-wrap items-center gap-2 text-xs"><a href="{{route('guide.index',array_filter(['ciudad'=>$cityId]))}}" class="rounded-xl px-4 py-2 font-bold transition {{$type===null?'bg-slate-900 text-white shadow-sm':'bg-slate-100 text-slate-700 hover:bg-slate-200'}}">Todos</a><a href="{{route('guide.index',array_filter(['ciudad'=>$cityId,'tipo'=>'lodging']))}}" class="rounded-xl px-4 py-2 font-semibold transition {{$type==='lodging'?'bg-emerald-800 text-white':'bg-slate-100 text-slate-700 hover:bg-slate-200'}}">🏨 Hoteles, lodges y Airbnb</a><a href="{{route('guide.index',array_filter(['ciudad'=>$cityId,'tipo'=>'gastronomy']))}}" class="rounded-xl px-4 py-2 font-semibold transition {{$type==='gastronomy'?'bg-emerald-800 text-white':'bg-slate-100 text-slate-700 hover:bg-slate-200'}}">🍽️ Gastronomía</a><a href="{{route('guide.index',array_filter(['ciudad'=>$cityId,'tipo'=>'attraction']))}}" class="rounded-xl px-4 py-2 font-semibold transition {{$type==='attraction'?'bg-emerald-800 text-white':'bg-slate-100 text-slate-700 hover:bg-slate-200'}}">🧭 Tours y expediciones</a></nav><form method="GET"><input type="hidden" name="tipo" value="{{$type}}"><select name="ciudad" onchange="this.form.submit()" class="cursor-pointer rounded-xl border border-slate-200 bg-slate-50 px-3 py-2 text-xs font-semibold text-slate-700 focus:ring-2 focus:ring-emerald-600"><option value="">Todas las localidades</option>@foreach($cities as $city)<option value="{{$city->id}}" @selected($cityId===$city->id)>{{$city->name}}</option>@endforeach</select></form></div></section>
<section class="mt-12"><div class="grid gap-6 md:grid-cols-2 lg:grid-cols-3">
<article class="group relative flex flex-col justify-between overflow-hidden rounded-3xl border border-emerald-800 p-7 text-white shadow-xl" style="background:linear-gradient(145deg,#064e3b 0%,#062c21 55%,#0f513f 100%);color:#fff"><div class="pointer-events-none absolute -bottom-8 -right-8 h-32 w-32 rounded-full blur-2xl" style="background:rgba(251,191,36,.12)"></div><div class="relative"><span class="inline-flex rounded-full border border-amber-400/30 px-3 py-1 text-[10px] font-extrabold uppercase tracking-wider text-amber-300" style="background:rgba(251,191,36,.14)">📢 Espacio publicitario</span><h2 class="mt-4 text-xl font-extrabold leading-tight text-white">¿Tienes un hotel, lodge, Airbnb, restaurante o tour?</h2><p class="mt-2.5 text-xs leading-relaxed" style="color:#d1fae5">Llega a viajeros que ya están comprando pasajes y organizando su visita a Loreto.</p><ul class="mt-4 space-y-2 text-xs font-medium" style="color:#a7f3d0"><li>✓ Contacto directo a tu WhatsApp</li><li>✓ Posición destacada en el directorio</li><li>✓ Estadísticas de vistas y contactos</li></ul></div><a href="https://wa.me/{{$support}}?text={{urlencode('Hola, deseo publicitar mi negocio en la guía de NavegaYA')}}" target="_blank" rel="noopener" class="relative mt-6 flex h-11 items-center justify-center gap-2 rounded-xl bg-amber-500 text-xs font-bold text-slate-950 shadow-sm transition hover:bg-amber-600">🚀 Anunciar mi negocio aquí</a></article>
@foreach($ads as $ad)<a href="{{route('discover.ad',$ad)}}" target="_blank" rel="sponsored noopener" class="group flex flex-col justify-between overflow-hidden rounded-3xl border border-amber-200 bg-white shadow-sm transition hover:shadow-xl"><div>@if($ad->image_url)<div class="relative h-48 overflow-hidden"><img src="{{$ad->image_url}}" alt="{{$ad->business_name}}" class="h-full w-full object-cover transition duration-300 group-hover:scale-105"><span class="absolute right-3 top-3 rounded-full bg-amber-400 px-2.5 py-1 text-[10px] font-extrabold text-slate-950">⭐ Patrocinado</span></div>@endif<div class="p-5"><span class="text-[10px] font-bold uppercase tracking-wide text-slate-400">{{$ad->city?->name??'Loreto'}} · {{$ad->category}}</span><h2 class="mt-1 text-base font-extrabold text-slate-900 group-hover:text-emerald-800">{{$ad->title}}</h2><p class="mt-1.5 text-xs leading-relaxed text-slate-500">{{$ad->description}}</p></div></div><div class="px-5 pb-5"><span class="flex w-full items-center justify-center rounded-xl border border-amber-200 bg-amber-50 py-2.5 text-xs font-bold text-amber-900">Conocer promoción →</span></div></a>@endforeach
@forelse($listings as $listing)
@php
    $image = $listing->images->first()?->path;
    $imageUrl = $image ? (str_starts_with($image, 'http') ? $image : (str_starts_with($image, '/') ? asset(ltrim($image, '/')) : asset('storage/'.$image))) : null;
    $icon = match ($listing->type) { 'lodging' => '🏨', 'gastronomy' => '🍽️', default => '🧭' };
    $label = match ($listing->type) { 'lodging' => 'Hotel / lodge / Airbnb', 'gastronomy' => 'Gastronomía', default => 'Tour / experiencia' };
@endphp
<article class="group flex flex-col justify-between overflow-hidden rounded-3xl border border-slate-200/80 bg-white shadow-sm transition duration-200 hover:shadow-xl"><div><div class="relative h-48 overflow-hidden bg-gradient-to-br from-emerald-100 to-sky-100">@if($imageUrl)<img src="{{$imageUrl}}" alt="{{$listing->name}}" class="h-full w-full object-cover transition duration-300 group-hover:scale-105">@else<div class="grid h-full place-items-center text-5xl">{{$icon}}</div>@endif<span class="absolute left-3 top-3 rounded-full bg-emerald-950/80 px-2.5 py-1 text-[10px] font-bold uppercase tracking-wider text-white backdrop-blur-sm">{{$label}}</span>@if($listing->is_featured)<span class="absolute right-3 top-3 rounded-full bg-amber-400 px-2.5 py-1 text-[10px] font-extrabold text-slate-950">Destacado</span>@endif</div><div class="p-5"><span class="text-[10px] font-bold uppercase tracking-wide text-slate-400">{{$listing->city->name}}{{$listing->category?' · '.$listing->category:''}}</span><h2 class="mt-1 text-base font-extrabold text-slate-900 transition group-hover:text-emerald-800">{{$listing->name}}</h2><p class="mt-1.5 text-xs leading-relaxed text-slate-500">{{$listing->description?:'Consulta información y disponibilidad directamente con el establecimiento.'}}</p><div class="mt-4 flex flex-wrap gap-1.5 text-[10px] font-medium text-slate-600">@if($listing->opening_hours)<span class="rounded-md bg-slate-100 px-2 py-0.5">🕒 {{$listing->opening_hours}}</span>@endif @if($listing->price_reference)<span class="rounded-md bg-slate-100 px-2 py-0.5">{{$listing->price_reference}}</span>@endif @if($listing->address)<span class="rounded-md bg-slate-100 px-2 py-0.5">📍 {{$listing->address}}</span>@endif</div></div></div><div class="flex gap-2 px-5 pb-5">@if($listing->contact_phone)<a href="https://wa.me/{{preg_replace('/\D/','',$listing->contact_phone)}}?text={{urlencode('Hola, vi su negocio en la guía de NavegaYA y deseo información')}}" target="_blank" rel="noopener" class="flex-1 rounded-xl border border-emerald-200 bg-emerald-50 py-2.5 text-center text-xs font-bold text-emerald-800 hover:bg-emerald-100">💬 WhatsApp</a>@endif @if($listing->website_url)<a href="{{$listing->website_url}}" target="_blank" rel="noopener" class="rounded-xl border border-slate-200 px-3 py-2.5 text-xs font-bold text-slate-700">Sitio web</a>@endif</div></article>
@empty
@if($ads->isEmpty())<div class="rounded-3xl border border-dashed border-slate-300 bg-white p-12 text-center md:col-span-2"><div class="text-4xl">🌿</div><h2 class="mt-3 text-sm font-bold text-slate-800">Pronto agregaremos más servicios</h2><p class="mt-1 text-xs text-slate-500">Prueba con otra localidad o categoría.</p></div>@endif
@endforelse
</div><div class="mt-8">{{$listings->links()}}</div></section>
</div></div>
</x-public-layout>


