<x-app-layout>
<x-slot name="header"><h2 class="ny-page-title">Registrar carga</h2></x-slot>
<style>
.ny-cargo-form{max-width:1000px;margin:auto}.ny-cargo-intro{padding:28px 30px;border-radius:20px;background:linear-gradient(118deg,#103a31,#176d60);color:#fff}.ny-cargo-intro h1{margin:6px 0;font-size:28px}.ny-cargo-intro p{margin:0;color:#d8eee7}.ny-cargo-card{margin-top:20px;padding:30px;border:1px solid #dce8e3;border-radius:20px;background:#fff;box-shadow:0 12px 34px #12372d0c}.ny-cargo-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:17px}.ny-cargo-field{display:block;color:#193d34;font-size:13px;font-weight:800}.ny-cargo-field input,.ny-cargo-field select,.ny-cargo-field textarea{box-sizing:border-box;display:block;width:100%;margin-top:7px;border:1px solid #cbdad4;border-radius:10px;padding:12px;background:#fbfdfc;color:#153b32;font:inherit;font-weight:500}.ny-cargo-field textarea{min-height:112px;resize:vertical}.ny-cargo-field.full{grid-column:1/-1}.ny-cargo-help{margin:0 0 22px;padding:12px 14px;border-radius:10px;background:#fff8df;color:#755205;font-size:13px;line-height:1.5}.ny-cargo-link{grid-column:1/-1;padding:18px;border:1px solid #bfe2d4;border-radius:14px;background:#f1faf6}.ny-cargo-link strong{display:block;color:#125847;font-size:15px}.ny-cargo-link small{display:block;color:#647d74;margin:4px 0 10px}.ny-cargo-actions{display:flex;justify-content:flex-end;gap:12px;margin-top:25px}.ny-cargo-actions a,.ny-cargo-actions button{border:0;border-radius:10px;padding:12px 18px;text-decoration:none;font-weight:800;cursor:pointer}.ny-cargo-actions a{color:#31554b;background:#eef5f2}.ny-cargo-actions button{color:#153b32;background:#eab634}@media(max-width:720px){.ny-cargo-grid{grid-template-columns:1fr}.ny-cargo-card{padding:20px}}
</style>
<div class="ny-cargo-form"><section class="ny-cargo-intro"><p style="font-size:11px;font-weight:800;letter-spacing:.13em;color:#f7d36a">CARGA EN TERMINAL</p><h1>Recepción de carga</h1><p>Registra una carga comercial o el exceso de equipaje de un viajero. El pesaje y cobro se confirman en el terminal.</p></section>
<form method="POST" action="{{ route('admin.cargo.store') }}" class="ny-cargo-card">@csrf
<p class="ny-cargo-help">Vincular a un viajero es opcional. Úsalo cuando el paquete corresponde a un pasajero con boleto; la carga comercial puede registrarse sin vínculo.</p>
<div class="ny-cargo-grid">
<label class="ny-cargo-field">Medio de transporte *<select name="transport_mode" id="cargoMode"><option value="fluvial" @selected(old('transport_mode','fluvial')==='fluvial')>Fluvial</option><option value="aereo" @selected(old('transport_mode')==='aereo')>Aéreo</option></select></label><div class="ny-cargo-field"><span style="display:block;margin-top:25px;color:#6d827b;font-weight:500">El registro, pesaje y cobro son únicos; solo cambia la salida asociada.</span></div>
<label class="ny-cargo-field full" id="fluvialDeparture">Salida fluvial *<select name="route_departure_id" id="routeDeparture"><option value="">Selecciona una salida fluvial</option>@foreach($departures as $d)<option value="{{ $d->id }}" @selected(old('route_departure_id') == $d->id)>{{ $d->transportRoute->originPort->city }} → {{ $d->transportRoute->destinationPort->city }} · {{ $d->departure_at->format('d/m/Y H:i') }}</option>@endforeach</select></label>
<label class="ny-cargo-field full" id="airDeparture">Salida aérea *<select name="air_departure_id"><option value="">Selecciona una salida aérea</option>@foreach($airDepartures as $d)<option value="{{ $d->id }}" @selected(old('air_departure_id') == $d->id)>{{ $d->airRoute->origin_city }} → {{ $d->airRoute->destination_city }} · {{ $d->departure_at->format('d/m/Y H:i') }} · {{ $d->aircraft->name }}</option>@endforeach</select></label>
<section class="ny-cargo-link" id="passengerLink"><strong>¿La carga pertenece a un viajero?</strong><small>Ingresa su DNI o documento y búscalo en la salida fluvial seleccionada. Si no existe un boleto confirmado, registra la carga normalmente.</small><div style="display:flex;gap:9px"><input id="passengerDocument" placeholder="DNI o documento del pasajero" style="margin:0"><button type="button" id="lookupPassenger" style="border:0;border-radius:10px;padding:10px 14px;background:#176d60;color:white;font-weight:800;cursor:pointer">Buscar</button></div><input type="hidden" name="reservation_seat_id" id="passengerSeat"><p id="passengerResult" style="margin:10px 0 0;font-size:13px;color:#647d74"></p></section>
<label class="ny-cargo-field">Remitente *<input id="senderName" name="sender_name" required value="{{ old('sender_name') }}" placeholder="Nombre completo o empresa"></label><label class="ny-cargo-field">Documento del remitente<input id="senderDocument" name="sender_document" value="{{ old('sender_document') }}" placeholder="DNI, RUC o CE"></label><label class="ny-cargo-field">Teléfono del remitente *<input id="senderPhone" name="sender_phone" required value="{{ old('sender_phone') }}" placeholder="Ej. 999 999 999"></label>
<label class="ny-cargo-field">Destinatario *<input name="recipient_name" required value="{{ old('recipient_name') }}" placeholder="Nombre completo o empresa"></label><label class="ny-cargo-field">Documento del destinatario<input name="recipient_document" value="{{ old('recipient_document') }}" placeholder="DNI, RUC o CE"></label><label class="ny-cargo-field">Teléfono del destinatario<input name="recipient_phone" value="{{ old('recipient_phone') }}" placeholder="Ej. 999 999 999"></label>
<label class="ny-cargo-field full">Descripción de la carga *<textarea name="description" required placeholder="Ej. Equipaje adicional, caja con repuestos, productos no perecibles…">{{ old('description') }}</textarea></label><label class="ny-cargo-field">Número de bultos *<input type="number" name="package_count" min="1" required value="{{ old('package_count',1) }}"></label><label class="ny-cargo-field">Peso declarado (kg) *<input type="number" step=".01" name="declared_weight_kg" min=".01" required value="{{ old('declared_weight_kg') }}" placeholder="0.00"></label></div>
<div class="ny-cargo-actions"><a href="{{ route('admin.cargo.index') }}">Cancelar</a><button type="submit">Registrar carga →</button></div></form></div>
<script>
const cargoMode=document.getElementById('cargoMode'), fluvial=document.getElementById('fluvialDeparture'), air=document.getElementById('airDeparture'), passengerLink=document.getElementById('passengerLink'), routeDeparture=document.getElementById('routeDeparture'), passengerDocument=document.getElementById('passengerDocument'), passengerSeat=document.getElementById('passengerSeat'), passengerResult=document.getElementById('passengerResult');
function resetPassenger(message='') { passengerSeat.value=''; passengerResult.textContent=message; passengerResult.style.color='#647d74'; }
function syncCargo(){const isAir=cargoMode.value==='aereo';fluvial.style.display=isAir?'none':'block';air.style.display=isAir?'block':'none';passengerLink.style.display=isAir?'none':'block';if(isAir) resetPassenger();}
async function lookupPassenger(){const documentNumber=passengerDocument.value.trim(), departure=routeDeparture.value;if(!departure){resetPassenger('Primero selecciona la salida fluvial.'); passengerResult.style.color='#a05c0c';return;}if(!documentNumber){resetPassenger('Ingresa el DNI o documento para buscar.'); passengerResult.style.color='#a05c0c';return;} passengerResult.textContent='Buscando pasajero…'; const url='{{ route('admin.cargo.passenger-lookup') }}?'+new URLSearchParams({document:documentNumber,route_departure_id:departure});try{const response=await fetch(url,{headers:{Accept:'application/json'}});const data=await response.json();if(!data.found){resetPassenger('No se encontró un boleto confirmado. Puedes continuar como carga sin pasajero vinculado.');return;}passengerSeat.value=data.seat_id;document.getElementById('senderName').value=data.passenger_name||'';document.getElementById('senderDocument').value=data.document||'';document.getElementById('senderPhone').value=data.phone||'';passengerResult.textContent='✓ Pasajero encontrado: '+data.passenger_name+' · Reserva '+data.reservation_code+' · '+data.route;passengerResult.style.color='#087057';}catch(error){resetPassenger('No se pudo realizar la búsqueda. Inténtalo nuevamente.');passengerResult.style.color='#b44747';}}
cargoMode.addEventListener('change',syncCargo);routeDeparture.addEventListener('change',()=>resetPassenger());document.getElementById('lookupPassenger').addEventListener('click',lookupPassenger);passengerDocument.addEventListener('keydown',(event)=>{if(event.key==='Enter'){event.preventDefault();lookupPassenger();}});syncCargo();
</script>
</x-app-layout>
