@extends('layouts.company')
@section('title','Mi flota')
@section('page-title','Mi Flota')
@section('content')
<div class="mx-auto max-w-7xl space-y-6" x-data="{form:null}">
<section class="flex flex-col justify-between gap-4 rounded-3xl bg-[#062c21] p-6 text-white sm:flex-row sm:items-center"><div><span class="text-[10px] font-bold uppercase tracking-wider text-emerald-300">Registro DICAPI / DGAC</span><h2 class="mt-1 text-2xl font-black">Flota autorizada</h2><p class="mt-1 text-xs text-emerald-100/70">Gestiona embarcaciones y aeronaves exclusivamente de tu empresa.</p></div><div class="flex gap-2"><button @click="form=form==='vessel'?null:'vessel'" class="rounded-xl bg-amber-500 px-4 py-2.5 text-xs font-black text-slate-950">＋ Embarcación</button><button @click="form=form==='aircraft'?null:'aircraft'" class="rounded-xl border border-white/20 px-4 py-2.5 text-xs font-bold">＋ Aeronave</button></div></section>
@if($errors->any())<div class="rounded-xl border border-rose-200 bg-rose-50 p-4 text-xs text-rose-700">{{ $errors->first() }}</div>@endif
<form x-show="form==='vessel'" x-cloak method="POST" action="{{ route('company.fleet.vessels.store') }}" class="grid gap-4 rounded-3xl border border-slate-200 bg-white p-6 shadow-sm sm:grid-cols-2 lg:grid-cols-5">@csrf<h3 class="font-black text-slate-900 sm:col-span-2 lg:col-span-5">Nueva embarcación</h3><input required name="name" placeholder="Nombre de nave" class="rounded-xl border-slate-200 text-sm"><input required name="registration_number" placeholder="Matrícula DICAPI" class="rounded-xl border-slate-200 text-sm"><select required name="vessel_type" class="rounded-xl border-slate-200 text-sm"><option value="rapido">Rápida</option><option value="lancha">Lancha</option><option value="motonave">Motonave</option><option value="ferry">Ferry</option></select><input required type="number" min="1" name="seat_capacity" placeholder="Asientos" class="rounded-xl border-slate-200 text-sm"><select name="base_port_id" class="rounded-xl border-slate-200 text-sm"><option value="">Puerto base</option>@foreach($ports as $port)<option value="{{ $port->id }}">{{ $port->city }} · {{ $port->name }}</option>@endforeach</select><button class="rounded-xl bg-[#062c21] px-4 py-3 text-xs font-black text-white lg:col-span-5">Registrar embarcación</button></form>
<form x-show="form==='aircraft'" x-cloak method="POST" action="{{ route('company.fleet.aircraft.store') }}" class="grid gap-4 rounded-3xl border border-slate-200 bg-white p-6 shadow-sm sm:grid-cols-2 lg:grid-cols-4">@csrf<h3 class="font-black text-slate-900 sm:col-span-2 lg:col-span-4">Nueva aeronave</h3><input required name="name" placeholder="Nombre comercial" class="rounded-xl border-slate-200 text-sm"><input required name="registration_number" placeholder="Matrícula DGAC" class="rounded-xl border-slate-200 text-sm"><input name="model" placeholder="Modelo" class="rounded-xl border-slate-200 text-sm"><input required type="number" min="1" name="seat_capacity" placeholder="Asientos" class="rounded-xl border-slate-200 text-sm"><button class="rounded-xl bg-sky-700 px-4 py-3 text-xs font-black text-white sm:col-span-2 lg:col-span-4">Registrar aeronave</button></form>
<section><div class="mb-3"><span class="text-[10px] font-bold uppercase tracking-wider text-emerald-700">DICAPI</span><h3 class="text-lg font-black text-slate-900">Embarcaciones</h3></div><div class="grid gap-4 md:grid-cols-2 xl:grid-cols-3">@forelse($vessels as $vessel)<article class="rounded-3xl border border-slate-200/90 bg-white p-5 shadow-sm"><div class="flex justify-between"><span class="grid h-11 w-11 place-items-center rounded-2xl bg-emerald-50">🚤</span><span class="rounded-full bg-slate-100 px-2.5 py-1 text-[10px] font-bold text-slate-600">{{ strtoupper($vessel->status) }}</span></div><h4 class="mt-4 font-black text-slate-900">{{ $vessel->name }}</h4><p class="text-xs text-slate-500">Matrícula {{ $vessel->registration_number }}</p><div class="mt-4 grid grid-cols-2 gap-2 text-xs"><span class="rounded-xl bg-slate-50 p-3"><b class="block text-lg text-slate-900">{{ $vessel->seat_capacity }}</b>asientos</span><span class="rounded-xl bg-slate-50 p-3"><b class="block text-slate-900">{{ $vessel->basePort?->name??'Sin base' }}</b>puerto base</span></div><a href="{{ route('admin.vessels.edit',$vessel) }}" class="mt-4 block text-xs font-bold text-emerald-800">Completar ficha y permisos →</a></article>@empty<p class="text-sm text-slate-500">Aún no hay embarcaciones.</p>@endforelse</div></section>
<section><div class="mb-3"><span class="text-[10px] font-bold uppercase tracking-wider text-sky-700">DGAC</span><h3 class="text-lg font-black text-slate-900">Aeronaves</h3></div><div class="grid gap-4 md:grid-cols-2 xl:grid-cols-3">@forelse($aircraft as $unit)<article class="rounded-3xl border border-slate-200/90 bg-white p-5 shadow-sm"><div class="flex justify-between"><span class="grid h-11 w-11 place-items-center rounded-2xl bg-sky-50">✈️</span><span class="rounded-full bg-sky-50 px-2.5 py-1 text-[10px] font-bold text-sky-700">{{ strtoupper($unit->status) }}</span></div><h4 class="mt-4 font-black text-slate-900">{{ $unit->name }}</h4><p class="text-xs text-slate-500">{{ $unit->model??'Modelo no registrado' }} · {{ $unit->registration_number }}</p><strong class="mt-4 block text-sm">{{ $unit->seat_capacity }} asientos</strong><a href="{{ route('admin.aircraft.edit',$unit) }}" class="mt-4 block text-xs font-bold text-sky-800">Completar ficha →</a></article>@empty<p class="text-sm text-slate-500">Aún no hay aeronaves.</p>@endforelse</div></section>
</div>
@endsection
