<x-app-layout>
<x-slot name="header"><h2 class="ny-page-title">Despacho de hoy</h2></x-slot>
@php($name=$company->commercial_name?:$company->legal_name)
<div class="mx-auto max-w-6xl space-y-5">
 <section class="rounded-3xl bg-[#062c21] p-6 text-white shadow-xl sm:p-8"><div class="flex flex-col justify-between gap-5 sm:flex-row sm:items-center"><div><span class="text-[10px] font-bold uppercase tracking-wider text-emerald-300">Portal Counter · {{now()->translatedFormat('d F Y')}}</span><h1 class="mt-2 text-2xl font-black sm:text-3xl">{{$name}}</h1><p class="mt-1 text-xs text-emerald-100/75">📍 {{$base}} · 🌊 Río: <strong class="text-emerald-300">{{$riverStatus}}</strong></p></div><a href="{{route('admin.boarding.index')}}" class="inline-flex h-12 items-center justify-center rounded-xl bg-amber-500 px-5 text-sm font-black text-slate-950">📱 Escanear DNI o QR</a></div></section>
 @if(session('success'))<div class="rounded-2xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-bold text-emerald-800">✓ {{session('success')}}</div>@endif
 <section><div class="mb-3"><span class="text-[10px] font-bold uppercase tracking-wider text-emerald-700">Operación diaria</span><h2 class="text-xl font-black text-slate-900">Salidas activas de hoy</h2></div><div class="grid gap-4">
 @forelse($departures as $row)@php($percent=$row['capacity']?min(100,round($row['booked']/$row['capacity']*100)):0)
  <article class="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><div class="flex flex-col gap-5 lg:flex-row lg:items-center"><div class="flex min-w-0 flex-1 items-start gap-4"><div class="flex h-12 w-12 shrink-0 items-center justify-center rounded-2xl {{$row['is_air']?'bg-sky-50':'bg-emerald-50'}} text-xl">{{$row['is_air']?'✈️':'🚤'}}</div><div><span class="text-[10px] font-bold uppercase tracking-wider {{$row['is_air']?'text-sky-700':'text-emerald-700'}}">{{$row['departure_at']->format('H:i')}} h · {{strtoupper($row['status'])}}</span><h3 class="mt-1 text-lg font-black text-slate-900">{{$row['origin']}} ➔ {{$row['destination']}}</h3><p class="text-xs text-slate-500">{{$row['unit']}}</p></div></div><div class="min-w-[190px]"><div class="flex justify-between text-xs"><strong>{{$row['booked']}}/{{$row['capacity']}} pasajeros</strong><span>{{$percent}}%</span></div><div class="mt-2 h-2 overflow-hidden rounded-full bg-slate-100"><i class="block h-full rounded-full {{$percent>=90?'bg-amber-500':'bg-emerald-600'}}" style="width:{{$percent}}%"></i></div></div><div class="flex flex-wrap gap-2"><a href="{{route('admin.boarding.index',[($row['is_air']?'air_departure':'departure')=>$row['model']->id])}}" class="inline-flex h-10 items-center rounded-xl bg-[#062c21] px-4 text-xs font-bold text-white">📱 Control de embarque</a>@if(!$row['is_air'])<a href="{{route('admin.manifests.show',$row['model'])}}" class="inline-flex h-10 items-center rounded-xl border border-slate-200 px-4 text-xs font-bold text-slate-700">📄 Manifiesto DICAPI</a>@else<span class="inline-flex h-10 items-center rounded-xl bg-sky-50 px-4 text-xs font-bold text-sky-700">DGAC · Registro interno</span>@endif</div></div></article>
 @empty<div class="rounded-3xl border border-dashed border-slate-300 bg-white px-6 py-14 text-center"><span class="text-3xl">🗓️</span><h3 class="mt-3 font-black text-slate-800">No hay salidas programadas para hoy</h3><p class="mt-1 text-xs text-slate-500">Consulta con el administrador de tu empresa.</p></div>@endforelse
 </div></section>
 <section class="grid gap-3 sm:grid-cols-2"><a href="{{route('admin.boarding.index')}}" class="rounded-2xl border border-emerald-200 bg-emerald-50 p-5"><strong class="text-sm text-emerald-900">📱 Validar pasajero</strong><p class="mt-1 text-xs text-emerald-700">Buscar por DNI, boleto, reserva o código QR.</p></a><a href="{{route('admin.cargo.create')}}" class="rounded-2xl border border-amber-200 bg-amber-50 p-5"><strong class="text-sm text-amber-900">📦 Registrar carga o equipaje</strong><p class="mt-1 text-xs text-amber-700">Recepción operativa vinculada a la empresa.</p></a></section>
</div>
</x-app-layout>

