<x-app-layout>
<x-slot name="header"><h2 class="ny-page-title">Centro operativo de empresa</h2></x-slot>
@php
$name=$company->commercial_name?:$company->legal_name;
$hasAir=$company->aircraft->isNotEmpty();
$hasRiver=$company->vessels->isNotEmpty();
$base=$company->vessels->first()?->basePort?->name??$company->address??'Base operativa por registrar';
@endphp
<div class="mx-auto max-w-7xl space-y-6 py-3">
<section class="overflow-hidden rounded-3xl bg-gradient-to-r from-[#062c21] via-emerald-950 to-slate-900 p-6 text-white shadow-xl sm:p-8">
<div class="flex flex-col justify-between gap-5 lg:flex-row lg:items-center"><div><div class="flex flex-wrap items-center gap-2"><span class="rounded-full border border-emerald-500/30 bg-emerald-500/15 px-3 py-1 text-[10px] font-bold uppercase tracking-wider text-emerald-300">{{$hasAir&&!$hasRiver?'✈️ Aerotaxi regional':'🚤 Operador fluvial'}}</span><span class="rounded-full bg-white/10 px-3 py-1 text-[10px] font-bold">RUC {{$company->ruc??'Por registrar'}}</span></div><h1 class="mt-3 text-2xl font-black tracking-tight sm:text-3xl">{{$name}}</h1><p class="mt-1 text-xs text-emerald-100/75">📍 {{$base}} · Operación diaria y despacho de pasajeros</p></div><div class="flex flex-wrap gap-2"><a href="{{route('admin.boarding.index')}}" class="inline-flex h-10 items-center rounded-xl bg-amber-500 px-4 text-xs font-black text-slate-950">📱 Control de abordaje</a><a href="{{route('company.departures.create')}}" class="inline-flex h-10 items-center rounded-xl border border-white/20 bg-white/5 px-4 text-xs font-bold text-white">＋ Programar salida</a></div></div>
</section>
@if(session('success'))<div class="rounded-2xl border border-emerald-200 bg-emerald-50 px-5 py-4 text-sm font-semibold text-emerald-800">✓ {{session('success')}}</div>@endif
<section class="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
@foreach([
['Recaudación hoy','S/ '.number_format($todayRevenue??0,2),'Ventas y carga confirmadas','💰'],
['Pasajeros hoy',number_format($todayTicketsCount??0),'viajeros registrados','👥'],
['Salidas del día',number_format($activeDeparturesCount??0),'programadas hoy','🧭'],
['Carga / fletes',number_format($pendingCargoCount??0),'encomiendas activas','📦'],
] as [$label,$value,$note,$icon])
<article class="rounded-2xl border border-slate-200/80 bg-white p-5 shadow-sm"><div class="flex items-center justify-between"><span class="text-[10px] font-bold uppercase tracking-wider text-slate-400">{{$label}}</span><span class="text-xl">{{$icon}}</span></div><strong class="mt-3 block text-2xl font-black text-slate-900">{{$value}}</strong><span class="mt-1 block text-[11px] text-slate-500">{{$note}}</span></article>
@endforeach
</section>
<section class="overflow-hidden rounded-3xl border border-slate-200/80 bg-white shadow-sm">
<div class="flex flex-wrap items-center justify-between gap-3 border-b border-slate-100 px-5 py-4"><div><span class="text-[10px] font-bold uppercase tracking-wider text-emerald-700">Despacho diario</span><h2 class="text-lg font-black text-slate-900">Salidas de hoy y manifiestos</h2></div><div class="flex gap-2"><a href="{{route('admin.boarding.index')}}" class="rounded-xl border border-slate-200 px-3 py-2 text-xs font-bold text-slate-700">Control de abordaje</a><a href="{{route('company.departures.create')}}" class="rounded-xl bg-emerald-800 px-3 py-2 text-xs font-bold text-white">Nueva salida</a></div></div>
<div class="overflow-x-auto"><table class="w-full min-w-[920px] text-left text-xs"><thead class="bg-slate-50 text-[10px] uppercase tracking-wider text-slate-400"><tr><th class="px-5 py-3">Hora</th><th class="px-4 py-3">Ruta</th><th class="px-4 py-3">Nave / matrícula</th><th class="px-4 py-3">Ocupación</th><th class="px-4 py-3">Estado</th><th class="px-5 py-3 text-right">Acciones</th></tr></thead><tbody>
@forelse($todayDepartures as $row)
@php($percentage=$row['capacity']>0?min(100,round($row['booked_seats']/$row['capacity']*100)):0)
<tr class="border-t border-slate-100"><td class="px-5 py-4"><strong class="text-base text-slate-900">{{$row['departure_at']->format('H:i')}}</strong><span class="block text-[9px] font-bold {{$row['is_air']?'text-sky-600':'text-emerald-700'}}">{{$row['is_air']?'✈ AÉREO':'🚤 FLUVIAL'}}</span></td><td class="px-4 py-4"><strong class="text-slate-900">{{$row['origin']}} ➔ {{$row['destination']}}</strong><span class="block text-[10px] text-slate-400">{{$row['departure_at']->format('d/m/Y')}}</span></td><td class="px-4 py-4 text-slate-700">{{$row['unit']}}<span class="block text-[10px] text-slate-400">{{$row['registration']??'Sin matrícula registrada'}}</span></td><td class="px-4 py-4"><div class="flex items-center justify-between text-[10px]"><strong class="text-slate-700">{{$row['booked_seats']}}/{{$row['capacity']}}</strong><span class="text-slate-400">{{$percentage}}%</span></div><div class="mt-1.5 h-2 w-36 overflow-hidden rounded-full bg-slate-100"><i class="block h-full rounded-full {{$percentage>=90?'bg-amber-500':'bg-emerald-600'}}" style="width:{{$percentage}}%"></i></div></td><td class="px-4 py-4"><span class="rounded-full bg-emerald-50 px-2 py-1 text-[10px] font-bold text-emerald-700">{{strtoupper($row['status'])}}</span></td><td class="px-5 py-4"><div class="flex flex-wrap justify-end gap-2">@if(!$row['is_air'])<a href="{{route('admin.manifests.show',$row['model'])}}" class="rounded-lg border border-slate-200 px-3 py-2 font-bold text-slate-700">📄 Manifiesto</a><a href="{{route('company.departures.edit',$row['model'])}}" class="rounded-lg border border-amber-200 bg-amber-50 px-3 py-2 font-bold text-amber-800">✏️ Reprogramar</a><form method="POST" action="{{route('company.departures.status',$row['model'])}}" class="flex gap-1">@csrf @method('PATCH')<select name="status" class="h-8 rounded-lg border-slate-200 py-1 text-[10px] font-bold"><option value="scheduled" @selected($row['status']==='scheduled')>Programado</option><option value="departed" @selected($row['status']==='departed')>Zarpó</option><option value="cancelled" @selected($row['status']==='cancelled')>Cancelado</option></select><button class="rounded-lg bg-slate-800 px-2 py-1 text-[10px] font-bold text-white">Guardar</button></form>@else<span class="rounded-lg bg-sky-50 px-3 py-2 font-bold text-sky-700">DGAC · Control interno</span>@endif<a href="{{route('admin.boarding.index',[($row['is_air']?'air_departure':'departure')=>$row['model']->id])}}" class="rounded-lg bg-[#062c21] px-3 py-2 font-bold text-white">📱 Abordaje</a></div></td></tr>
@empty<tr><td colspan="6" class="px-5 py-12 text-center"><strong class="text-slate-700">No hay salidas programadas para hoy.</strong><span class="mt-1 block text-xs text-slate-400">Programa una salida para comenzar el despacho.</span></td></tr>@endforelse
</tbody></table></div>
</section>
<section class="grid gap-6 lg:grid-cols-12">
<div class="overflow-hidden rounded-3xl border border-slate-200/80 bg-white shadow-sm lg:col-span-8">
<div class="flex items-center justify-between border-b border-slate-100 px-5 py-4"><div><span class="text-[10px] font-bold uppercase tracking-wider text-emerald-700">Últimos movimientos</span><h2 class="text-lg font-black text-slate-900">Reservas recientes</h2></div><a href="{{route('admin.reports.index')}}" class="text-xs font-bold text-emerald-800">Ver reporte →</a></div>
<div class="overflow-x-auto"><table class="w-full min-w-[720px] text-left text-xs"><thead class="bg-slate-50 text-[10px] uppercase tracking-wider text-slate-400"><tr><th class="px-5 py-3">Pasajero</th><th class="px-4 py-3">Ruta</th><th class="px-4 py-3">Asiento</th><th class="px-4 py-3">Importe</th><th class="px-5 py-3">Estado</th></tr></thead><tbody>
@forelse($recentBookings as $seat)
@php($reservation=$seat->reservation) @php($air=$reservation->isAir()) @php($trip=$air?$reservation->airDeparture:$reservation->departure) @php($route=$air?$trip?->airRoute:$trip?->transportRoute) @php($seatCount=max(1,$reservation->seats->count()))
<tr class="border-t border-slate-100"><td class="px-5 py-4"><strong class="text-slate-900">{{$seat->passenger_name}}</strong><span class="block text-[10px] text-slate-400">{{$seat->document_type??'DNI'}} {{$seat->document_number}}</span></td><td class="px-4 py-4 text-slate-700">{{$air?($route?->origin_city??'Origen'):($route?->originPort?->city??'Origen')}} ➔ {{$air?($route?->destination_city??'Destino'):($route?->destinationPort?->city??'Destino')}}</td><td class="px-4 py-4 font-bold text-slate-800">{{$air?$seat->aircraftSeat?->code:$seat->seat?->code}}</td><td class="px-4 py-4 font-bold text-slate-900">S/ {{number_format((float)$reservation->total_amount/$seatCount,2)}}</td><td class="px-5 py-4"><span class="rounded-full bg-slate-100 px-2 py-1 text-[10px] font-bold text-slate-600">{{strtoupper($reservation->status)}}</span></td></tr>
@empty<tr><td colspan="5" class="px-5 py-10 text-center text-slate-500">Todavía no hay reservas para mostrar.</td></tr>@endforelse
</tbody></table></div>
</div>
<aside class="space-y-4 lg:col-span-4"><div class="rounded-3xl border border-slate-200/80 bg-white p-5 shadow-sm"><h3 class="text-sm font-black text-slate-900">Acciones operativas</h3><div class="mt-3 grid gap-2"><a href="{{route('admin.boarding.index')}}" class="rounded-xl bg-emerald-50 px-4 py-3 text-xs font-bold text-emerald-800">📱 Validar DNI o QR</a><a href="{{route('admin.cargo.create')}}" class="rounded-xl bg-amber-50 px-4 py-3 text-xs font-bold text-amber-800">📦 Registrar encomienda</a><a href="{{route('admin.reports.index')}}" class="rounded-xl bg-sky-50 px-4 py-3 text-xs font-bold text-sky-800">📊 Reportes de operación</a></div></div></aside>
</section>
<section class="overflow-hidden rounded-3xl border border-slate-200/80 bg-white shadow-sm" x-data="{open:false}">
<div class="flex flex-wrap items-center justify-between gap-3 border-b border-slate-100 px-5 py-4"><div><span class="text-[10px] font-bold uppercase tracking-wider text-emerald-700">Accesos de terminal</span><h2 class="text-lg font-black text-slate-900">Equipo y usuarios Counter</h2><p class="text-[11px] text-slate-500">Personal limitado a despacho, embarque y carga de esta empresa.</p></div><button type="button" @click="open=!open" class="rounded-xl bg-amber-500 px-4 py-2.5 text-xs font-black text-slate-950">+ Nuevo usuario Counter</button></div>
<form x-show="open" x-cloak method="POST" action="{{route('company.staff.store')}}" class="grid gap-3 border-b border-slate-100 bg-slate-50 p-5 sm:grid-cols-2 lg:grid-cols-3">@csrf
<label class="text-xs font-bold text-slate-700">Nombre completo<input required name="name" value="{{old('name')}}" class="mt-1.5 w-full rounded-xl border-slate-200 text-sm"></label><label class="text-xs font-bold text-slate-700">Correo<input required type="email" name="email" value="{{old('email')}}" class="mt-1.5 w-full rounded-xl border-slate-200 text-sm"></label><label class="text-xs font-bold text-slate-700">DNI / documento<input required name="document_number" value="{{old('document_number')}}" class="mt-1.5 w-full rounded-xl border-slate-200 text-sm"></label><label class="text-xs font-bold text-slate-700">Teléfono<input required name="phone" value="{{old('phone')}}" class="mt-1.5 w-full rounded-xl border-slate-200 text-sm"></label><label class="text-xs font-bold text-slate-700">Contraseña temporal<input required type="password" name="password" class="mt-1.5 w-full rounded-xl border-slate-200 text-sm"></label><label class="text-xs font-bold text-slate-700">Confirmar contraseña<input required type="password" name="password_confirmation" class="mt-1.5 w-full rounded-xl border-slate-200 text-sm"></label><div class="sm:col-span-2 lg:col-span-3"><button class="rounded-xl bg-[#062c21] px-5 py-3 text-xs font-black text-white">Crear acceso Counter</button></div></form>
<div class="overflow-x-auto"><table class="w-full min-w-[760px] text-left text-xs"><thead class="bg-slate-50 text-[10px] uppercase tracking-wider text-slate-400"><tr><th class="px-5 py-3">Usuario</th><th class="px-4 py-3">Documento</th><th class="px-4 py-3">Teléfono</th><th class="px-4 py-3">Estado</th><th class="px-5 py-3 text-right">Acciones</th></tr></thead><tbody>
@forelse($counterStaff as $staff)@php($membership=$staff->organizations->first()?->pivot) <tr class="border-t border-slate-100"><td class="px-5 py-4"><strong class="text-slate-900">{{$staff->name}}</strong><span class="block text-[10px] text-slate-400">{{$staff->email}}</span></td><td class="px-4 py-4">{{$staff->document_number}}</td><td class="px-4 py-4">{{$staff->phone}}</td><td class="px-4 py-4"><span class="rounded-full px-2.5 py-1 text-[10px] font-bold {{$membership?->status==='active'?'bg-emerald-50 text-emerald-700':'bg-slate-100 text-slate-500'}}">{{$membership?->status==='active'?'Activo':'Inactivo'}}</span></td><td class="px-5 py-4"><div class="flex justify-end gap-2"><form method="POST" action="{{route('company.staff.toggle',$staff)}}">@csrf @method('PATCH')<button class="rounded-lg border border-slate-200 px-3 py-2 font-bold text-slate-700">{{$membership?->status==='active'?'Deshabilitar':'Habilitar'}}</button></form><form method="POST" action="{{route('company.staff.destroy',$staff)}}" onsubmit="return confirm('¿Retirar este usuario Counter?')">@csrf @method('DELETE')<button class="rounded-lg bg-red-50 px-3 py-2 font-bold text-red-700">Retirar</button></form></div></td></tr>
@empty<tr><td colspan="5" class="px-5 py-10 text-center text-slate-500">Todavía no hay usuarios Counter registrados.</td></tr>@endforelse
</tbody></table></div></section>
<details class="group rounded-3xl border border-slate-200/80 bg-white shadow-sm">
<summary class="flex cursor-pointer list-none items-center justify-between p-5"><div><span class="text-[10px] font-bold uppercase tracking-wider text-slate-400">Configuración secundaria</span><h2 class="text-lg font-black text-slate-900">Perfil público de la empresa</h2></div><span class="rounded-xl bg-slate-100 px-3 py-2 text-xs font-bold text-slate-600 group-open:hidden">Editar perfil</span><span class="hidden rounded-xl bg-slate-100 px-3 py-2 text-xs font-bold text-slate-600 group-open:block">Cerrar</span></summary>
<div class="border-t border-slate-100 p-5 sm:p-6"><p class="mb-5 text-xs text-slate-500">Esta información aparece en el directorio público de operadores.</p><form method="POST" enctype="multipart/form-data" action="{{route('company.dashboard.profile')}}">@csrf @method('PATCH')<div class="grid gap-4 md:grid-cols-2"><label class="text-xs font-bold text-slate-700">Nombre comercial<input name="commercial_name" value="{{old('commercial_name',$company->commercial_name)}}" class="mt-1.5 w-full rounded-xl border-slate-200 text-sm"></label><label class="text-xs font-bold text-slate-700">WhatsApp público<input name="whatsapp" value="{{old('whatsapp',$company->whatsapp)}}" class="mt-1.5 w-full rounded-xl border-slate-200 text-sm"></label><label class="text-xs font-bold text-slate-700">Teléfono<input name="phone" value="{{old('phone',$company->phone)}}" class="mt-1.5 w-full rounded-xl border-slate-200 text-sm"></label><label class="text-xs font-bold text-slate-700">Sitio web<input type="url" name="website" value="{{old('website',$company->website)}}" class="mt-1.5 w-full rounded-xl border-slate-200 text-sm"></label><label class="text-xs font-bold text-slate-700 md:col-span-2">Dirección<input name="address" value="{{old('address',$company->address)}}" class="mt-1.5 w-full rounded-xl border-slate-200 text-sm"></label><label class="text-xs font-bold text-slate-700 md:col-span-2">Descripción para viajeros<textarea name="public_description" rows="4" class="mt-1.5 w-full rounded-xl border-slate-200 text-sm">{{old('public_description',$company->public_description)}}</textarea></label><label class="text-xs font-bold text-slate-700">Logo<input type="file" accept="image/*" name="logo" class="mt-1.5 w-full rounded-xl border border-slate-200 p-2 text-xs"></label><label class="text-xs font-bold text-slate-700">Imagen de portada<input type="file" accept="image/*" name="cover" class="mt-1.5 w-full rounded-xl border border-slate-200 p-2 text-xs"></label></div><button class="mt-5 rounded-xl bg-amber-500 px-5 py-3 text-xs font-black text-slate-950">Guardar cambios</button></form></div>
</details>
</div>
</x-app-layout>

