<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Reserva aérea · NavegaYA</title>@vite(['resources/css/app.css','resources/js/app.js'])
<style>
*{box-sizing:border-box}body{margin:0;background:#f4f7f8;color:#173b4b;font-family:ui-sans-serif,system-ui,sans-serif}.wrap{max-width:1160px;margin:25px auto;padding:0 20px}.hero{padding:27px 30px;border-radius:22px;background:linear-gradient(120deg,#123f64,#167da2);color:#fff}.hero small{color:#9ee3f8;font-weight:900;letter-spacing:.13em}.hero h1{margin:7px 0;font-size:30px}.hero p{margin:0;color:#dceff7}.grid{display:grid;grid-template-columns:minmax(0,1.35fr) minmax(330px,.65fr);gap:20px;margin-top:20px}.card{padding:24px;border:1px solid #d8e8ee;border-radius:20px;background:#fff}.card h2{margin:0;color:#164d63}.hint{color:#687f88;font-size:13px}.cabin-title{display:flex;justify-content:space-between;margin:22px 0 10px;color:#0b6889;font-size:13px;font-weight:850;text-transform:uppercase;letter-spacing:.08em}.cabin-title small{color:#71847d;letter-spacing:0;text-transform:none}
.stage{overflow:auto;padding:55px 16px 34px;border:1px solid #d8edf5;border-radius:18px;background:radial-gradient(circle at 50% 5%,#dff4fc,#f5fbfe 62%,#fff)}.plane{position:relative;width:var(--plane-width);min-height:var(--plane-height);margin:auto;padding:80px 38px 70px;border:2px solid #72b8d1;border-radius:48% 48% 36% 36% / 11% 11% 8% 8%;background:linear-gradient(90deg,#e2f4fa,#fff 14%,#fff 86%,#e2f4fa);box-shadow:0 22px 42px #145b7826,inset 0 0 0 8px #f2fafd}.plane:before{content:"";position:absolute;z-index:0;top:42%;left:50%;transform:translate(-50%,-50%);width:calc(100% + 230px);height:90px;border:2px solid #72b8d1;border-radius:65% 65% 25% 25%;background:#e6f5fa;box-shadow:0 12px 24px #145b7817}.plane:after{content:"";position:absolute;left:50%;bottom:-32px;transform:translateX(-50%);width:85px;height:72px;border:2px solid #72b8d1;border-radius:15% 15% 65% 65%;background:#e1f2f8}.cockpit,.seat-cabin{position:relative;z-index:2}.cockpit{position:absolute;top:22px;left:50%;transform:translateX(-50%);width:64%;padding:11px;border:1px solid #b5dce9;border-radius:50% 50% 12px 12px;background:#dff2f9;color:#245e74;text-align:center;font-size:9px;font-weight:900;letter-spacing:.11em}.seat-cabin{padding:16px;border:1px solid #cce5ef;border-radius:25px;background:#fafdffff}.seat-cabin:before{content:"PASILLO";position:absolute;top:50%;left:50%;transform:translate(-50%,-50%) rotate(-90deg);padding:4px 7px;border-radius:99px;background:#fff;color:#7da0ae;font-size:7px;font-weight:900;letter-spacing:.1em;box-shadow:0 0 0 1px #dcecf2}.seat-row{position:relative;z-index:2;display:grid;align-items:center;gap:7px;margin:8px 0}.row-no{font-size:9px;font-weight:900;color:#7093a1;text-align:center}.aisle{width:23px}.seat{width:40px;height:38px;border:1px solid #86c7de;border-radius:12px 12px 8px 8px;background:linear-gradient(#dff5fc,#c9ebf7);color:#075f82;font-size:11px;font-weight:900;cursor:pointer;box-shadow:0 3px 0 #8dc8dc}.seat:hover{transform:translateY(-2px)}.seat.selected{border-color:#086d95;background:linear-gradient(#43b7df,#168bb5);color:#fff;box-shadow:0 3px 0 #086d95}.seat:disabled{border-color:#d9dfe0;background:#e9edee;color:#98a5a8;cursor:not-allowed;text-decoration:line-through;box-shadow:0 3px 0 #d1d7d8}.nose,.tail{position:absolute;z-index:3;left:50%;transform:translateX(-50%);font-size:8px;font-weight:900;letter-spacing:.14em;color:#0d6687}.nose{top:-26px}.tail{bottom:20px}.legend{display:flex;gap:14px;flex-wrap:wrap;margin-top:14px;color:#667d86;font-size:11px}.legend i{display:inline-block;width:10px;height:10px;border-radius:3px}
.field{display:block;margin-top:13px;color:#345866;font-size:13px;font-weight:750}.field input{width:100%;margin-top:5px;padding:10px;border:1px solid #c6dce5;border-radius:9px}.passenger{margin-top:12px;padding:13px;border:1px solid #d9e9ef;border-radius:11px;background:#f5fbfd}.holder-check{display:flex!important;align-items:center;gap:9px;margin:12px 0 0!important;padding:10px 11px;border:1px solid #cfe7f0;border-radius:9px;background:#e8f6fb;color:#185b73!important;line-height:1.35}.holder-check input{width:17px!important;height:17px;margin:0!important;padding:0!important;accent-color:#147699}.holder-check span{font-weight:750}.checkout{position:sticky;top:18px;height:max-content}.summary{margin-top:18px;padding:13px;border-radius:11px;background:#e8f6fb;color:#135b75}.submit{width:100%;margin-top:18px;padding:13px;border:0;border-radius:10px;background:#146f91;color:#fff;font-weight:850}.error{padding:12px;border-radius:10px;background:#fff0f1;color:#b4233f}@media(max-width:850px){.grid{grid-template-columns:1fr}.checkout{position:static}}@media(max-width:600px){.wrap{padding:0 12px}.card{padding:16px}.stage{margin:0 -8px}}
</style></head><body><x-public-nav current="travels"/>
<main class="wrap"><section class="hero"><small>VIAJE AÉREO</small><h1>{{$departure->airRoute->origin_city}} → {{$departure->airRoute->destination_city}}</h1><p>{{$departure->departure_at->format('d/m/Y · H:i')}} h · {{$departure->aircraft->name}} · S/ {{number_format($departure->fare,2)}} por pasajero</p></section>
@if($errors->any())<p class="error">{{$errors->first()}}</p>@endif
<form method="POST" action="{{route('air-bookings.store',$departure)}}" id="airForm">@csrf<div class="grid"><section class="card"><h2>Elige tus asientos</h2><p class="hint">Selecciona uno o varios asientos directamente dentro de la aeronave.</p>
@foreach($seats->groupBy('cabin') as $cabinName=>$cabinSeats)
@php($cols=$cabinSeats->max('column_position')) @php($middle=(int)ceil($cols/2)) @php($rows=$cabinSeats->max('row_position'))
<div class="cabin-title"><span>{{$cabinName}}</span><small>{{$cabinSeats->count()}} asientos</small></div>
<div class="stage"><div class="plane" style="--plane-width:{{max(330,100+($cols*47)+23)}}px;--plane-height:{{max(360,180+($rows*46))}}px"><span class="nose">NARIZ</span><div class="cockpit">◉ CABINA DE PILOTOS</div><div class="seat-cabin">
@foreach($cabinSeats->groupBy('row_position') as $row=>$rowSeats)<div class="seat-row" style="grid-template-columns:26px repeat({{$middle}},40px) 23px repeat({{$cols-$middle}},40px)"><span class="row-no">{{str_pad($row,2,'0',STR_PAD_LEFT)}}</span>
@for($col=1;$col<=$cols;$col++) @php($seat=$rowSeats->firstWhere('column_position',$col)) @if($seat)<button type="button" class="seat" data-id="{{$seat->id}}" data-code="{{$seat->code}}" @disabled(in_array($seat->id,$occupiedSeatIds,true))>{{$seat->code}}</button>@endif @if($col===$middle)<span class="aisle"></span>@endif @endfor
</div>@endforeach</div><span class="tail">COLA</span></div></div>
@endforeach
<div class="legend"><span><i style="background:#c9ebf7"></i> Disponible</span><span><i style="background:#168bb5"></i> Seleccionado</span><span><i style="background:#e2e8f0"></i> Ocupado</span></div><div id="seatInputs"></div></section>
<aside class="card checkout"><h2>Datos de quien realiza la compra</h2><p class="hint">Esta persona recibirá la confirmación. Puede viajar o comprar para otra persona.</p><label class="field">Nombre completo<input name="contact_name" required></label><label class="field">Correo electrónico<input type="email" name="contact_email" required></label><label class="field">Teléfono / WhatsApp<input name="contact_phone" required></label><label class="field">DNI o documento<input name="contact_document" required></label><div id="passengers"></div><div class="summary"><strong id="selectionCount">0 asientos seleccionados</strong><br>Total estimado: <strong id="selectionTotal">S/ 0.00</strong></div><button class="submit">Agregar al carrito</button></aside>
</div></form></main><x-public-footer/>
<script>
const selected=new Map,inputs=document.getElementById('seatInputs'),passengers=document.getElementById('passengers'),fare={{(float)$departure->fare}},buyerName=document.querySelector('[name=contact_name]'),buyerDocument=document.querySelector('[name=contact_document]');
document.querySelectorAll('.seat:not(:disabled)').forEach(b=>b.onclick=()=>{selected.has(b.dataset.id)?selected.delete(b.dataset.id):selected.set(b.dataset.id,b.dataset.code);b.classList.toggle('selected');render()});
function syncHolder(box){const card=box.closest('.passenger'),fields=card.querySelector('.passenger-fields'),name=card.querySelector('.passenger-name'),documentField=card.querySelector('.passenger-document');if(box.checked){document.querySelectorAll('.holder-toggle').forEach(other=>{if(other!==box&&other.checked){other.checked=false;syncHolder(other)}});name.value=buyerName.value;documentField.value=buyerDocument.value;fields.hidden=true}else{fields.hidden=false;name.required=true;documentField.required=true}}
function render(){inputs.innerHTML='';passengers.innerHTML='';[...selected].forEach(([id,code],i)=>{inputs.insertAdjacentHTML('beforeend',`<input type="hidden" name="seats[]" value="${id}">`);passengers.insertAdjacentHTML('beforeend',`<div class="passenger"><strong>Pasajero · asiento ${code}</strong><label class="holder-check"><input type="checkbox" class="holder-toggle" ${i===0?'checked':''}><span>La persona que realiza la compra viaja en este asiento</span></label><div class="passenger-fields"><label class="field">Nombre completo<input class="passenger-name" name="passengers[${i}][name]" required></label><label class="field">DNI o documento<input class="passenger-document" name="passengers[${i}][document]" required></label></div></div>`)});passengers.querySelectorAll('.holder-toggle').forEach(box=>{box.addEventListener('change',()=>syncHolder(box));syncHolder(box)});document.getElementById('selectionCount').textContent=`${selected.size} asiento(s) seleccionado(s)`;document.getElementById('selectionTotal').textContent=`S/ ${(selected.size*fare).toFixed(2)}`}
;[buyerName,buyerDocument].forEach(field=>field.addEventListener('input',()=>{const box=document.querySelector('.holder-toggle:checked');if(box)syncHolder(box)}));
document.getElementById('airForm').onsubmit=e=>{if(!selected.size){e.preventDefault();alert('Selecciona al menos un asiento.')}}
</script></body></html>
