<x-public-layout title="Selección de asientos · NavegaYA">
<x-slot:head><style>
.booking-layout{display:grid;grid-template-columns:minmax(0,1fr);gap:1.5rem;align-items:start}.deck-panel[hidden]{display:none}.vessel-hull{position:relative;margin:auto;max-width:520px;border:2px solid #93c5bd;border-radius:48% 48% 22px 22px/11% 11% 22px 22px;background:linear-gradient(90deg,#e8f7f4 0,#fff 13%,#fff 87%,#e8f7f4 100%);padding:66px 24px 54px;box-shadow:inset 0 0 24px #dff3ee}.vessel-hull:before,.vessel-hull:after{content:'';position:absolute;top:100px;bottom:65px;width:5px;border-radius:99px;background:repeating-linear-gradient(#7dd3c7 0 8px,transparent 8px 20px);opacity:.65}.vessel-hull:before{left:10px}.vessel-hull:after{right:10px}.bridge{position:absolute;top:16px;left:50%;transform:translateX(-50%);width:190px;border:1px solid #a7d8cc;border-radius:50% 50% 12px 12px;background:#e5f4f0;padding:9px;text-align:center;font-size:9px;font-weight:800;letter-spacing:.12em;color:#0f766e}.stern{position:absolute;bottom:16px;left:50%;transform:translateX(-50%);font-size:9px;font-weight:800;letter-spacing:.12em;color:#64748b;white-space:nowrap}.seat-row{display:grid;grid-template-columns:22px repeat(var(--cols),44px);gap:8px;align-items:center;justify-content:center;margin-bottom:9px}.seat-btn{height:42px;width:44px;border:2px solid #a7d8cc;border-radius:12px;background:#fff;color:#065f46;font-size:11px;font-weight:800;box-shadow:0 2px 0 #d1fae5;transition:.15s}.seat-btn:hover{border-color:#059669;transform:translateY(-1px)}.seat-btn.selected{border-color:#062c21;background:#062c21;color:#fbbf24;box-shadow:0 0 0 2px #f59e0b}.seat-btn:disabled{cursor:not-allowed;border-color:#e2e8f0;background:#e2e8f0;color:#94a3b8;text-decoration:line-through;box-shadow:none}.seat-gap{width:44px}.field{border:1px solid #e2e8f0;border-radius:12px;background:#f8fafc;padding:8px 11px}.field:focus-within{background:#fff;box-shadow:0 0 0 2px #059669}.field label{display:block;font-size:9px;font-weight:800;text-transform:uppercase;letter-spacing:.06em;color:#94a3b8}.field input,.field select{width:100%;border:0;background:transparent;padding:2px 0 0;font-size:12px;font-weight:600;color:#1e293b;outline:0;box-shadow:none}.passenger-card{border:1px solid #dbe7e3;border-radius:14px;background:#f8fafc;padding:12px}@media(min-width:1024px){.booking-layout{grid-template-columns:minmax(0,7fr) minmax(360px,5fr)}.checkout-side{position:sticky;top:6.5rem}}
</style><style>.seat-btn{position:relative;height:46px;padding-top:7px;border-color:#94a3b8}.seat-btn:before{content:"";position:absolute;left:9px;right:9px;top:5px;height:5px;border-radius:999px;background:#dbe7e3}.seat-btn.selected{border-color:#f59e0b;box-shadow:0 0 0 2px #064e3b}.seat-btn.selected:before{background:#fbbf24;opacity:.55}.seat-btn:disabled:before{background:#cbd5e1}.bridge{background:linear-gradient(#062c21,#164e3f);color:#a7f3d0}.motors{display:flex;justify-content:center;gap:9px;margin-bottom:4px}.motor{display:block;width:20px;height:11px;border-radius:3px 3px 7px 7px;background:#64748b;box-shadow:inset 0 2px #94a3b8}</style><style>
.vessel-hull{border-color:#72a99e;background:linear-gradient(90deg,#d8ebe7 0,#f8fafc 8%,#fff 19%,#fff 81%,#f8fafc 92%,#d8ebe7 100%);box-shadow:inset 0 0 0 5px rgba(255,255,255,.82),inset 0 0 28px #b9d9d2,0 18px 34px rgba(15,118,110,.14)}
.bridge{width:218px;border-color:#0f766e;background:linear-gradient(180deg,#164e63,#071f1a);color:#a7f3d0;box-shadow:inset 0 -7px 13px rgba(0,0,0,.4),0 5px 13px rgba(6,44,33,.22)}
.seat-btn{position:relative;height:48px;padding-top:8px;border-color:#cbd5e1;border-radius:14px 14px 10px 10px;background:linear-gradient(145deg,#fff,#f8fafc);box-shadow:0 4px 0 #cbd5e1,0 7px 12px rgba(15,23,42,.1)}
.seat-btn:before{content:"";position:absolute;left:8px;right:8px;top:5px;height:7px;border:1px solid #cbd5e1;border-radius:999px;background:linear-gradient(#fff,#e2e8f0)}
.seat-btn:after{content:"";position:absolute;left:6px;right:6px;bottom:4px;height:8px;border:1px solid #e2e8f0;border-radius:3px 3px 7px 7px}
.seat-btn:hover{border-color:#059669;box-shadow:0 4px 0 #6ee7b7,0 9px 15px rgba(5,150,105,.16)}
.seat-btn.selected{border-color:#f59e0b;background:linear-gradient(145deg,#064e3b,#062c21);color:#fbbf24;box-shadow:0 4px 0 #f59e0b,0 0 17px rgba(245,158,11,.34)}
.seat-btn.selected:before{border-color:#fbbf24;background:#fbbf24;opacity:.6}.seat-btn.selected:after{border-color:rgba(251,191,36,.55)}
.seat-btn:disabled{border-color:#94a3b8;background:repeating-linear-gradient(135deg,#e2e8f0 0,#e2e8f0 6px,#cbd5e1 6px,#cbd5e1 8px);color:#64748b;box-shadow:0 3px 0 #94a3b8}.seat-btn:disabled:before{border-color:#94a3b8;background:#94a3b8}.seat-btn:disabled:after{border-color:#94a3b8}
.seat-gap{height:48px;border-radius:7px;background:repeating-linear-gradient(90deg,#d8b47c 0,#d8b47c 5px,#c89b5e 5px,#c89b5e 7px);box-shadow:inset 0 0 0 1px rgba(120,72,20,.16)}
.motors{display:flex;justify-content:center;gap:10px;margin-bottom:4px}.motor{display:block;width:24px;height:14px;border-radius:4px 4px 8px 8px;background:linear-gradient(180deg,#64748b,#0f172a);box-shadow:inset 0 2px #94a3b8,0 3px 6px rgba(15,23,42,.28)}
.checkout-side section{padding:20px}
.checkout-side .field{min-height:0!important;padding:6px 10px!important;border-radius:11px!important}
.checkout-side .field label{font-size:8px!important;line-height:1.1}
.checkout-side .field input,.checkout-side .field select{height:24px!important;min-height:24px!important;padding:1px 0!important;font-size:11px!important;line-height:1.2!important}
.checkout-side .passenger-card{padding:10px!important;border-radius:12px!important}
.checkout-side .passenger-card .field{background:#fff}
.checkout-steps{display:grid;grid-template-columns:repeat(3,1fr);gap:6px}
.checkout-step{display:flex;align-items:center;gap:6px;border-radius:10px;background:#f8fafc;padding:6px 8px;font-size:9px;font-weight:800;color:#64748b}
.checkout-step b{display:grid;width:18px;height:18px;place-items:center;border-radius:999px;background:#062c21;color:#fbbf24;font-size:9px}
</style></x-slot:head>
@php
    $route=$departure->transportRoute;
    $deckGroups=$seats->groupBy('deck');
    $firstDeck=(string)($deckGroups->keys()->first() ?? 'principal');
@endphp
<div class="min-h-screen bg-slate-50 pb-20"><main class="mx-auto max-w-7xl px-4 pt-4 sm:px-6 lg:px-8">
<section class="relative overflow-hidden rounded-3xl bg-gradient-to-r from-[#062c21] via-emerald-950 to-slate-900 p-6 text-white shadow-xl sm:p-8"><div class="relative z-10 flex flex-col justify-between gap-4 md:flex-row md:items-center"><div><span class="mb-2 inline-flex rounded-full border border-emerald-500/30 bg-emerald-500/20 px-2.5 py-1 text-[10px] font-bold uppercase tracking-wider text-emerald-300">Reserva de asientos en vivo</span><h1 class="text-2xl font-black tracking-tight sm:text-3xl">{{$route->originPort->city}} ➔ {{$route->destinationPort->city}}</h1><p class="mt-1 flex flex-wrap gap-3 text-xs text-emerald-100/80"><span>📅 {{$departure->departure_at->format('d/m/Y · H:i')}} h</span><span>🚤 {{$departure->vessel->name}}</span><strong class="text-amber-300">S/ {{number_format((float)$departure->fare,2)}} por pasajero</strong></p></div><a href="{{route('routes.index')}}" class="text-xs font-bold text-emerald-200 hover:text-white">← Cambiar salida</a></div></section>
@if($errors->any())<div class="mt-4 rounded-2xl border border-rose-200 bg-rose-50 p-4 text-xs text-rose-800"><strong>Revisa los datos:</strong><ul class="mt-1 list-inside list-disc">@foreach($errors->all() as $error)<li>{{$error}}</li>@endforeach</ul></div>@endif
<form method="POST" action="{{route('bookings.store',$departure)}}" id="bookingForm">@csrf
<div class="booking-layout mt-6">
<section class="rounded-3xl border border-slate-200/90 bg-white p-5 shadow-sm sm:p-7"><div class="flex flex-col justify-between gap-4 border-b border-slate-100 pb-4 sm:flex-row sm:items-center"><div><h2 class="text-lg font-black text-slate-900">Croquis de la embarcación</h2><p class="text-xs text-slate-400">Selecciona hasta 4 asientos disponibles.</p></div><div class="flex flex-wrap gap-1 rounded-2xl bg-slate-100 p-1">@foreach($deckGroups as $deck=>$deckSeats)<button type="button" class="deck-tab rounded-xl px-3 py-1.5 text-xs font-bold" data-deck-tab="{{$deck}}">{{$deck==='principal'?'Cubierta Principal':'Cubierta Superior'}} ({{$deckSeats->count()}})</button>@endforeach</div></div>
<div class="flex flex-wrap justify-center gap-5 border-b border-slate-100 py-4 text-[11px] text-slate-600"><span class="flex items-center gap-1.5"><i class="h-4 w-4 rounded border-2 border-emerald-600 bg-white"></i>Disponible</span><span class="flex items-center gap-1.5 font-bold"><i class="grid h-4 w-4 place-items-center rounded bg-[#062c21] text-[9px] text-amber-400">✓</i>Seleccionado</span><span class="flex items-center gap-1.5 text-slate-400"><i class="grid h-4 w-4 place-items-center rounded bg-slate-200 text-[9px]">×</i>Ocupado</span></div>
<div class="overflow-x-auto py-7">@foreach($deckGroups as $deck=>$deckSeats)@php $maxColumn=(int)$deckSeats->max('column_position'); @endphp<div class="deck-panel" data-deck-panel="{{$deck}}" @if($deck!==$firstDeck) hidden @endif><div class="vessel-hull" style="min-width:{{max(360,100+$maxColumn*52)}}px"><div class="bridge">⚓ PROA · PARABRISAS Y TIMÓN</div>@foreach($deckSeats->groupBy('row_position') as $row=>$rowSeats)<div class="seat-row" style="--cols:{{$maxColumn}}"><span class="text-center text-[8px] font-black text-slate-400">F{{$row}}</span>@for($column=1;$column<=$maxColumn;$column++)@php $seat=$rowSeats->firstWhere('column_position',$column); @endphp @if($seat)<button type="button" class="seat-btn" data-seat-id="{{$seat->id}}" data-code="{{$seat->code}}" @disabled(in_array($seat->id,$occupiedSeatIds,true))>{{$seat->code}}</button>@else<span class="seat-gap"></span>@endif @endfor</div>@endforeach<div class="stern"><span class="motors"><i class="motor"></i><i class="motor"></i></span>POPA · BODEGA Y MOTORES</div></div></div>@endforeach</div>
</section>
<aside class="checkout-side space-y-4"><section class="rounded-3xl border border-slate-200/90 bg-white shadow-xl"><div class="checkout-steps mb-4"><div class="checkout-step"><b>1</b> Asiento</div><div class="checkout-step"><b>2</b> Pasajeros</div><div class="checkout-step"><b>3</b> Confirmar</div></div><div class="flex items-end justify-between gap-3 border-b border-slate-100 pb-3"><div><span class="text-[9px] font-extrabold uppercase tracking-wider text-emerald-800">Tu viaje</span><h2 class="mt-0.5 text-lg font-black text-slate-900">{{$route->originPort->city}} ➔ {{$route->destinationPort->city}}</h2><p class="mt-0.5 text-[10px] text-slate-500">{{$departure->departure_at->format('d/m/Y · H:i')}} h · {{$route->originPort->name}}</p></div><span class="rounded-lg bg-emerald-50 px-2 py-1 text-[9px] font-bold text-emerald-700">Reserva segura</span></div>
<div class="mt-3 flex items-center justify-between gap-3 rounded-xl border border-slate-100 bg-slate-50 px-3 py-2"><span class="shrink-0 text-[9px] font-bold uppercase text-slate-400">Tus asientos</span><div id="selectedLabels" class="flex flex-wrap justify-end gap-1.5"><span class="text-xs font-bold text-amber-700">Selecciona un asiento en el croquis.</span></div></div>
<div class="mt-3">
<div class="mb-2 flex items-center justify-between"><div><h3 class="text-[11px] font-black uppercase tracking-wider text-slate-900">🪪 Titular y pasajero principal</h3><p class="mt-0.5 text-[9px] text-slate-400">Usaremos estos datos para el boleto digital.</p></div><span class="rounded-lg bg-emerald-50 px-2 py-1 text-[9px] font-bold text-emerald-700">Paso 2</span></div>
<div class="grid gap-2 sm:grid-cols-2">
<div class="field"><label>Tipo de documento</label><select id="holderDocumentType"><option value="DNI">DNI</option><option value="CE">Carné de extranjería</option><option value="Pasaporte">Pasaporte</option></select></div>
<div class="field"><label>DNI / documento</label><input name="contact_document" required inputmode="numeric" maxlength="20" value="{{old('contact_document')}}" placeholder="Ej. 41694908"></div>
<div class="field sm:col-span-2"><label>Nombres y apellidos según documento</label><input name="contact_name" required autocomplete="name" value="{{old('contact_name')}}" placeholder="Nombre legal completo"></div>
<div class="field"><label>WhatsApp</label><div class="flex items-center"><span class="mr-2 border-r border-slate-200 pr-2 text-[10px] font-bold text-slate-500">+51</span><input name="contact_phone" required inputmode="tel" value="{{old('contact_phone')}}" placeholder="900 000 000"></div></div>
<div class="field"><label>Correo para recibir el QR</label><input type="email" name="contact_email" required autocomplete="email" value="{{old('contact_email')}}" placeholder="correo@ejemplo.com"></div>
</div></div>
<div id="additionalHeading" class="mt-3 hidden items-center justify-between border-t border-slate-100 pt-3"><div><h3 class="text-[11px] font-black uppercase tracking-wider text-slate-900">👥 Pasajeros adicionales</h3><p class="text-[9px] text-slate-400">Solo para los asientos extra seleccionados.</p></div></div>
<div id="passengers" class="mt-2 space-y-2"></div><div class="mt-3 space-y-1.5 rounded-xl bg-slate-50 p-3 text-[11px]"><div class="flex justify-between text-slate-600"><span>Pasaje regular</span><span id="fareLine" class="font-bold text-slate-900">S/ 0.00</span></div><div class="flex justify-between text-slate-500"><span>Tasa portuaria / impuestos</span><strong class="text-emerald-700">Incluido</strong></div><div class="flex items-baseline justify-between border-t border-slate-100 pt-3"><strong class="text-sm text-slate-900">Total a pagar</strong><strong id="totalAmount" class="text-2xl text-slate-900">S/ 0.00</strong></div></div>
<button id="submitButton" disabled class="mt-3 flex h-11 w-full items-center justify-center rounded-xl bg-amber-500 text-xs font-black text-slate-950 transition hover:bg-amber-600 disabled:cursor-not-allowed disabled:bg-slate-200 disabled:text-slate-400">Selecciona un asiento</button><p class="mt-3 border-t border-slate-100 pt-2 text-[9px] leading-relaxed text-slate-500">🛡️ Tu reserva se registra automáticamente en el manifiesto oficial de zarpe para control de Capitanía.</p></section></aside>
</div></form></main></div>
<script>
(()=>{const selected=new Map(),fare={{(float)$departure->fare}},passengers=document.getElementById('passengers'),labels=document.getElementById('selectedLabels'),total=document.getElementById('totalAmount'),fareLine=document.getElementById('fareLine'),submit=document.getElementById('submitButton'),holderName=document.querySelector('[name=contact_name]'),holderDocument=document.querySelector('[name=contact_document]');
function render(){const list=[...selected.entries()],docType=document.getElementById('holderDocumentType'),extraHeading=document.getElementById('additionalHeading');labels.innerHTML=list.length?list.map(([id,code])=>`<span class="rounded-xl bg-[#062c21] px-2.5 py-1 text-[10px] font-black text-amber-300">Asiento ${code}</span>`).join(''):'<span class="text-xs font-bold text-amber-700">Selecciona un asiento en el croquis.</span>';extraHeading.classList.toggle('hidden',list.length<2);extraHeading.classList.toggle('flex',list.length>1);passengers.innerHTML=list.map(([id,code],i)=>{if(i===0)return `<input type="hidden" name="seats[]" value="${id}"><input type="hidden" class="primary-name" name="passengers[0][name]"><input type="hidden" class="primary-document" name="passengers[0][document]"><input type="hidden" class="primary-document-type" name="passengers[0][document_type]"><input type="hidden" name="passengers[0][age]" value="">`;return `<div class="passenger-card"><div class="flex items-center justify-between"><strong class="text-[11px] text-slate-900">Asiento ${code}</strong><span class="rounded-md bg-amber-50 px-2 py-0.5 text-[9px] font-bold text-amber-700">Pasajero ${i+1}</span></div><input type="hidden" name="seats[]" value="${id}"><div class="mt-1.5 grid gap-1.5 sm:grid-cols-2"><div class="field"><label>Tipo de documento</label><select name="passengers[${i}][document_type]"><option>DNI</option><option>CE</option><option>Pasaporte</option></select></div><div class="field"><label>Número</label><input required name="passengers[${i}][document]"></div><div class="field sm:col-span-2"><label>Nombres y apellidos</label><input required name="passengers[${i}][name]"></div><input type="hidden" name="passengers[${i}][age]" value=""></div></div>`}).join('');const syncPrimary=()=>{passengers.querySelector('.primary-name')?.setAttribute('value',holderName.value);passengers.querySelector('.primary-document')?.setAttribute('value',holderDocument.value);passengers.querySelector('.primary-document-type')?.setAttribute('value',docType.value)};syncPrimary();const amount=list.length*fare;fareLine.textContent=`${list.length} × S/ ${fare.toFixed(2)}`;total.textContent=`S/ ${amount.toFixed(2)}`;submit.textContent=list.length?`Continuar · S/ ${amount.toFixed(2)}`:'Selecciona un asiento';submit.disabled=!list.length}
document.querySelectorAll('.seat-btn:not(:disabled)').forEach(button=>button.addEventListener('click',()=>{const id=button.dataset.seatId;if(selected.has(id)){selected.delete(id);button.classList.remove('selected')}else if(selected.size<4){selected.set(id,button.dataset.code);button.classList.add('selected')}render()}));document.querySelectorAll('[data-deck-tab]').forEach(button=>button.addEventListener('click',()=>{const deck=button.dataset.deckTab;document.querySelectorAll('[data-deck-panel]').forEach(panel=>panel.hidden=panel.dataset.deckPanel!==deck);document.querySelectorAll('[data-deck-tab]').forEach(tab=>{const active=tab.dataset.deckTab===deck;tab.classList.toggle('bg-white',active);tab.classList.toggle('text-slate-900',active);tab.classList.toggle('shadow-sm',active);tab.classList.toggle('text-slate-500',!active)})}));document.querySelector('[data-deck-tab]')?.click();[holderName,holderDocument].forEach(field=>field.addEventListener('input',()=>{passengers.querySelector('.primary-name')?.setAttribute('value',holderName.value);passengers.querySelector('.primary-document')?.setAttribute('value',holderDocument.value)}));document.getElementById('holderDocumentType').addEventListener('change',event=>passengers.querySelector('.primary-document-type')?.setAttribute('value',event.target.value));render()})();
</script>
</x-public-layout>



