<x-app-layout>
 <x-slot name="header"><h2 class="ny-page-title">Usuarios y permisos</h2></x-slot>
 <div class="mx-auto max-w-7xl space-y-6">
  @if(session('success'))<div class="rounded-xl bg-emerald-50 px-5 py-4 text-emerald-800">{{session('success')}}</div>@endif
  <section style="border-radius:20px;padding:28px;background:linear-gradient(110deg,#103d35,#1d705e);color:white"><p style="margin:0;color:#f2c348;font-size:12px;font-weight:800;letter-spacing:.12em">CONTROL DE ACCESO</p><h1 style="margin:8px 0;font-size:28px">Usuarios y permisos</h1><p style="margin:0;color:#d9ece6">Un solo panel administrativo. Cada usuario recibe únicamente los módulos que necesita.</p></section>
  <section style="border:1px solid #dbe6e1;border-radius:18px;background:#fff;padding:28px"><div style="display:flex;align-items:center;gap:12px"><span style="display:grid;place-items:center;width:36px;height:36px;border-radius:10px;background:#e8f5f0;color:#0d6b5e">+</span><div><h2 style="margin:0;font-size:20px">Nuevo administrador</h2><p style="margin:3px 0 0;color:#64748b;font-size:14px">Completa sus datos y define sus accesos.</p></div></div>
   <form method="POST" action="{{route('admin.users.store')}}" style="margin-top:24px">@csrf
    <div style="display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:14px"><label style="font-weight:700">Nombre<input required name="name" value="{{old('name')}}" placeholder="Nombre completo" style="display:block;width:100%;margin-top:6px;border:1px solid #cbdad4;border-radius:8px;padding:11px"></label><label style="font-weight:700">Correo<input required type="email" name="email" value="{{old('email')}}" placeholder="correo@empresa.com" style="display:block;width:100%;margin-top:6px;border:1px solid #cbdad4;border-radius:8px;padding:11px"></label><label style="font-weight:700">Empresa afiliada<select name="organization_id" style="display:block;width:100%;margin-top:6px;border:1px solid #cbdad4;border-radius:8px;padding:11px"><option value="">Acceso general</option>@foreach($organizations as $organization)<option value="{{$organization->id}}">{{$organization->commercial_name ?: $organization->legal_name}}</option>@endforeach</select></label><label style="font-weight:700">Contraseña<input required type="password" name="password" style="display:block;width:100%;margin-top:6px;border:1px solid #cbdad4;border-radius:8px;padding:11px"></label><label style="font-weight:700">Confirmar contraseña<input required type="password" name="password_confirmation" style="display:block;width:100%;margin-top:6px;border:1px solid #cbdad4;border-radius:8px;padding:11px"></label></div>
    <div style="margin-top:24px;border-top:1px solid #e7eeeb;padding-top:20px"><h3 style="margin:0;font-size:17px">Módulos permitidos</h3><p style="margin:5px 0 14px;color:#64748b;font-size:13px">Marca las áreas que podrá usar este administrador.</p><div style="display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:10px">@foreach($permissions as $group=>$items)<fieldset style="border:1px solid #dbe6e1;border-radius:10px;padding:12px"><legend style="padding:0 5px;color:#0d6b5e;font-size:11px;font-weight:800;text-transform:uppercase">{{$group}}</legend>@foreach($items as $permission)<label style="display:flex;align-items:flex-start;gap:8px;padding:6px 0;font-size:13px"><input type="checkbox" name="permissions[]" value="{{$permission->id}}" @checked(in_array($permission->id,old('permissions',[])))><span><strong style="display:block">{{$permission->name}}</strong><small style="color:#71847d">{{$permission->description}}</small></span></label>@endforeach</fieldset>@endforeach</div></div>
    <div style="display:flex;justify-content:flex-end;margin-top:22px"><button style="border:0;border-radius:8px;padding:12px 20px;background:#eab634;color:#12372d;font-weight:800;cursor:pointer">Crear administrador</button></div>
   </form>
  </section>
  <section style="overflow:hidden;border:1px solid #dbe6e1;border-radius:18px;background:#fff"><div style="padding:20px 24px;border-bottom:1px solid #e7eeeb"><h2 style="margin:0;font-size:20px">Administradores registrados</h2></div><div>@foreach($users as $user)<article style="padding:20px 24px;border-bottom:1px solid #eef2f0"><div style="display:flex;justify-content:space-between;gap:22px"><div style="min-width:210px"><h3 style="margin:0">{{$user->name}}</h3><p style="margin:5px 0;color:#64748b;font-size:14px">{{$user->email}}</p><span style="display:inline-block;margin-top:5px;border-radius:20px;padding:4px 8px;background:#e8f5f0;color:#0d6b5e;font-size:11px;font-weight:800">{{$user->organizations->pluck('commercial_name')->filter()->join(', ') ?: 'Acceso general'}}</span></div>@if($user->roles->contains('code','super_admin'))<span style="height:max-content;border-radius:20px;padding:6px 10px;background:#fff1c9;color:#8a6200;font-size:12px;font-weight:800">Acceso total</span>@else<form method="POST" action="{{route('admin.users.update',$user)}}" style="flex:1">@csrf @method('PATCH')<div style="display:flex;align-items:center;gap:10px"><label style="font-size:13px;font-weight:700">Empresa<select name="organization_id" style="margin-left:6px;border:1px solid #cbdad4;border-radius:7px;padding:7px"><option value="">General</option>@foreach($organizations as $organization)<option value="{{$organization->id}}" @selected($user->organizations->contains('id',$organization->id))>{{$organization->commercial_name ?: $organization->legal_name}}</option>@endforeach</select></label><button style="margin-left:auto;border:0;border-radius:7px;padding:8px 12px;background:#0d6b5e;color:white;font-weight:800;cursor:pointer">Guardar</button></div><div style="display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:7px;margin-top:12px">@foreach($permissions as $items)@foreach($items as $permission)<label style="display:flex;align-items:center;gap:6px;border-radius:7px;background:#f5f8f7;padding:7px;font-size:12px"><input type="checkbox" name="permissions[]" value="{{$permission->id}}" @checked($user->permissions->contains('id',$permission->id))>{{$permission->name}}</label>@endforeach @endforeach</div></form>@endif</div></article>@endforeach</div><div style="padding:16px 24px">{{$users->links()}}</div></section>
 </div>
</x-app-layout>
