<x-app-layout>
<x-slot name="header"><h2 class="ny-page-title">Plano de asientos</h2></x-slot>
<style>
.sp{max-width:1180px;margin:auto;color:#183d35}.back{color:#126858;font-size:13px;font-weight:850;text-decoration:none}.hero{display:flex;justify-content:space-between;align-items:center;gap:24px;margin-top:15px;padding:28px 32px;border-radius:24px;background:linear-gradient(125deg,#0c3b32,#176d60);color:#fff;box-shadow:0 18px 40px #0a393018}.hero .eyebrow{margin:0;color:#f5c344;font-size:11px;font-weight:900;letter-spacing:.16em}.hero h1{margin:7px 0 5px;font-size:32px}.hero p{margin:0;color:#d8eee8}.stats{display:flex;gap:10px}.stat{min-width:110px;padding:11px;border:1px solid #ffffff33;border-radius:14px;background:#ffffff10;text-align:center}.stat b{display:block;font-size:20px}.stat span{font-size:9px;color:#cce7df;letter-spacing:.08em;text-transform:uppercase}
.tabs{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin:18px 0}.tab{display:flex;justify-content:space-between;align-items:center;padding:13px 16px;border:1px solid #d4e4df;border-radius:14px;background:#fff;color:#31564d;font-size:13px;font-weight:850;text-decoration:none}.tab.active{border-color:#126858;background:#126858;color:#fff;box-shadow:0 8px 20px #12685829}.tab small{display:grid;place-items:center;min-width:28px;height:24px;border-radius:99px;background:#12685817}.tab.active small{background:#ffffff29}.ok{padding:13px 16px;border-radius:12px;background:#e7f8f1;color:#087057;font-weight:750}
.layout{display:grid;grid-template-columns:340px minmax(0,1fr);gap:22px;align-items:start}.panel,.map{padding:23px;border:1px solid #dbe8e4;border-radius:20px;background:#fff;box-shadow:0 10px 32px #1d493f0f}.panel{position:sticky;top:18px}.panel h2,.map h2{margin:0;color:#143c33;font-size:19px}.panel p{color:#647a74;font-size:13px;line-height:1.55}.note{padding:10px!important;border-radius:10px;background:#fff7df;color:#916300!important}.fields{display:grid;grid-template-columns:1fr 1fr;gap:13px;margin-top:18px}.fields label{font-size:11px;font-weight:850;color:#38554e;text-transform:uppercase}.fields input,.fields select{box-sizing:border-box;width:100%;margin-top:6px;padding:11px;border:1px solid #cbdad5;border-radius:10px;background:#fbfdfc;color:#173b33;font:inherit;text-transform:none}.fields .full{grid-column:1/-1}.capacity{margin-top:14px;padding:13px;border-radius:11px;background:#edf7f4;color:#31544c;font-size:12px;line-height:1.55}.button{display:inline-flex;justify-content:center;border:0;border-radius:11px;padding:12px 15px;background:#123d34;color:#fff;font-weight:850;text-decoration:none;cursor:pointer}.button.warn{background:#fff0f1;color:#b4233f}.actions{display:flex;gap:9px;flex-wrap:wrap;margin-top:16px}
.map-head{display:flex;justify-content:space-between;gap:18px;margin-bottom:20px}.map-head p{margin:5px 0;color:#687d77;font-size:12px}.legend{display:flex;gap:12px;font-size:11px;color:#526760}.legend span{display:flex;align-items:center;gap:5px}.legend i{width:11px;height:11px;border-radius:4px}.stage{overflow:auto;padding:18px 10px 30px;border:1px solid #dbeef6;border-radius:18px;background:radial-gradient(circle at 50% 8%,#dff4fc,#f4fbfe 58%,#fff)}
.boat{position:relative;box-sizing:border-box;width:var(--boat-width);max-width:none;margin:42px auto 22px;padding:70px 38px 45px;border:2px solid #7cbcd3;border-radius:46% 46% 19% 19% / 14% 14% 7% 7%;background:linear-gradient(90deg,#e3f4fa,#fff 14%,#fff 86%,#e3f4fa);box-shadow:0 20px 38px #145b7824,inset 0 0 0 8px #f1f9fc}.boat:before{content:"PROA";position:absolute;top:-34px;left:50%;transform:translateX(-50%);display:grid;place-items:center;width:116px;height:57px;border:2px solid #7cbcd3;border-bottom:0;border-radius:70px 70px 0 0;background:#f4fbfe;color:#0d6687;font-size:10px;font-weight:900;letter-spacing:.15em}.boat:after{content:"";position:absolute;left:50%;bottom:-19px;transform:translateX(-50%);width:82%;height:18px;border:2px solid #7cbcd3;border-top:0;border-radius:0 0 50% 50%;background:#d7edf5}.helm{position:absolute;top:23px;left:50%;transform:translateX(-50%);display:flex;align-items:center;justify-content:center;gap:8px;width:min(220px,60%);height:35px;border:1px solid #b5dce9;border-radius:12px;background:#e3f4fa;color:#245e74;font-size:10px;font-weight:900;letter-spacing:.11em}.helm b{font-size:18px}
.cabin{position:relative;padding:18px 20px;border:1px solid #cce5ef;border-radius:22px;background:#f9fdffeb}.cabin:before{content:"PASILLO CENTRAL";position:absolute;top:50%;left:50%;transform:translate(-50%,-50%) rotate(-90deg);padding:5px 9px;border-radius:99px;background:#fff;color:#7da0ae;font-size:8px;font-weight:900;letter-spacing:.12em;white-space:nowrap;box-shadow:0 0 0 1px #dcecf2}.row{display:grid;align-items:center;gap:7px;margin:9px 0}.rowno{font-size:10px;font-weight:900;color:#7093a1;text-align:center}.sf{margin:0}.seat{display:grid;place-items:center;width:40px;height:38px;border:1px solid #86c7de;border-radius:11px 11px 8px 8px;background:linear-gradient(#dff5fc,#c9ebf7);color:#075f82;font-size:11px;font-weight:900;cursor:pointer;box-shadow:0 3px 0 #8dc8dc}.seat:hover{transform:translateY(-2px);background:linear-gradient(#c9effc,#addff0)}.seat.blocked{border-color:#d9dfe0;background:#e9edee;color:#98a5a8;text-decoration:line-through;box-shadow:0 3px 0 #d1d7d8}.aisle{min-height:38px}.stern{text-align:center;color:#668b99;font-size:9px;font-weight:900;letter-spacing:.15em}.exit{position:absolute;right:34px;bottom:15px;padding:4px 8px;border-radius:6px;background:#dff4fb;color:#096686;font-size:8px;font-weight:900}.empty{padding:70px 20px;text-align:center;color:#647b75}.empty b{display:block;margin-bottom:7px;color:#244b42;font-size:17px}.empty i{display:block;font-style:normal;font-size:42px}
@media(max-width:920px){.layout{grid-template-columns:1fr}.panel{position:static}.hero{align-items:flex-start}}@media(max-width:620px){.hero{display:block;padding:24px}.stats{margin-top:18px}.tabs,.fields{grid-template-columns:1fr}.map-head{display:block}.legend{margin-top:12px}.map{padding:14px}}
</style>
<div class="sp">
<a class="back" href="{{route('admin.vessels.index')}}">← Volver a embarcaciones</a>
<section class="hero"><div><p class="eyebrow">CONFIGURACIÓN DE EMBARCACIÓN</p><h1>{{$vessel->name}}</h1><p>Matrícula {{$vessel->registration_number}} · Diseña cada cubierta y controla los asientos habilitados.</p></div><div class="stats"><div class="stat"><b>{{$vessel->seat_capacity}}</b><span>Capacidad máxima</span></div><div class="stat"><b>{{($deckCounts['principal']??0)+($deckCounts['superior']??0)}}</b><span>Asientos creados</span></div></div></section>
<nav class="tabs"><a class="tab {{$deck==='principal'?'active':''}}" href="{{route('admin.vessels.seats.edit',['vessel'=>$vessel,'deck'=>'principal'])}}"><span>▰ Cubierta principal</span><small>{{$deckCounts['principal']??0}}</small></a><a class="tab {{$deck==='superior'?'active':''}}" href="{{route('admin.vessels.seats.edit',['vessel'=>$vessel,'deck'=>'superior'])}}"><span>▱ Cubierta superior</span><small>{{$deckCounts['superior']??0}}</small></a></nav>
@if(session('success'))<p class="ok">✓ {{session('success')}}</p>@endif
<div class="layout">
<section class="panel">
@if($seats->isEmpty()||$isEditing)
<h2>{{$isEditing?'Editar':'Crear'}} {{$deck==='principal'?'cubierta principal':'cubierta superior'}}</h2><p>Indica filas y asientos a cada lado. El sistema reservará automáticamente el pasillo central.</p>
@if($isEditing)<p class="note">Guardar reemplazará únicamente esta cubierta. La otra conservará su plano.</p>@endif
<form method="POST" action="{{route('admin.vessels.seats.generate',$vessel)}}">@csrf @if($isEditing)<input type="hidden" name="replace_existing" value="1">@endif
<div class="fields"><label>Filas<input id="rows" type="number" name="rows" value="{{old('rows',max(1,$seats->max('row_position')?:10))}}" min="1" max="100" required></label><label>Categoría<select name="seat_class"><option value="standard">Estándar</option><option value="premium">Premium</option><option value="business">Business</option></select></label><label>Asientos izquierda<input id="leftSeats" type="number" name="left_seats" value="{{old('left_seats',2)}}" min="1" max="6" required></label><label>Asientos derecha<input id="rightSeats" type="number" name="right_seats" value="{{old('right_seats',2)}}" min="1" max="6" required></label><label class="full">Nivel<input value="{{$deck==='principal'?'Cubierta principal':'Cubierta superior'}}" disabled><input type="hidden" name="deck" value="{{$deck}}"></label></div>
<div id="seatPreview" class="capacity" data-limit="{{$vessel->seat_capacity}}" data-other="{{$otherDeckSeats}}">Esta cubierta: <strong id="seatCount">0</strong> asientos<br>Otras cubiertas: <strong>{{$otherDeckSeats}}</strong> · Total: <strong id="totalSeatCount">{{$otherDeckSeats}}</strong> de {{$vessel->seat_capacity}}</div>
@if($errors->any())<div style="color:#be123c;font-size:12px">@foreach($errors->all() as $error)<p>{{$error}}</p>@endforeach</div>@endif
<button id="generateButton" class="button" style="width:100%;margin-top:18px">{{$isEditing?'Guardar nuevo plano':'Generar plano de cubierta'}}</button></form>
@else
<h2>Plano configurado</h2><p>La {{$deck==='principal'?'cubierta principal':'cubierta superior'}} tiene <strong>{{$seats->count()}} asientos</strong>. Pulsa cada asiento para bloquearlo o habilitarlo.</p><div class="actions"><a class="button" href="{{route('admin.vessels.seats.edit',['vessel'=>$vessel,'deck'=>$deck,'edit'=>1])}}">Editar distribución</a><form method="POST" action="{{route('admin.vessels.seats.destroy-deck',$vessel)}}" onsubmit="return confirm('¿Eliminar el plano de esta cubierta?')">@csrf @method('DELETE')<input type="hidden" name="deck" value="{{$deck}}"><button class="button warn">Eliminar</button></form></div>
@endif
</section>
<section class="map"><div class="map-head"><div><h2>{{$deck==='principal'?'Cubierta principal':'Cubierta superior'}}</h2><p>Vista desde arriba · toca un asiento para cambiar su disponibilidad.</p></div><div class="legend"><span><i style="background:#ccece3"></i>Disponible</span><span><i style="background:#e5eaeb"></i>Bloqueado</span></div></div>
@if($seats->isNotEmpty())
@php($maxColumn=$seats->max('column_position'))
<div class="stage"><div class="boat" style="--boat-width:{{max(390,118+($maxColumn*47))}}px"><div class="helm"><b>◉</b> CABINA DE MANDO</div><div class="cabin">
@foreach($seats->groupBy('row_position') as $row=>$rowSeats)
<div class="row" style="grid-template-columns:28px repeat({{$maxColumn}},40px)"><span class="rowno">{{str_pad($row,2,'0',STR_PAD_LEFT)}}</span>
@for($column=1;$column<=$maxColumn;$column++) @php($seat=$rowSeats->firstWhere('column_position',$column))
@if($seat)<form class="sf" method="POST" action="{{route('admin.vessels.seats.toggle',[$vessel,$seat])}}">@csrf @method('PATCH')<button title="{{$seat->is_available?'Asiento disponible':'Asiento bloqueado'}}" class="seat {{$seat->is_available?'':'blocked'}}">{{$seat->code}}</button></form>@else<span class="aisle"></span>@endif
@endfor</div>
@endforeach
</div><div class="exit">SALIDA</div><p class="stern">POPA · PARTE POSTERIOR</p></div></div>
@else<div class="empty"><i>⛴</i><b>Esta cubierta todavía no tiene distribución</b>Configura las filas y asientos para visualizar la lancha.</div>@endif
</section></div></div>
<script>
const updateCount=()=>{const rows=Number(document.getElementById('rows')?.value)||0,left=Number(document.getElementById('leftSeats')?.value)||0,right=Number(document.getElementById('rightSeats')?.value)||0,preview=document.getElementById('seatPreview');if(!preview)return;const current=rows*(left+right),total=current+Number(preview.dataset.other),limit=Number(preview.dataset.limit),button=document.getElementById('generateButton'),exceeds=total>limit;document.getElementById('seatCount').textContent=current;document.getElementById('totalSeatCount').textContent=total;preview.style.background=exceeds?'#fff1f2':'#edf7f4';preview.style.color=exceeds?'#be123c':'#31544c';button.disabled=exceeds;button.style.opacity=exceeds?'.5':'1';button.title=exceeds?'La suma de ambas cubiertas supera la capacidad máxima.':''};['rows','leftSeats','rightSeats'].forEach(id=>document.getElementById(id)?.addEventListener('input',updateCount));updateCount();
</script>
</x-app-layout>
