<x-app-layout>
<x-slot name="header"><h1 class="ny-page-title">Liquidaciones y comisiones</h1></x-slot>
<div class="space-y-6">
 <section class="rounded-3xl bg-[#062c21] p-7 text-white"><span class="text-[10px] font-black uppercase tracking-widest text-emerald-300">Tesorería regional</span><h1 class="mt-2 text-2xl font-black">Conciliación financiera</h1><p class="mt-1 text-xs text-emerald-100/70">Control del dinero procesado, comisión de plataforma y saldos por transferir.</p></section>
 <section class="grid gap-3 sm:grid-cols-3"><article class="rounded-2xl border bg-white p-5"><span class="text-[10px] font-bold uppercase text-slate-400">GMV bruto acumulado</span><strong class="mt-2 block text-2xl font-black">S/ {{ number_format($grossVolume,2) }}</strong></article><article class="rounded-2xl border bg-white p-5"><span class="text-[10px] font-bold uppercase text-slate-400">Comisión neta NavegaYA</span><strong class="mt-2 block text-2xl font-black text-amber-600">S/ {{ number_format($netCommission,2) }}</strong></article><article class="rounded-2xl border bg-white p-5"><span class="text-[10px] font-bold uppercase text-slate-400">Pendiente a transportistas</span><strong class="mt-2 block text-2xl font-black text-emerald-700">S/ {{ number_format($pendingPayout,2) }}</strong></article></section>
 @if(session('success'))<div class="rounded-xl bg-emerald-50 p-4 text-sm font-bold text-emerald-800">{{ session('success') }}</div>@endif
 <section class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div class="overflow-x-auto"><table class="min-w-[1050px] w-full text-left text-xs"><thead class="bg-slate-50 text-[10px] uppercase text-slate-400"><tr><th class="p-4">Empresa</th><th class="p-4">Cuenta / CCI</th><th class="p-4">Comisión</th><th class="p-4">Saldo pendiente</th><th class="p-4">Registrar transferencia</th></tr></thead><tbody class="divide-y">@foreach($organizations as $organization)<tr><td class="p-4"><strong>{{ $organization->commercial_name ?: $organization->legal_name }}</strong><br><span class="text-slate-400">RUC {{ $organization->ruc }}</span></td><td class="p-4">{{ $organization->bank_name ?: 'Sin banco' }}<br><span class="font-mono text-slate-400">{{ $organization->bank_cci ?: $organization->bank_account ?: 'CCI pendiente' }}</span></td><td class="p-4 font-bold">{{ number_format((float)$organization->commission_rate,2) }}%</td><td class="p-4 font-black">S/ {{ number_format((float)$organization->pending_payout_balance,2) }}</td><td class="p-4"><form method="POST" action="{{ route('admin.settlements.store',$organization) }}" class="flex gap-2">@csrf<input type="date" name="period_start" required class="h-8 w-32 rounded-lg border-slate-200 text-[10px]"><input type="date" name="period_end" required class="h-8 w-32 rounded-lg border-slate-200 text-[10px]"><input name="reference" required placeholder="N° operación" class="h-8 w-32 rounded-lg border-slate-200 text-[10px]"><button @disabled((float)$organization->pending_payout_balance<=0) class="rounded-lg bg-amber-500 px-3 text-[10px] font-bold disabled:opacity-40">Registrar pago</button></form></td></tr>@endforeach</tbody></table></div></section>
 <section class="rounded-2xl border border-slate-200 bg-white p-5"><h2 class="font-black">Historial de liquidaciones</h2><div class="mt-3 space-y-2">@forelse($settlements as $settlement)<div class="flex justify-between rounded-xl bg-slate-50 p-3 text-xs"><span><strong>{{ $settlement->organization->commercial_name ?: $settlement->organization->legal_name }}</strong> · {{ $settlement->period_start->format('d/m/Y') }}–{{ $settlement->period_end->format('d/m/Y') }}</span><strong>S/ {{ number_format((float)$settlement->net_amount,2) }} · {{ $settlement->reference }}</strong></div>@empty<p class="text-sm text-slate-400">Aún no existen liquidaciones registradas.</p>@endforelse</div><div class="mt-4">{{ $settlements->links() }}</div></section>
</div>
</x-app-layout>
