<x-app-layout>
<x-slot name="header"><h2 class="ny-page-title">{{ isset($port) ? 'Editar puerto' : 'Registrar puerto' }}</h2></x-slot>
@php
$isEdit=isset($port); $field=fn(string $key,mixed $default='')=>old($key,$isEdit?$port->{$key}:$default); $provinceUrl=route('admin.locations.provinces',['department'=>'__ID__']); $districtUrl=route('admin.locations.districts',['province'=>'__ID__']);
@endphp
<style>.port-form-wrap{max-width:none;width:100%;margin:0}.port-card{margin-top:14px;padding:30px 34px;border:1px solid #dbe8e4;border-radius:20px;background:#fff;box-shadow:0 12px 32px rgba(16,53,47,.06)}.port-card h1{margin:0;color:#12372d;font-size:25px}.port-intro{margin:7px 0 0;color:#64748b;font-size:14px}.port-section{margin-top:25px;padding-top:20px;border-top:1px solid #edf3f0}.port-section h2{margin:0;color:#176d60;font-size:16px}.port-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:15px;margin-top:16px}.port-grid.two{grid-template-columns:repeat(2,minmax(0,1fr))}.port-grid label{display:block;color:#334155;font-size:12px;font-weight:800}.port-grid input,.port-grid select,.port-grid textarea{box-sizing:border-box;width:100%;margin-top:6px;padding:10px 11px;border:1px solid #cbd5e1;border-radius:9px;background:#fff;color:#1e293b}.port-grid textarea{min-height:84px;resize:vertical}.port-grid select:disabled{background:#f5f7f6;color:#94a3b8}.port-grid input.port-fixed{background:#f1f5f4;color:#64748b;border-color:#d8e2de;cursor:not-allowed}.port-help{margin-top:12px;padding:11px 13px;border-radius:10px;background:#eff9f5;color:#356056;font-size:12px}.port-save{margin-top:24px;border:0;border-radius:10px;background:#12372d;padding:11px 17px;color:#fff;font-weight:800;cursor:pointer}.port-cancel{margin-left:8px;color:#176d60;font-size:13px;font-weight:800;text-decoration:none}.port-status{display:flex;align-items:center;gap:8px;margin-top:22px;font-size:13px;font-weight:700;color:#334155}@media(max-width:850px){.port-grid,.port-grid.two{grid-template-columns:1fr 1fr}}@media(max-width:600px){.port-grid,.port-grid.two{grid-template-columns:1fr}.port-card{padding:21px}}</style>
<div class="port-form-wrap"><a href="{{ route('admin.ports.index') }}" class="port-cancel" style="margin-left:0">← Volver a puertos</a><form method="POST" action="{{ $isEdit?route('admin.ports.update',$port):route('admin.ports.store') }}" class="port-card">@csrf
@if($isEdit)
@method('PATCH')
@endif
<h1>{{ $isEdit?'Editar puerto o terminal':'Nuevo puerto o terminal' }}</h1><p class="port-intro">Catálogo oficial de infraestructura fluvial y aérea de Loreto.</p>
<section class="port-section" style="margin-top:18px;padding-top:0;border-top:0"><h2>Ubicación administrativa</h2><div class="port-grid"><label>Departamento<input value="Loreto" readonly class="port-fixed"><input type="hidden" name="department_id" value="{{ $loreto->id }}"></label><label>Provincia<select id="province" name="province_id" required><option value="">Selecciona provincia</option>@foreach($initialProvinces as $province)<option value="{{ $province->id }}" @selected($field('province_id')==$province->id)>{{ $province->name }}</option>@endforeach</select></label><label>Distrito<select id="district" name="district_id" required @disabled(!$field('province_id'))><option value="">Primero provincia</option>@foreach($initialDistricts as $district)<option value="{{ $district->id }}" @selected($field('district_id')==$district->id)>{{ $district->name }}</option>@endforeach</select></label></div><div class="port-help">El puerto se registra una sola vez. Será salida o llegada según el orden que tenga dentro de cada ruta.</div></section>
<section class="port-section"><h2>Identificación y operación</h2><div class="port-grid"><label>Nombre del puerto o terminal<input name="name" required value="{{ $field('name') }}" placeholder="Ej. Puerto La Boca"></label><label>Modalidad<select name="modality" required><option value="fluvial" @selected($field('modality','fluvial')==='fluvial')>🚤 Fluvial</option><option value="aereo" @selected($field('modality')==='aereo')>✈️ Aéreo</option></select></label><label>Tipo de instalación<select name="port_type" required>@foreach(['terminal'=>'Terminal fluvial','embarcadero'=>'Embarcadero','muelle'=>'Muelle','muelle_flotante'=>'Muelle flotante','privado'=>'Puerto privado','aerodromo'=>'Aeródromo / pista','otro'=>'Otro'] as $value=>$label)<option value="{{ $value }}" @selected($field('port_type','embarcadero')===$value)>{{ $label }}</option>@endforeach</select></label><label>Río, pista o referencia<input name="river" required value="{{ $field('river') }}" placeholder="Ej. Amazonas"></label><label>Teléfono de contacto<input name="contact_phone" value="{{ $field('contact_phone') }}" placeholder="Ej. 999 999 999"></label><label style="grid-column:span 2">Referencia o dirección<input name="address" value="{{ $field('address') }}" placeholder="Ej. frente al mercado, muelle principal"></label></div></section>
<section class="port-section"><h2>Acceso y servicios</h2><div class="port-grid two"><label>Indicaciones de acceso<textarea name="access_notes" placeholder="Acceso por mototaxi, restricciones, horario de carga, etc.">{{ $field('access_notes') }}</textarea></label><label>Servicios disponibles<textarea name="available_services" placeholder="Baños, sala de espera, estacionamiento, carga, seguridad, venta de alimentos, etc.">{{ $field('available_services') }}</textarea></label><label>Latitud (opcional)<input type="number" step="0.0000001" name="latitude" value="{{ $field('latitude') }}"></label><label>Longitud (opcional)<input type="number" step="0.0000001" name="longitude" value="{{ $field('longitude') }}"></label></div><label class="port-status"><input type="checkbox" name="is_active" value="1" @checked($field('is_active',true))> Puerto habilitado para crear rutas y salidas</label></section>
@if($errors->any())
<div style="margin-top:18px;padding:12px;border-radius:10px;background:#fff1f2;color:#be123c;font-size:13px"><ul>@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>
@endif
<button class="port-save">{{ $isEdit?'Guardar cambios':'Guardar puerto' }}</button><a class="port-cancel" href="{{ route('admin.ports.index') }}">Cancelar</a></form></div>
<script>const province=document.getElementById('province'),district=document.getElementById('district'),districtUrl=@json($districtUrl);function reset(s,label){s.innerHTML=`<option value="">${label}</option>`;s.disabled=true}async function fill(s,url,label){reset(s,'Cargando...');try{const rows=await fetch(url,{headers:{Accept:'application/json'}}).then(r=>r.json());s.innerHTML=`<option value="">${label}</option>`+rows.map(row=>`<option value="${row.id}">${row.name}</option>`).join('');s.disabled=false}catch{reset(s,'No se pudo cargar')}}province.addEventListener('change',()=>province.value?fill(district,districtUrl.replace('__ID__',province.value),'Selecciona distrito'):reset(district,'Primero provincia'));</script>
</x-app-layout>

