<x-app-layout>
 <x-slot name="header"><h2 class="ny-page-title">{{ $creating ? 'Nuevo destino' : 'Editar destino' }}</h2></x-slot>
 <div class="mx-auto max-w-5xl"><a class="font-bold text-[#0d6b5e]" href="{{route('admin.destinations.index')}}">← Volver a destinos</a>
 <form method="POST" enctype="multipart/form-data" action="{{ $creating ? route('admin.destinations.store') : route('admin.destinations.update',$city) }}" class="mt-5 rounded-2xl bg-white p-7 shadow-sm ring-1 ring-slate-200">@csrf @if(!$creating)@method('PATCH')@endif
  @if($errors->any())<div class="mb-5 rounded-xl bg-rose-50 p-4 text-rose-800">@foreach($errors->all() as $error)<p>{{$error}}</p>@endforeach</div>@endif
  <p class="text-xs font-bold uppercase tracking-widest text-[#0d6b5e]">Ficha pública</p><h1 class="mt-2 text-2xl font-bold">{{ $creating ? 'Crear destino amazónico' : $city->name }}</h1><p class="mt-2 text-slate-600">Esta ficha alimenta las tarjetas de la portada y la página Descubrir.</p>
  <div class="mt-6 grid gap-5 md:grid-cols-3"><label class="font-semibold">Nombre de la ciudad<input required name="name" value="{{old('name',$city->name)}}" class="mt-1 w-full rounded-lg border-slate-300" placeholder="Ej. Requena"></label><label class="font-semibold">Departamento<input required name="department" value="{{old('department',$city->department ?: 'Loreto')}}" class="mt-1 w-full rounded-lg border-slate-300"></label><label class="font-semibold">Río<input name="river" value="{{old('river',$city->river)}}" class="mt-1 w-full rounded-lg border-slate-300" placeholder="Ej. Ucayali"></label></div>
  <div class="mt-5 grid gap-5 md:grid-cols-2"><label class="font-semibold">Orden en portada<input required type="number" min="1" name="sort_order" value="{{old('sort_order',$city->sort_order)}}" class="mt-1 w-full rounded-lg border-slate-300"><span class="mt-1 block text-sm font-normal text-slate-500">1 aparece primero.</span></label><label class="flex items-center gap-2 pt-7 font-semibold"><input type="checkbox" name="is_active" value="1" @checked(old('is_active',$city->is_active))> Publicar destino en portada y Descubrir</label></div>
  <div class="mt-6 border-t pt-6"><h2 class="text-lg font-bold">Imagen de portada</h2><div class="mt-3 grid gap-5 md:grid-cols-2"><label class="font-semibold">Subir imagen<input type="file" accept="image/*" name="image" class="mt-1 w-full rounded-lg border-slate-300"></label><label class="font-semibold">o URL de imagen<input type="url" name="image_url" value="{{old('image_url',$city->image_url)}}" placeholder="https://..." class="mt-1 w-full rounded-lg border-slate-300"></label></div>@if($city->image_url)<img src="{{$city->image_url}}" alt="Vista previa" class="mt-4 h-44 w-full rounded-xl object-cover">@endif</div>
  <label class="mt-6 block font-semibold">Descripción pública<textarea name="summary" rows="4" class="mt-1 w-full rounded-lg border-slate-300" placeholder="Presenta la ciudad, su cultura y por qué visitarla.">{{old('summary',$city->summary)}}</textarea></label>
  <section class="mt-6 rounded-xl border border-emerald-100 bg-emerald-50 p-5"><h2 class="font-bold text-[#0d6b5e]">Contenido relacionado</h2><p class="mt-1 text-sm text-slate-600">Los lugares turísticos, hospedajes y gastronomía se registran como fichas independientes para evitar duplicar información y poder mostrarlos automáticamente en la portada.</p><div class="mt-4 flex flex-wrap gap-3"><a class="font-bold text-[#0d6b5e]" href="{{route('admin.destination-listings.index','attraction')}}">Lugares turísticos →</a><a class="font-bold text-[#0d6b5e]" href="{{route('admin.destination-listings.index','lodging')}}">Hospedajes →</a><a class="font-bold text-[#0d6b5e]" href="{{route('admin.destination-listings.index','gastronomy')}}">Gastronomía →</a></div></section><button style="display:inline-block;margin-top:28px;border:0;border-radius:8px;padding:12px 20px;background:#0d6b5e;color:#fff;font-weight:800;cursor:pointer">{{ $creating ? 'Crear destino' : 'Guardar cambios' }}</button>
 </form></div>
</x-app-layout>


