<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{{ $city->name }} · NavegaYA</title><style>body{margin:0;background:#f5f4ef;font-family:Arial;color:#153b32}.hero{padding:70px 8%;background:linear-gradient(90deg,#0f352ddd,#176d6099),url('{{ $city->image_url }}') center/cover;color:white}.wrap{max-width:1100px;margin:30px auto;padding:0 20px}.box{background:#fff;padding:24px;border-radius:16px;margin:16px 0;box-shadow:0 3px 14px #12372d12}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:16px}.stars{color:#eab634;font-size:22px}.button{border:0;border-radius:8px;background:#0d6b5e;color:white;padding:11px 15px;font-weight:bold}@media(max-width:750px){.grid{grid-template-columns:1fr}}</style></head><body><x-public-nav current="discover"/><section class="hero public-page-hero"><a style="color:white" href="{{ route('discover.index') }}">← Todos los destinos</a><p>{{ $city->department }} · Río {{ $city->river }}</p><h1>{{ $city->name }}</h1><p>{{ $city->summary ?: 'Explora rutas, cultura y naturaleza amazónica.' }}</p></section><main class="wrap">@if(session('success'))<p class="box" style="color:#08755f">{{session('success')}}</p>@endif<section class="grid"><div class="box"><h2>Atractivos</h2><p>{{ $city->attractions ?: 'Información próximamente.' }}</p></div><div class="box"><h2>Hospedajes</h2><p>{{ $city->lodging ?: 'Información próximamente.' }}</p></div><div class="box"><h2>Gastronomía</h2><p>{{ $city->gastronomy ?: 'Información próximamente.' }}</p></div></section><section class="box"><h2>Rutas disponibles</h2>@forelse($routes as $route)<p><strong>{{ $route->originPort->city }} → {{ $route->destinationPort->city }}</strong><br>{{ $route->originPort->name }} → {{ $route->destinationPort->name }}</p>@empty<p>Aún no hay rutas activas registradas.</p>@endforelse</section><section class="box"><h2>Valoraciones de viajeros</h2><p class="stars">{{ str_repeat('★', (int) round($average)) }}{{ str_repeat('☆', 5-(int) round($average)) }} <strong>{{ $average ?: 'Sin valoraciones' }}</strong></p>@forelse($reviews as $review)<article style="border-top:1px solid #e4ebe8;padding:14px 0"><strong>{{ $review->user->name }}</strong><span class="stars"> {{ str_repeat('★',$review->rating) }}</span><p>{{ $review->comment }}</p></article>@empty<p>Aún no hay valoraciones verificadas.</p>@endforelse</section>
@auth
    @if($canReview)
        <section class="box"><h2>Comparte tu experiencia</h2><p>Tu valoración será publicada después de una revisión.</p><form method="POST" action="{{ route('discover.review', $city) }}">@csrf<label>Calificación <select name="rating"><option value="5">5 · Excelente</option><option value="4">4 · Muy bueno</option><option value="3">3 · Bueno</option><option value="2">2 · Regular</option><option value="1">1 · Malo</option></select></label><br><textarea required minlength="10" name="comment" rows="4" style="width:100%;margin:12px 0" placeholder="Cuéntanos sobre tu viaje"></textarea><button class="button">Enviar valoración</button></form></section>
    @endif
@else
    <section class="box"><h2>¿Ya viajaste?</h2><p><a href="{{ route('login') }}">Ingresa a tu cuenta</a> para valorar este destino después de completar tu viaje.</p></section>
@endauth
</main><x-public-footer/></body></html>


