@extends('layouts.admin')
@section('title','Suscripciones publicitarias · NavegaYA')
@section('content')
<div class="mx-auto max-w-7xl space-y-5">
<section class="rounded-2xl bg-gradient-to-r from-fuchsia-950 to-slate-950 p-6 text-white"><p class="text-[10px] font-black uppercase tracking-widest text-fuchsia-300">Monetización B2B</p><h1 class="mt-1 text-2xl font-black">Suscripciones publicitarias</h1><p class="mt-1 text-xs text-slate-300">Activa planes, registra renovaciones y controla bajas de empresas anunciantes.</p></section>
@if(session('success'))<div class="rounded-xl border border-emerald-200 bg-emerald-50 p-3 text-xs font-bold text-emerald-800">{{ session('success') }}</div>@endif
<section class="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">@foreach([['Activas',$statusCounts['active']??0,'bg-emerald-50 text-emerald-800'],['Por vencer',$statusCounts['overdue']??0,'bg-amber-50 text-amber-800'],['Bajas',$statusCounts['cancelled']??0,'bg-rose-50 text-rose-800'],['Ingreso mensual','S/ '.number_format($monthlyRevenue,2),'bg-fuchsia-50 text-fuchsia-800']] as [$label,$value,$style])<article class="rounded-xl border border-slate-200 p-4 {{ $style }}"><span class="text-[9px] font-black uppercase">{{ $label }}</span><strong class="mt-1 block text-2xl">{{ $value }}</strong></article>@endforeach</section>
<section class="rounded-2xl border border-slate-200 bg-white p-5"><h2 class="text-sm font-black">Activar una suscripción</h2><form method="POST" action="{{ route('admin.advertising-subscriptions.store') }}" class="mt-4 grid gap-3 md:grid-cols-5">@csrf<select name="organization_id" required class="rounded-xl border-slate-200 text-xs"><option value="">Empresa anunciante</option>@foreach($organizations as $organization)<option value="{{ $organization->id }}">{{ $organization->commercial_name ?: $organization->legal_name }}</option>@endforeach</select><select name="subscription_plan_id" required class="rounded-xl border-slate-200 text-xs"><option value="">Plan</option>@foreach($plans as $plan)<option value="{{ $plan->id }}">{{ $plan->name }} · S/ {{ number_format($plan->monthly_price,0) }}</option>@endforeach</select><input type="date" name="starts_on" value="{{ today()->toDateString() }}" required class="rounded-xl border-slate-200 text-xs"><select name="months" class="rounded-xl border-slate-200 text-xs"><option value="1">1 mes</option><option value="3">3 meses</option><option value="6">6 meses</option><option value="12">12 meses</option></select><button class="rounded-xl bg-fuchsia-700 px-4 py-2 text-xs font-black text-white">Activar plan</button></form></section>
<section class="overflow-hidden rounded-2xl border border-slate-200 bg-white"><form method="GET" class="grid gap-2 border-b bg-slate-50 p-4 md:grid-cols-4"><input name="search" value="{{ request('search') }}" placeholder="Empresa o RUC" class="rounded-lg border-slate-200 text-xs"><select name="plan" class="rounded-lg border-slate-200 text-xs"><option value="">Todos los planes</option>@foreach($plans as $plan)<option value="{{ $plan->code }}" @selected(request('plan')===$plan->code)>{{ $plan->name }}</option>@endforeach</select><select name="status" class="rounded-lg border-slate-200 text-xs"><option value="">Todos los estados</option>@foreach(['active'=>'Activo','overdue'=>'Por vencer','cancelled'=>'Baja','expired'=>'Vencido'] as $key=>$label)<option value="{{ $key }}" @selected(request('status')===$key)>{{ $label }}</option>@endforeach</select><button class="rounded-lg bg-slate-900 text-xs font-black text-white">Filtrar</button></form><div class="overflow-x-auto"><table class="w-full text-left text-[10px]"><thead class="bg-slate-50 uppercase text-slate-400"><tr><th class="p-3">Empresa</th><th class="p-3">Plan</th><th class="p-3">Precio</th><th class="p-3">Inicio</th><th class="p-3">Renovación</th><th class="p-3">Estado</th><th class="p-3 text-right">Acciones</th></tr></thead><tbody class="divide-y">@forelse($subscriptions as $subscription)<tr><td class="p-3"><strong>{{ $subscription->organization?->commercial_name ?: $subscription->organization?->legal_name }}</strong><small class="block text-slate-400">{{ $subscription->organization?->ruc }}</small></td><td class="p-3">{{ $subscription->plan?->name }}</td><td class="p-3 font-black">S/ {{ number_format($subscription->monthly_price,2) }}</td><td class="p-3">{{ $subscription->starts_on?->format('d/m/Y') }}</td><td class="p-3">{{ $subscription->ends_on?->format('d/m/Y') ?: 'Sin fecha' }}</td><td class="p-3">{{ strtoupper($subscription->status) }}</td><td class="p-3"><div class="flex justify-end gap-2"><form method="POST" action="{{ route('admin.advertising-subscriptions.renew',$subscription) }}">@csrf @method('PATCH')<input type="hidden" name="months" value="1"><button class="rounded-lg bg-emerald-50 px-2 py-1 font-bold text-emerald-700">Renovar</button></form>@if($subscription->status!=='cancelled')<form method="POST" action="{{ route('admin.advertising-subscriptions.cancel',$subscription) }}">@csrf @method('PATCH')<button onclick="return confirm('¿Registrar esta suscripción como baja?')" class="rounded-lg bg-rose-50 px-2 py-1 font-bold text-rose-700">Dar de baja</button></form>@endif</div></td></tr>@empty<tr><td colspan="7" class="p-10 text-center text-slate-400">Aún no existen suscripciones publicitarias.</td></tr>@endforelse</tbody></table></div><div class="p-4">{{ $subscriptions->links() }}</div></section>
</div>
@endsection
